### ISSUE TITLE
WotLK mods don't load in ICC10

### ISSUE THREAD

**Issue by legolas-a20** [DeadlyBossMods/DeadlyBossMods#1022]
**Describe the bug**
I have DBM and the WotLK mods installed. While playing classic WotLK. In ICC 10, DBM reports that mods are available, but not installed.

**Which version of DeadlyBossMods are you using?**
DBM 10.2.31
DBM dungeons r122-wrath
DBM WotLK mods r326

(If it matters: using WowUp to get the files from wago)

**Comment by jungheeMW** [comment]
Have you checked to see if addons are enabled in the addon list?

**Comment by legolas-a20** [comment]
Hi, yes they are enabled (attached screenshot of them enabled while getting the message, this time in ICC25).

**Comment by MysticalOS** [comment]
The point is do the mods work? the problem with message is that wrath client is still missing api vanilla and cataclysm and retail have for checking if a mod is installed, so it may incorrectly report the mod isn't installed, but as long as it actually works it should work.

Also github doesn't like some image formats that are large, like PNG, you may have to change it to JPG or something

**Comment by legolas-a20** [comment]
Hi, I didn't think to just look in the dbm options... so no, only classic and tbc raids listed in there. So it's not loading.

**Comment by MysticalOS** [comment]
then it has to be installed wrong somehow, maybe too many parent folders, or in wrong addons folder maybe?

**Comment by legolas-a20** [comment]
It's shown in the addon list in WoW itself, so that makes me think it's both installed and found by WoW.

**Comment by MysticalOS** [comment]
![Screenshot 2024-03-30 at 7 49 53 PM](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/1899149/9e6387bb-3b62-4498-97ba-206bc571616f)
Don't know what to tell you.
PEBCAK

**Comment by legolas-a20** [comment]
New version seems to have fixed it, so closing.
