### ISSUE TITLE
PvP addon disabled due to "major patch" that does not affect PvP timers

### ISSUE THREAD

**Issue by Vecht** [DeadlyBossMods/DeadlyBossMods#103]
Previous ticket marked "as spam." Look: it's absolutely infuriating to update this addon every two days because there has been some "major patch" in a PvE instance, and that somehow invalidates my PvP timers in AV. This is completely unnecessary, is massively user unfriendly, and causes a great deal of annoyance and frustration for your users in completely valid use cases. Your system can be trivially improved by not having a global "major patch" flag to automatically disable every single timer in every scenario. This is just poor design and is completely inexcusable.

**Comment by MysticalOS** [comment]
You got your answer here https://github.com/DeadlyBossMods/DeadlyBossMods/issues/102
