### ISSUE TITLE
Windows Defender is detecting threat on update

### ISSUE THREAD

**Issue by jmf191** [DeadlyBossMods/DeadlyBossMods#1038]
**Describe the bug**

Updating Deadly Boss Mods (DBM - Dungeons (All Dungeon Mods) via WowUp from (https://addons.wago.io/addons/deadly-boss-mods-dbm-old-dungeon-mods) is getting blocked by Windows Defender.  It claims it has detected a threat.  

Here is what it says:  "Trojan:Script/Wacatac.B!ml"

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

Yes, hadn't had any issues prior to latest update.

**Additional context**

**Comment by MysticalOS** [comment]
Safe to ignore it. seems to happen once per year, every year.
https://github.com/DeadlyBossMods/DeadlyBossMods/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+defender
