### ISSUE TITLE
"Major Patch" auto-disable functionality is user-unfriendly

### ISSUE THREAD

**Issue by Vecht** [DeadlyBossMods/DeadlyBossMods#104]
Your automatic disabling feature and "forced updates" is user-unfriendly garbage, plain and simple. It does not matter how you choose to justify this to yourselves. Your design sucks, and rather than fixing the issue at its core you instead dump your negative externalities onto your users and call it a day.

I would like to request that you fix this so that players without the most updated "major patch" addon can still see timers without having their addons disabled entirely.

**Comment by Vloz** [comment]
@MysticalOS pls reconsider this. 🙏
