### ISSUE TITLE
Nerub-ar Palace Support

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DeadlyBossMods#1047]
- Ulgrax the Devourer
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from all difficulties on live
- The Bloodbound Horror
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from all difficulties on live
- Sikran, Captain of the Sureki
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from all difficulties on live
- Rasha'nan
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from all difficulties on live
- Broodtwister Ovi'nax
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from all difficulties on live
- Nexus-Princess Ky'veza
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from all difficulties on live
- The Silken Court
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from all difficulties on live
- Queen Ansurek
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post availability 
  - [x] Mod finished with real data from all difficulties on live

**Comment by ylt** [comment]
Not 100% sure how to best raise this so throwing in here. 

The taunt swaps on Queen Ansurek aren't right and if followed result in the off tank receiving far more damage than necessary (and making a mess). 

Grabbed the relevant events from logs (heroic), added notes of what DBM currently does, and what I think the desired behavior should be:

| Time       | Event                                                       | Current Behavior                        | Desired Behavior                              |
|------------|-------------------------------------------------------------|-----------------------------------------|-----------------------------------------------|
| 00:08.322  | Queen Ansurek begins casting Liquefy                        |                                         | Taunt boss (Shaype)                          |
| 00:09.862  | Queen Ansurek casts Liquefy on Unkillbar                    |                                         |                                     |
| 00:09.863  | Unkillbar is afflicted by Liquefy from Queen Ansurek        | Taunt boss (Shaype)                     |  Move boss                                             |
| 00:09.864  | Queen Ansurek Acid Explosion Ispase 1562416                 |                                         |                                               |
| 00:11.326  | Queen Ansurek begins casting Feast                          |                                         | Defensive (Shaype)                   |
| 00:12.315  | Queen Ansurek casts Feast on Shaype                         |                                         |                                               |
| 00:12.352  | Shaype is afflicted by Feast from Queen Ansurek  | Taunt boss (Unkillbar)      |                                               |
| 00:18.596  | Queen Ansurek's Feast fades from Shaype |                          |                                               |
| 00:39.847  | Queen Ansurek's Liquefy fades from Unkillbar                |                                         |                                               |

Several problems with what's currently happening:
 * Liquefy is still on first tank (Unkillbar) for another 25 seconds, so as they taunt it back they're now taking on the bosses +500% damage melee hits.
 * Second tank has already started moving the boss so this results in a bit of a mess as it's yanked back again (feast taunt).
 * If taunted upon liquefy cast, there's no time to build threat before moving out of the acid so there's a risk of losing threat. If taunted on channel start you get 1.5 seconds to build up threat before you begin moving.

**Comment by MysticalOS** [comment]
the alpha already changed swap behavior to only taunt on liquify, feast is fully disabled. there will be no swaps on feast anymore. I thought that change made it into last release but I guess not
