### ISSUE TITLE
Suggestion for DBM Classic

### ISSUE THREAD

**Issue by dreamscape89** [DeadlyBossMods/DeadlyBossMods#105]
Since everyone would have DBM installed, can you make something for DBM to communicate between clients and tell us who is not looting the Core Hounds and Ancient Core Hounds so they can be skinned? Like some sort of announcement? This would be godlike. Please.

**Comment by MysticalOS** [comment]
not really in DBM's scope, seems more of a CTRaid type deal. Plus as is, classic development is at a minimum now and pretty soon going to be heavily swampted on retail.
