### ISSUE TITLE
Normal Vault of the Incarnates timer corrections

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DeadlyBossMods#1052]
**Do you have an error log of what happened?**
https://www.warcraftlogs.com/reports/N42wBaZ3h9vryzAD
[Transcriptor VOTI.txt](https://github.com/DeadlyBossMods/DeadlyBossMods/files/15088456/Transcriptor.VOTI.txt)

**Screenshots**
![normal (1)](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/134947146/6af89a4a-7b74-4aa3-850b-c4af53ee2e5b)
![normal (2)](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/134947146/bce01cab-f6ec-49ab-b0ef-bf9edf2b0bdb)
![normal (3)](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/134947146/46e77eb1-0bee-4ea3-abeb-cbf0402514b1)
![normal (4)](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/134947146/7455ba04-fe87-47e4-b990-e4c348f6f27c)
![normal (5)](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/134947146/5f47a1bb-f1cf-4785-8ceb-6a3ede4ec15f)
![normal (6)](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/134947146/d583e5f9-31cf-4b6b-b2a1-d24c318fb030)

**Which version of DeadlyBossMods are you using?**
10.2.36

**Comment by MysticalOS** [comment]
Fixed in https://github.com/DeadlyBossMods/DeadlyBossMods/commit/a4f3814e1072d740a7ab77180a56b0d9067dfc03
