### ISSUE TITLE
Pull timers are semi-broken in 10.2.7

### ISSUE THREAD

**Issue by brittyazel** [DeadlyBossMods/DeadlyBossMods#1075]
In tonight's raid, any time the raid lead would cast `/pull 10`, instead of the nice gold numbers that used to show in the screen we instead only got raid warnings indicating the countdown. I'm not sure what changed, and the built in `/countdown 10` still works, but `/pull` has appeared to revert to how it was 10+ years ago.

DBM 10.2.39

**Comment by MysticalOS** [comment]
working fine on 10.2.7, are you on EU and still on 10.2.6? the gold numbers are very much present. in fact more present than before

**Comment by brittyazel** [comment]
I am on US, and it's possible they're not on the latest version. I was not the raid lead, I was just relaying what we saw during the raid. They verbally 'said' they were updated, but maybe they're mistaken. I can test more after the raid is over

**Comment by MysticalOS** [comment]
yeah ERT won't send proper countdown for DBM or BW now that we're using blizzard functionality. that needs updating to use DoCountdown() api

**Comment by deNoor** [comment]
MRT / ERT already has Blizzard countdown option. Pull sender needs to enable in main addon window - tab "Timers" - flag "Enable timers from default interface".
or
`/run VMRT.Timers.BlizzTimer = true` in chat and reload ui

**Comment by MysticalOS** [comment]
This is good to know actually, just gotta convince them to make that the default in a new update
