### ISSUE TITLE
Nymue (heroic) Soak error

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DeadlyBossMods#1076]
**Describe the bug**
Soak timer error on heroic Nymue. Not sure if fixable.

**Do you have an error log of what happened?**
[nymue.zip](https://github.com/DeadlyBossMods/DeadlyBossMods/files/15244018/nymue.zip)

**Screenshots**
![WoWScrnShot_050824_112821](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/134947146/580b8684-dd91-4645-982c-e2b9016cd4d2)

**Which version of DeadlyBossMods are you using?**
DBM Core 10.2.39

**Comment by MysticalOS** [comment]
This is a case of "won't fix". it can be anywhere from 5-9 sec, it's using 7 cause that's the average, it's just gonna report 1-2sec fast sometimes, but most of time it won't.
