### ISSUE TITLE
Range checker disabled in classic

### ISSUE THREAD

**Issue by rainecheck** [DeadlyBossMods/DeadlyBossMods#1077]
**Describe the bug**
`/range` is disabled in Classic Cata. It's been disabled for retail, but was re-enabled for Classic as the API is still active there. In the move to Cata pre-patch, DBM is still returning the retail "<DBM> Range frame can not be used due to Blizzard disabling that functionality in this area."

**To Reproduce**
1. Enter a Wrath dungeon or raid
2. Type `/range`

**Screenshots**
![image](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/33798530/8f2cae9f-d0f7-4df9-b936-5dbd2d68bd62)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?**
`10.2.39 / 241 (2024/05/08 01:34:55) `

**Was it working in a previous version? If yes, which was the last good one?**
It was working before pre-patch.

**Comment by MysticalOS** [comment]
it's disabled in cata pre patch too, this is intended. there is no range check in classic anymore during combat. technically it's still possible to allow it out of combat and code maybe updated to reflect this so raid can still use it to pre position BEFORE a pull but once combat starts it is hard disabled.

**Comment by rainecheck** [comment]
Damn, ok. My bad. Appreciate the response.
