### ISSUE TITLE
[Classic] Sync error on Ragnaros (alpha)

### ISSUE THREAD

**Issue by Road-block** [DeadlyBossMods/DeadlyBossMods#108]
**Twitch client installed classic/retail version on retail/classic**
Classic alpha version on Classic installed through Twitch (and verified before submitting the bug by looking at the actual files)

**Describe the bug**

**Do you have an error log of what happened?**
```
1x DBM-MC\Ragnaros.lua:138: attempt to call method 'GetRemaining' (a nil value)
DBM-MC\Ragnaros.lua:138: in function 'OnSync'
DBM-Core\DBM-Core-1.13.28-4-g7027e6d.lua:11140: in function 'ReceiveSync'
DBM-Core\DBM-Core-1.13.28-4-g7027e6d.lua:11116: in function 'SendSync'
DBM-MC\Ragnaros.lua:84: in function 'handler'
DBM-Core\DBM-Core-1.13.28-4-g7027e6d.lua:828: in function <DBM-Core\DBM-Core.lua:815>
(tail call): ?
DBM-Core\DBM-Core-1.13.28-4-g7027e6d.lua:828: in function <DBM-Core\DBM-Core.lua:815>
```

**To Reproduce**
1. Go to Molten Core
2. Fight Ragnaros
3. See error

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**
1.13.28-4-g7027e6d-classic

**Was it working in a previous version? If yes, which was the last good one?**
I update alphas pretty frequently so no idea when this might have happened, probably the sync changes?

**Additional context**

**Comment by MysticalOS** [comment]
Pushed a possible fix to this, but unable to test it.
