### ISSUE TITLE
Lua Error in Azure Vaults: Script ran too long PlaySoundFile()

### ISSUE THREAD

**Issue by brittyazel** [DeadlyBossMods/DeadlyBossMods#1083]
**Describe the bug**
Error happened during a Mythic+ Azure Vaults during the Leymor fight.

WoW 10.2.7
DBM 10.2.39

**Do you have an error log of what happened?**
```
1x DBM-Core/DBM-Core.lua:6304: script ran too long
[string "@DBM-Core/DBM-Core.lua"]:6304: in function `PlaySoundFile'
[string "@DBM-Core/modules/objects/SpecialWarning.lua"]:608: in function `Play'
[string "@DBM-Party-Dragonflight/TheAzurevault/Leymor.lua"]:121: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:995: in function <DBM-Core/DBM-Core.lua:982>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:995: in function <DBM-Core/DBM-Core.lua:982>

Locals:
Skipped (In Encounter)
```

**Comment by MysticalOS** [comment]
happens when it takes longer than 200ms to read file from your disk. so either your disk is too slow or your system resources are and causing system to lag.

Blizzards code on this matter is crap and despite our feedback they think making a function fail instead of finish is even better logic (which usually results in further performance degradation)

**Comment by brittyazel** [comment]
Hrm, well I definitely don't think it's my PC or SSD that's too slow. This is the first time in a while that I've seen this error pop up, just thought it was worth reporting.

**Comment by MysticalOS** [comment]
it doesn't not that PC is slow overall, but was slow in that moment. maybe windows update fired up. maybe antivirus was scanning files. SOMETHING caused performance degradation in that moment, that caused seek time for the file to exceed permit-able time limit (like 200-250ms) of the PlaySoundFile api and thus 'script took too long' abort code blizzard has (which is annoyingly coded)
