### ISSUE TITLE
Bug in Cata Heroic Dungeon Grim Batol First Boss

### ISSUE THREAD

**Issue by crossfactioninstancedpvp** [DeadlyBossMods/DeadlyBossMods#1101]
The bug occurred while fighting General Umbriss in Grim Batol when the adds spawned.

![image](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/170687628/f22fffe0-d4ec-4195-9865-99d2ffece737)

**Comment by MysticalOS** [comment]
ah forgot to push new release. it is fixed in alpha. will do update soon™
