### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Carnage2024** [DeadlyBossMods/DeadlyBossMods#1105]
**Describe the bug**

When I join a party of 5, with a healer and 3 DPS, this Lua Error appears

**Do you have an error log of what happened?**
Message: Interface/AddOns/DBM-Core/DBM-Core.lua:7188: attempt to index field '?' (a nil value)
Time: Mon May 27 14:41:54 2024
Count: 1
Stack: Interface/AddOns/DBM-Core/DBM-Core.lua:7188: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:7188: in function `func'
[string "@Interface/AddOns/DBM-Core/modules/Scheduler.lua"]:175: in function <Interface/AddOns/DBM-Core/modules/Scheduler.lua:166>

Locals: self = false
ignoreLoot = <table> {
 MoveSpecialWarning = <function> defined @Interface/AddOns/DBM-Core/modules/objects/SpecialWarning.lua:132
 CopyAllModOption = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:3262
 PLAY_MOVIE = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:7301
 SortByTankAlpha = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:7567
 CopyProfile = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2010
 GetNumRealGroupMembers = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2833
 CHAT_MSG_WHISPER = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6971
 GetCachedBossHealth = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:7956
 DungeonMusic = <table> {
 }
 FireEvent = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:1918
 CreateModLocalization = <function> defined @Interface/AddOns/DBM-Core/modules/objects/Localization.lua:104
 GetMyPlayerInfo = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2739
 ADDON_LOADED = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:1524
 CANCEL_PLAYER_COUNTDOWN = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:4982
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2539
 AddDefeatSound = <function> defined @Interface/AddOns/DBM-Core/modules/Sounds.lua:123
 GetDefeatSounds = <function> defined @Interface/AddOns/DBM-Core/modules/Sounds.lua:116
 GroupInCombat = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:8677
 UPDATE_MOUSEOVER_UNIT = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:4070
 GetSpellCooldown = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6521
 UPDATE_BATTLEFIELD_STATUS = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:3632
 UnitAura = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6548
 IsRanged = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:7509
 LFG_PROPOSAL_SHOW = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:3541
 ReleaseRevision = 20240527000000
 RegisterShortTermEvents = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:1288
 LOADING_SCREEN_DISABLED = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:3853
 GetUnitFullName = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:2744
 IsClassic = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:7350
 UNIT_HEALTH_FREQUENT = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:5794
 UNIT_DIED = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6665
 IsTanking = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:7736
 FindInstanceIDs = <function> defined @Interface/AddOns/DBM-Core/modules/DevTools.lua:91
 CHALLENGE_MODE_RESET = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:3901
 UnitDebuff = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6589
 LFG_ROLE_CHECK_SHOW = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:3532
 Disable = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:7039
 ReceiveTimerInfo = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6743
 Arrow = <table> {
 }
 RangeCheck = <table> {
 }
 ValidateSound = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:6336
 IsHealer = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:7701
 AddBattleMusic = <function> defined @Interface/AddOns/DBM-Core/modules/Sounds.lua:218
 LoadModByName = <function> defined @Interface/AddOns/DBM-Core/DBM-Core.lua:4041
 Debug = <fun

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, the UI I use is Dominos and is up to date
**Which version of DeadlyBossMods are you using?**
DBM-Core-10.2.43-4-g0d2c510.zip
**Was it working in a previous version? If yes, which was the last good one?**
Not sure what last version I had, but Lua Error is new and attempted to fix by updating to this Version
**Additional context**

**Comment by MysticalOS** [comment]
What level are you?

**Comment by billveld** [comment]
I'm getting this error as well on Cata classic lvl 85 on latest version.  Rolling back to 5-21 release of DBM Core seems to fix it

**Comment by MysticalOS** [comment]
are you unspecced? it's basically saying it can't find your spec

**Comment by MysticalOS** [comment]
I pushed another update with very aggressive missing spec recovery, and then if it still can't find spec, it just gives up and treats you as a dps (catas default behavior anyways, dps unless specifically flagged as tank or healer so really basically DBM does nothing if it can't determine if you're a healer or tank)

Try new update and see

**Comment by billveld** [comment]
No, I was on a blood spec DK
