### ISSUE TITLE
Classic Cata - DBM-Core.lua:7426 Error

### ISSUE THREAD

**Issue by evilgodly** [DeadlyBossMods/DeadlyBossMods#1108]
**Describe the bug**
Got this when i logged in and was in Deepholm.

**Do you have an error log of what happened?**
10x DBM-Core/DBM-Core.lua:7426: attempt to index field '?' (a nil value)
[string "@DBM-Core/DBM-Core.lua"]:7426: in function `GetRoleFlagValue'
[string "@DBM-Core/DBM-Core.lua"]:7990: in function `AddBoolOption'
[string "@DBM-Core/modules/objects/Announce.lua"]:636: in function <DBM-Core/modules/objects/Announce.lua:582>
[string "=(tail call)"]: ?
[string "@DBM-Party-Cataclysm/BlackrockCaverns/RomoggBonecrusher.lua"]:18: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@DBM-Core/DBM-Core.lua"]:3998: in function `LoadMod'
[string "@DBM-Core/DBM-Core.lua"]:3941: in function `LoadModsOnDemand'
[string "@DBM-Core/DBM-Core.lua"]:3841: in function `func'
[string "@DBM-Core/modules/Scheduler.lua"]:175: in function <DBM-Core/modules/Scheduler.lua:166>

Locals:
self = <table> {
 NoSortAnnounce = false
 timers = <table> {
 }
 categorySort = <table> {
 }
 instanceId = 66
 inCombatOnlyEvents = <table> {
 }
 modelId = 33147
 SyncThreshold = 8
 numBoss = 1
 combatInfo = <table> {
 }
 encounterId = 1040
 creatureId = 39665
 modId = "DBM-Party-Cataclysm"
 groupSpells = <table> {
 }
 statTypes = "normal,heroic,timewalker"
 isTrashMod = false
 specwarns = <table> {
 }
 zones = <table> {
 }
 revision = 20210922153837
 Options = <table> {
 }
 DefaultOptions = <table> {
 }
 id = "105"
 inCombat = false
 addon = <table> {
 }
 iconRestore = <table> {
 }
 isDummyMod = false
 groupOptions = <table> {
 }
 optionCategories = <table> {
 }
 yells = <table> {
 }
 localization = <table> {
 }
 announces = <table> {
 }
 vb = <table> {
 }
 subTab = 1
}
flag = "Tank|Healer"
flags = <table> {
 1 = "Tank"
 2 = "Healer"
}
(for index) = 1
(for limit) = 2
(for step) = 1
i = 1
flagText = "Tank"
(*temporary) = nil
(*temporary) = 399
(*temporary) = "^-"
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
currentSpecID = 399
DBM = <table> {
 MoveSpecialWarning = <function> defined @DBM-Core/modules/objects/SpecialWarning.lua:132
 CopyAllModOption = <function> defined @DBM-Core/DBM-Core.lua:3262
 PLAY_MOVIE = <function> defined @DBM-Core/DBM-Core.lua:7312
 SortByTankAlpha = <function> defined @DBM-Core/DBM-Core.lua:7578
 CopyProfile = <function> defined @DBM-Core/DBM-Core.lua:2010
 GetNumRealGroupMembers = <function> defined @DBM-Core/DBM-Core.lua:2833
 CHAT_MSG_WHISPER = <function> defined @DBM-Core/DBM-Core.lua:6974
 GetCachedBossHealth = <function> defined @DBM-Core/DBM-Core.lua:7967
 DungeonMusic = <table> {
 }
 FireEvent = <function> defined @DBM-Core/DBM-Core.lua:1918
 CreateModLocalization = <function> defined @DBM-Core/modules/objects/Localization.lua:104
 GetMyPlayerInfo = <function> defined @DBM-Core/DBM-Core.lua:2739
 ADDON_LOADED = <function> defined @DBM-Core/DBM-Core.lua:1524
 CANCEL_PLAYER_COUNTDOWN = <function> defined @DBM-Core/DBM-Core.lua:4982
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @DBM-Core/DBM-Core.lua:2539
 AddDefeatSound = <function> defined @DBM-Core/modules/Sounds.lua:123
 GetDefeatSounds = <function> defined @DBM-Core/modules/Sounds.lua:116
 GroupInCombat = <function> defined @DBM-Core/DBM-Core.lua:8688
 UPDATE_MOUSEOVER_UNIT = <function> defined @DBM-Core/DBM-Core.lua:4070
 GetSpellCooldown = <function> defined @DBM-Core/DBM-Core.lua:6524
 UPDATE_BATTLEFIELD_STATUS = <function> defined @DBM-Core/DBM-Core.lua:3632
 UnitAura = <function> defined @DBM-Core/DBM-Core.lua:6551
 IsRanged = <function> defined @DBM-Core/DBM-Core.lua:7520
 LFG_PROPOSAL_SHOW = <function> defined @DBM-Core/DBM-Core.lua:3541
 ReleaseRevision = 20240527000000
 RegisterShortTermEvents = <function> defined @DBM-Core/DBM-Core.lua:1288
 LOADING_SCREEN_DISABLED = <function> defined @DBM-Core/DBM-Core.lua:3853
 GetUnitFullName = <function> defined @DBM-Core/DBM-Core.lua:2744
 IsClassic = <function> defined @DBM-Core/DBM-Core.lua:7361
 UNIT_HEALTH_FREQUENT = <function> defined @DBM-Core/DBM-Core.lua:5794
 UNIT_DIED = <function> defined @DBM-Core/DBM-Core.lua:6668
 IsTanking = <function> defined @DBM-Core/DBM-Core.lua:7747
 FindInstanceIDs = <function> defined @DBM-Core/modules/DevTools.lua:91
 CHALLENGE_MODE_RESET = <function> defined @DBM-Core/DBM-Core.lua:3901
 UnitDebuff = <function> defined @DBM-Core/DBM-Core.lua:6592
 LFG_ROLE_CHECK_SHOW = <function> defined @DBM-Core/DBM-Core.lua:3532
 Disable = <function> defined 

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?** DBM Core 10.2.44

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
I genuinely have no idea. it's gotta be a bug with blizzard api at this point where it just doesn't return your spec no matter how many times it's checked. I can't fix this. I can't even reproduce the error on my end so only some users have specs that can't be read.

**Comment by evilgodly** [comment]
i will try uninstalling and reinstalling DBM along with the saved variables to see what is going on.

I am getting this on my 85 Frost DK.

**Comment by MysticalOS** [comment]
I think you're second person who said they were on a DK, can you do me a favor and do following in game

`/dump GetPrimaryTalentTree()`
(see what number this returns)
then do this
`/dump GetTalentTabInfo(theNumberFirstThingReturned)`

**Comment by evilgodly** [comment]
i just deleted all of Classic Cata & Retail versions of Saved Variables & Addons and jsut reinstaleld them. will see what happens when i login. If still same error, will run the 2 scripts

**Comment by evilgodly** [comment]
OK so here is what i found. After removing the saved variables & uninstalling & reinstalling all the DBM Add-ons for Cata. I brought up wow and turned off everything but the DBM Core Main Core and no errors at all. Then turned everything on but the Cata specific ones and still no errors. 

After turning the Cata specific add-ons on i figured out that when DBM Mod Dungeon Cata is turned on i get the error. I am testing each of the Cata zones to see if it is only Deepholm or others.

**Comment by evilgodly** [comment]
> I think you're second person who said they were on a DK, can you do me a favor and do following in game
> 
> `/dump GetPrimaryTalentTree()` (see what number this returns) then do this `/dump GetTalentTabInfo(theNumberFirstThingReturned)`

First Dump [1]=2

2nd dump got error
2x [string "return GetTalentTabInfo(theNumberFirstThing..."]:1: Usage: GetTalentTabInfo(tabIndex[, isInspect[, isPet[, groupIndex]]])
[string "=[C]"]: in function `GetTalentTabInfo'
[string "return GetTalentTabInfo(theNumberFirstThingReturned)"]:1: in function `func'
[string "@Blizzard_SharedXML/Dump.lua"]:396: in function `DevTools_DumpCommand'
[string "@Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:2493: in function `?'
[string "@Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:5001: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:4664: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:4700: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:120_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:120_OnEnterPressed"]:1>

Locals:
(*temporary) = nil

**Comment by MysticalOS** [comment]
the second part of instructions you missed part of replacing theNumberFirstThing with 2

**Comment by evilgodly** [comment]
hehe......................... im a dumb ass
![image](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/109829810/ed62bdc8-e7cf-406f-89fc-1a942f0f0477)

**Comment by MysticalOS** [comment]
I see the problem, and it took not one but two DK reports to put it together it was a DK only issue.

the numbers for DKs and ONLY DKs were incorrectly mapped, fixing and getting a new release out asap. thanks for debugging for me

**Comment by evilgodly** [comment]
no issues in  Dalaran, Mount Hyjal, Stormwind, Twilight Highlands, Uldum, and Vashj'ir. BUt when i go to Deepholm i get the below screen shot and the error.

![image](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/109829810/c651bf67-c04e-4018-90b8-43aeda42d8c0)

**Comment by MysticalOS** [comment]
you'd get same error if you manually loaded any mod too. it's on mod load it can't read your spec, and I have a fix for DKs going out soon

**Comment by evilgodly** [comment]
ok thank you and glad i could help.
