### ISSUE TITLE
Don't output on trial accounts

### ISSUE THREAD

**Issue by p3lim** [DeadlyBossMods/DeadlyBossMods#1111]
**Describe the bug**

Trial accounts can't chat in raid channels, yet DBM attempts to:

![image](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/26496/bd7f5124-ac5f-47b2-8f73-4e909eee11ca)

**Which version of DeadlyBossMods are you using?**

10.2.46

**Comment by MysticalOS** [comment]
Good call, I'll fix this
