### ISSUE TITLE
Weird LFR Igira (Amirdrassil) error

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DeadlyBossMods#1136]
**Describe the bug**
Likely a false positive, probably can't replicate, but I got 3 error pings at once and I don't understand why.

**Do you have an error log of what happened?**
[LFR wing 1 DK.zip](https://github.com/user-attachments/files/16177459/LFR.wing.1.DK.zip)

**Screenshots**
![WoWScrnShot_071124_203637](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/134947146/bb14fdef-f5d6-4a7e-b44b-811ac0520486)
![WoWScrnShot_071124_203725](https://github.com/DeadlyBossMods/DeadlyBossMods/assets/134947146/952219bf-f25c-49f9-80cc-32a9d6e0b856)

**Which version of DeadlyBossMods are you using?**
DBM 10.2.53-1 alpha

**Comment by MysticalOS** [comment]
Don't know how or why, but boss stopped channeling torment for 1 second then started again., non broken, but i silenced error from happening anyways
