### ISSUE TITLE
jaina fight dazalor DBM CheckDispelFilter must provide dispel type

### ISSUE THREAD

**Issue by 4t0msk** [DeadlyBossMods/DeadlyBossMods#1154]
7x DBM-Core/modules/objects/BossMod.lua:673: DBM CheckDispelFilter must provide dispel type
[string "=[C]"]: in function `error'
[string "@DBM-Core/modules/objects/BossMod.lua"]:673: in function `CheckDispelFilter'
[string "@DBM-Raids-BfA/BattleofDazaralor/Jaina.lua"]:187: in function `func'
[string "@DBM-Core/modules/Scheduler.lua"]:163: in function <DBM-Core/modules/Scheduler.lua:153>

Locals:
Skipped (In Encounter)

**Comment by MysticalOS** [comment]
Weird, LuaLS should have caught this error, i'll fix it and also investigate why it wasn't found when i did a full scan

**Comment by MysticalOS** [comment]
and already found reason it slipped through luaLS, thanks for report
