### ISSUE TITLE
no sound countdown on pull timer

### ISSUE THREAD

**Issue by artazika** [DeadlyBossMods/DeadlyBossMods#1159]
There is no sound countdown before the fight starts in raids sent by other players (I'm not sure).
I tested myself /pull 10 and MRT pull button and sound countdown works in both cases. But I got no sound when I asked my friend to send /pull 10 (he uses DBM).

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
In raid - no, in my tests - yes

**Which version of DeadlyBossMods are you using?**
11.0.1

**Was it working in a previous version? If yes, which was the last good one?**
In versions before TWW prepatch, I'm not sure which one

**Comment by MysticalOS** [comment]
Sounds like a bug with way they are sending the pull timer. they are probably using an obsolete method of sending it that isn't sending a blizzard countdown. the old sync based pull counters are no longer supported by either DBM or bw and they actually just use blizzard countdown now (/countdown) if they are using something that sends old syncs, it will do nothing

**Comment by artazika** [comment]
so right now only the way to send pull timer with sound countdown is /countdown ?
and there's no way to change that now?
Only to ask everyone (both people and addons) to switch to the /countdown ?

**Comment by MysticalOS** [comment]
no, /pull also works, from DBM and BW, what i'm saying is whoever is sending pull is probably using a crappy mod like MRT that's not updated to send them properly. send them with DBM or BW, not MRT, or any other addon that's sending them an old incompatible way.

**Comment by artazika** [comment]
I retested. My personal counts are always with sound, no matter how sent.
Checked with a friend some more. We both had no addons only with DBM enabled (me) and DBM / BW / no addons at all (my friend). Sent via chat via /pull and /countdown. I never once heard the voice countdown when my friend sent with DBM, with BW or without addons.
My friend heard countdowns sent from me with BW enabled.

**Comment by MysticalOS** [comment]
the person sending them has assist right? if they don't it's not sent to group just to themself

**Comment by artazika** [comment]
The group leader was always the one who sent the timer

**Comment by MysticalOS** [comment]
leader automatically has assist. I cannot think of any reason for problems, unless leader is just purposely running an older version of DBM or Bigwigs

**Comment by artazika** [comment]
No, the latest versions of addons were used, both mine and hers.
There was no sound when the leader was without addons either.

**Comment by MysticalOS** [comment]
Found cause, i couldn't reproduce until sender was cross realm. that's what broke in prepatch and issuing fix shortly
