### ISSUE TITLE
Lua Error during Jaina Proudmoore mythic fight

### ISSUE THREAD

**Issue by anthrowill** [DeadlyBossMods/DeadlyBossMods#1182]
**Describe the bug**
During the first stage of the Jaina Proudmoore fight in the Battle of Dazar'alor raid, when her spells/abilities root my character, an Lua Error appears.

**Do you have an error log of what happened?**

Message: ...nterface/AddOns/DBM-Core/modules/objects/BossMod.lua:672: DBM CheckDispelFilter must provide dispel type
Time: Wed Aug 14 22:05:40 2024
Count: 1
Stack: ...nterface/AddOns/DBM-Core/modules/objects/BossMod.lua:672: DBM CheckDispelFilter must provide dispel type
[string "@Interface/AddOns/DBM-Core/modules/objects/BossMod.lua"]:672: in function `CheckDispelFilter'
[string "@Interface/AddOns/DBM-Raids-BfA/BattleofDazaralor/Jaina.lua"]:187: in function `func'
[string "@Interface/AddOns/DBM-Core/modules/Scheduler.lua"]:163: in function <Interface/AddOns/DBM-Core/modules/Scheduler.lua:153>

Locals: self = <table> {
 stats = <table> {
 }
 isTrashMod = false
 numBoss = 1
 ignoreBestkill = false
 modId = "DBM-Raids-BfA"
 engagedDiffText = "Mythic - "
 shortTermRegisterEvents = <table> {
 }
 engagedDiffModifier = 0
 revision = 20240629024602
 yells = <table> {
 }
 DefaultOptions = <table> {
 }
 iconRestore = <table> {
 }
 engagedDiffIndex = 16
 isDummyMod = false
 encounterId = 2281
 engagedDiff = "mythic"
 registeredUnitEvents = <table> {
 }
 localization = <table> {
 }
 announces = <table> {
 }
 inCombatOnlyEventsRegistered = 1
 subTab = 4
 timers = <table> {
 }
 specwarns = <table> {
 }
 instanceId = 1176
 modelId = 87892
 id = "2343"
 groupSpells = <table> {
 }
 dropdowns = <table> {
 }
 zones = <table> {
 }
 combatInfo = <table> {
 }
 Options = <table> {
 }
 addon = <table> {
 }
 optionCategories = <table> {
 }
 categorySort = <table> {
 }
 SyncThreshold = 8
 hotfixNoticeRev = 18363
 groupOptions = <table> {
 }
 creatureId = 146409
 usedIcons = <table> {
 }
 inCombat = true
 vb = <table> {
 }
 inCombatOnlyEvents = <table> {
 }
}
dispelType = nil
DBM = <table> {
 DungeonMusic = <table> {
 }
 ReleaseRevision = 20240728000000
 Arrow = <table> {
 }
 RangeCheck = <table> {
 }
 Test = <table> {
 }
 Voices = <table> {
 }
 BattleMusic = <table> {
 }
 InfoFrame = <table> {
 }
 Flash = <table> {
 }
 ModLists = <table> {
 }
 Music = <table> {
 }
 classicSubVersion = 0
 Mods = <table> {
 }
 lastAntiSpamEE = 70090.214000
 lastAntiSpamFLASH = 70508.384000
 registeredUnitEvents = <table> {
 }
 VoiceVersions = <table> {
 }
 AddOns = <table> {
 }
 Options = <table> {
 }
 Revision = 20240728191115
 Defeat = <table> {
 }
 Victory = <table> {
 }
 DefaultOptions = <table> {
 }
 Counts = <table> {
 }
 Nameplate = <table> {
 }
 HudMap = <table> {
 }
 DisplayVersion = "11.0.2"
 HighestRelease = 20240728000000
}
lastCheck = 0
lastReturn = true
typeCheck = <table> {
 disease = <table> {
 }
 bleed = <table> {
 }
 curse = <table> {
 }
 magic = <table> {
 }
 poison = <table> {
 }
}

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

No.

**Which version of DeadlyBossMods are you using?**

the one released on 7/28/2024 for patch 11.0.2

**Was it working in a previous version? If yes, which was the last good one?**

Unsure, I did not try farming this encounter until last week, and the error appeared last time but I closed it during the fight.

**Comment by MysticalOS** [comment]
This was fixed a LONG time ago, you need to update your battle for azeroth raid mods

**Comment by MysticalOS** [comment]
Oh crap i never tagged the fix, that's why, sorry about that, tagging now
