### ISSUE TITLE
Unused/outdated localizations in DBM-GUI

### ISSUE THREAD

**Issue by emmericp** [DeadlyBossMods/DeadlyBossMods#1191]
If you change the definition of DBM_GUI_L in GUI/localization.en.lua as follows:

```
---@class DBMGUILocalization
local L = {}

DBM_GUI_L = L
```

You get 69 warnings about languages defining localizations that are not present in localization.en.lua

**Comment by MysticalOS** [comment]
I'll leave that be for now, no time for non breaking errors with expansion launch.
