### ISSUE TITLE
Annoying fanfare sound is played whenever i land skyflying

### ISSUE THREAD

**Issue by pugzzyy** [DeadlyBossMods/DeadlyBossMods#1215]
**Describe the bug**
<When i land from skyflying, a fanfare/horn noise is played. This only started on 3rd September 2024. I have not changed any settings etc

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?** 11.0.5
**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by pugzzyy** [comment]
I have closed all add ons to isolate the issue and it is DBM causing the sound effect. I cant see in options where this might be to turn it off.

**Comment by MysticalOS** [comment]
DBM has made no change here. it definitely doesn't play any sound for skyriding. You must have missed a weak aura or some other addon that added this, or maybe it's a default blizzard sound hard to say. if you make a video or something of it we can maybe help identify it. But there is no setting for such a sound in DBM because there is no such sound in DBM

**Comment by pugzzyy** [comment]
Hi

Thanks for the quick reply. 

It was odd - i disabled all addons, and i had no sound played when landing. Turn DBM only back on and it started again. 

I have since deleted some of the older DBM packs, and it seemed to have resolved my issue. 

Thanks again though.

**Comment by MysticalOS** [comment]
that's true, it could have been a 3rd party pack we are unaware of. it's certainly not a feature built into first party modules.

**Comment by MysticalOS** [comment]
can you tell us what 3rd party packs you removed? it'd be nice to know the offender
