### ISSUE TITLE
Tooltip hidden

### ISSUE THREAD

**Issue by Totoroe** [DeadlyBossMods/DeadlyBossMods#1217]
I logged in today and tried to check some items in my bag but the tooltip feature wasn't working. I updated all addons, including DBM but the issue continued. Turned off all addons and first tried turning DBM back on to find that it was the source of the tooltip not working.

From what I can work out the issue is within the DBM Mod "World Events" as everything else I've been using does not recreate the issue.

**Comment by MysticalOS** [comment]
I just checked in game, with world events, my tooltips work just fine. It's more likely whatever broke your tooltips sorted itself out via the multiple reloads you did during testing?
not only do I run DBM but i have every DBM module there is (first party) and have no issues.

**Comment by Totoroe** [comment]
Ok it isn't an issue in open world, I was in the "Awakening the Machine" scenario (the weekly in Ringing Deeps) when I first noticed it and this is where I worked it out. When back outside it was fine but I've gone back into the scenario it's happened again. I don't recall this being something I've noticed happening before.

Do you think it might be a setting that could be set up specific to scenarios?

**Comment by MysticalOS** [comment]
![Screenshot 2024-09-03 at 4 50 23 PM](https://github.com/user-attachments/assets/46f5a27c-7873-4d79-acb7-2ca2da2afdca)

**Comment by MysticalOS** [comment]
See if that's enabled. that exists to hide annoying 30 line tooltips during boss fights if entire raid has quest to kill x boss or whatever.

scenario is considered a boss fight.

**Comment by Totoroe** [comment]
Ahhh! Thanks so much for clarifying, my work fried brain didn't even think it would be linked to the scenario counting.

**Comment by Totoroe** [comment]
Ahhh! Thanks so much for clarifying, my work fried brain didn't even think it would be linked to the scenario counting.

**Comment by Totoroe** [comment]
Ahhh! Thanks so much for clarifying, my work fried brain didn't even think it would be linked to the scenario counting.
