### ISSUE TITLE
Experimental Dosage on Broodwister Ovi'nax

### ISSUE THREAD

**Issue by Athliara** [DeadlyBossMods/DeadlyBossMods#1245]
Was expecting markers to be assigned to people with Experimental Dosage as set in the option which doesn't currently work.

**Comment by MysticalOS** [comment]
has the RAID LEADER set them, the raid leaders setting overrides all the rest.

raid leader must have latest DBM and have option set to desired outcome

**Comment by MysticalOS** [comment]
Found a bug causing raid leader override not to work, so i'll be doing a new tag shortly to fix it
