### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Addonman** [DeadlyBossMods/DeadlyBossMods#1247]
Just loged in game and this popped out.

Message: Interface/AddOns/DBM-Core/modules/Sounds.lua line 147:
   attempt to index field 'Options' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/DBM-Core/modules/Sounds.lua"]:147: in main chunk

**Comment by MysticalOS** [comment]
thanks for report, looking into it now

**Comment by MysticalOS** [comment]
Doing a new tag to fix this. was something last minute I put in i should have tested more. it seemed pretty straight forward but had unforeseen load order issues
