### ISSUE TITLE
Nerub-ar Palace - The Silken Court - Tank Swap

### ISSUE THREAD

**Issue by janeczkoc1** [DeadlyBossMods/DeadlyBossMods#1248]
There is no indicator for a Taunt Swap on Anub'arash after piercing strike is applied to a tank.

DBM should alert the off tank to taunt Anub'arash after piercing strike is applied to the active tank.

**Comment by MysticalOS** [comment]
it shows the stacks but yeah doesn't alert taunt cause I wasn't sure how to fully balance it yet. swap both bosses or just the one and let caster cast on who he's gonna cast on. I also found during charge you can reset stacks anyways so taunting isn't essential if you can survive two hits in a row. this something i'm gauging more feedback on

**Comment by Sfrjoshpro** [comment]
i was coming here just talk about this

**Comment by MysticalOS** [comment]
what do you feel is missing?

**Comment by Sfrjoshpro** [comment]
idk i was really hoping for a taunt boss audio or something. or even something that tell the player what boss to be on and have threat of. from what i learned from downing the boss yesterday was pretty much what ever boss you have at the current time you need to stay on them. bc the mage boss will move one side or the other charge.

hope that help

**Comment by silviodc** [comment]
I have been joining pugs on normal and heroic as tank.
What I saw was people ask to swap after 2 stacks. This can happen 2/3 times before the charge. It depends on DPS throughput.

Everyone stack both boss on P1 so it is easy to swap.
Sometimes the tank handling the caster get so focused on mitigate the spell damage (warrior for example) that forget to taunt.
If the other tank is ungeared he dies. If he is very emotional he will say you are forgetting to taunt

**Comment by MysticalOS** [comment]
I might add a two stack taunt warning, but this is one of those cases where you can actually easily reset stacks every charge as well. it just depends on groups strategy. But i think a 2 stack swap is safe

**Comment by MysticalOS** [comment]
https://github.com/DeadlyBossMods/DeadlyBossMods/commit/1765718111575981acb6c8ef78659674d56ad83a completes this request
