### ISSUE TITLE
When used with Masque Serenity, the circular glowing shape does not work.

### ISSUE THREAD

**Issue by EarthPlanet97** [DeadlyBossMods/DeadlyBossMods#1250]
**Describe the bug**
It works properly only up to DBM (Core) 11.0.5. With the add-on "Masque Serenity".

After installing various add-ons and repeating, it works properly up to DBM (Core) 11.0.5, but in later versions, the glow shape is displayed as a square, not a circle.

**Screenshots**
![image](https://github.com/user-attachments/assets/1d9baed2-7bea-4ab6-83f0-c3d3200fbde9)
Above is DBM(Core) 11.0.5 with the Masque Serenity

![image](https://github.com/user-attachments/assets/958ec098-d3d6-45e5-95fe-278ccc47c269)
Above is DBM(Core) 11.0.6~Latest version with the Masque Serenity

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, I tried enabling and running only DBM/Masque/WeakAura, but the result is the same.

**Which version of DeadlyBossMods are you using?**
11.0.13 (With Cataclysm)

**Was it working in a previous version? If yes, which was the last good one?**
11.0.5

**Additional context**
Please help me!!

**Comment by MysticalOS** [comment]
that doesn't look like one of our namepelate timers. that's another addon
more likely that's some kind of personal debuff timers addon.

**Comment by EarthPlanet97** [comment]
Yes, that's right.
But WA works fine when I install DBM 11.0.5.
If I install 11.0.6 or later again, it doesn't work properly.
So I'm using 11.0.5 now

**Comment by MysticalOS** [comment]
that makes no sense. also DBM 11.0.5 and 11.0.6 both are very old. they will have serous problems in raid (and likely will be force disabled second you join a group. current I think is 11.0.13

**Comment by EarthPlanet97** [comment]
I just tried reinstalling 11.0.13 again, but
DBM 11.0.6~latest version affects WA's glow.
My foolish guess is that some setting in DBM is affecting it.

**Comment by EarthPlanet97** [comment]
Here are the tests I've done:
1. Disable all addons
2. Enable: WeakAura & Masque --> The glow effect is displayed normally as a circle
3. Enable: DBM Core (11.0.5) & WeakAura & Masque --> The glow effect is displayed normally as a circle (Addon: Masque Serenity)
4. DBM(Core) Update: 11.0.6 and WA & Masque enabled --> The glow effect is displayed as a square
5. DBM(Core) Update: 11.0.13 and WA & Masque enabled --> The glow effect is displayed as a square

Server : Cataclysm / KR

**Comment by MysticalOS** [comment]
All I know is we're using the lib the correct way, so someone else isn't. They're probably overwriting a custom version of lib that has round option and when DBM loads it loads an unmodified version of it maybe? Either way, I've basically escalated this to WA and libglow people since there is nothing wrong on DBMs end

**Comment by EarthPlanet97** [comment]
I understand. Thank you for your help.
