### ISSUE TITLE
Request: Allow toggling auto-reply for delves (or by each content type)

### ISSUE THREAD

**Issue by TheCheat54** [DeadlyBossMods/DeadlyBossMods#1253]
There's no bug related to this, but I find that the auto-response feature feels very spammy in the context of delves due to how often players are entering and leaving them. They are short-form content compared to just about everything else, so it would be nice if we could toggle auto-reply per content type or at least for delves. I still like having it on for dungeons and raid boss pulls.

Delves also aren't timed, so I am far more likely to be able to stop and engage a conversation than I would be in a key run or boss pull.

**Comment by MysticalOS** [comment]
that's a valid concern, i can probably add a disable specifically for delves. the engage and end stats are mostly for the player. i'll heave the auto reply enabled for zekvir only.

**Comment by TheCheat54** [comment]
That's perfect. I almost forgot about Zekvir given the state of his pinnacle difficulty but his is quite the unique case.
