### ISSUE TITLE
New Fork Called DBM Classic

### ISSUE THREAD

**Issue by jmaslows** [DeadlyBossMods/DeadlyBossMods#127]
I think it would be amazing if you created DBM Classic so that the Twitch Client would stop breaking your addon.  All it would be is the current version you have for Classic.

**Comment by MysticalOS** [comment]
I won't be doing this. migration would be just as much of a mess. one project for multiple game version is intended way. twitch client I haven't seen mess up in months. I know others see it more often but I can't explain why that happens. it happens only to a few users. the mass user situations haven't happened in ages. when it does happen though users need to send their twitch client logs to twitch to analyze why. i bet problem is they can't reproduce it and almost no one is reporting it to them or sending them logs.

**Comment by b-morgan** [comment]
If there was a useable replacement for the Twitch Client I would delete it in a heartbeat.

@MysticalOS, I would gladly report the issue to Twitch but even with your comments above, I still can't figure out how to do so. If you can elaborate on the details, I'd be grateful.

Judging from my previous interactions with Twitch support, they will most likely either ignore me or blame the problem on you anyway,
