### ISSUE TITLE
Sikran - Taunt Alert

### ISSUE THREAD

**Issue by janeczkoc1** [DeadlyBossMods/DeadlyBossMods#1271]
The Alert to Taunt Swap triggers too early. 

The Alert should trigger after "Phase Lunge", not before "Phase Lunge".

**Comment by MysticalOS** [comment]
it triggers after 2nd expose, and that's not too early. that's the standard for all taunt swaps on this fight. having tanked it myself. one tank takes both first attacks, then other tank taunts and takes 3rd.
