### ISSUE TITLE
No Warnings going off Since recent update. Not even seeing bars.

### ISSUE THREAD

**Issue by Mallust1** [DeadlyBossMods/DeadlyBossMods#1274]
**Describe the bug**
Nothing no bars no sound in Grim Batol havent tried other dungeons yet.

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
not a bug here. Likely dungeons mods not installed, or not fully enabled.
