### ISSUE TITLE
Taunt call out of Shad'har the Insatiable seem to be inaccurate

### ISSUE THREAD

**Issue by tharakadesilva** [DeadlyBossMods/DeadlyBossMods#128]
**Is your feature request related to a problem? Please describe.**
The boss does a tank damage combo of Crush and Dissolve. It will be either 2 Crush and 1 Dissolve or it will be either 2 Dissolve and 1 Crush. These can alternate [Crush > Dissolve > Crush] or [Dissolve > Crush > Dissolve] or they can happen in a consecutive manner [Crush > Crush > Dissolve] or [Dissolve > Dissolve > Crush].

The tanks have to make sure that the Crushes are taken by one tank and the Dissolves are taken by the other. Right now, the taunt call out seems to be happening every time either a dissolve or a crush is cast by the boss.

**Describe the solution you'd like**
The taunt call out should happen in the following scenarios:
(1) The current tank has Crush and the boss is casting Dissolve
(2) The current tank has Dissolve and the boss is casting Crush

**Comment by tharakadesilva** [comment]
Seeing a similar commit, not sure if this was already fixed.

**Comment by MysticalOS** [comment]
it should be fixed in alpha like 2 days ago. try that.

**Comment by tharakadesilva** [comment]
Will check it out. Thanks @MysticalOS .

**Comment by MysticalOS** [comment]
I'd leave issue open for now until you can verify fix is ok. as it's not tested yet to be behaving as desired.

**Comment by tharakadesilva** [comment]
Okay, I downed the boss for the week. I'll try to verify if I have some time.

**Comment by MysticalOS** [comment]
Applied even more fixes tonight, i THINK it's nailed down now but i have to wait to see it tested on another stream or feedback at least given.

**Comment by MysticalOS** [comment]
I've had no feedback in 16 days, is everything fine now?

**Comment by tharakadesilva** [comment]
Hey Adam, unfortunately, I've had to make a role switch and I'm no longer
tanking. At this time, I am unable to verify this fix.
-- 
Sincerely,

Tharaka De Silva
