### ISSUE TITLE
Hi! There Dragonflight version? 

### ISSUE THREAD

**Issue by Louivatar** [DeadlyBossMods/DeadlyBossMods#1287]
**Describe the bug**

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by jungheeMW** [comment]
Hi, you can find Dragonflight module [here](https://www.curseforge.com/wow/addons/dbm-dragonflight-requires-deadly-boss-mods-dbm/files/all?page=1&pageSize=20). Make sure to enable "Show alpha files".

**Comment by MysticalOS** [comment]
Should be fixed on CF now btw, forgot to update this.
