### ISSUE TITLE
Normal Silken Court timer errors

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DeadlyBossMods#1302]
**Describe the bug**
1. General timer errors
2. For the frontal warnings, they are labeled "B-Anub" and "R-Takazj". What does the B and R mean?

**Do you have an error log of what happened?**
[normal silken court.zip](https://github.com/user-attachments/files/17220363/normal.silken.court.zip)

**Screenshots**
![WoWScrnShot_100224_105753](https://github.com/user-attachments/assets/8f902835-9976-494d-ae0c-36c8daaa94fb)
![WoWScrnShot_100224_105800](https://github.com/user-attachments/assets/64e4b16c-1705-4a61-bd2d-9b38e762995e)
![WoWScrnShot_100224_105804](https://github.com/user-attachments/assets/c2df5529-c044-4943-ae1d-e62d25b2c122)
![WoWScrnShot_100224_105809](https://github.com/user-attachments/assets/90366393-a3fc-4c92-8949-4d515cf5e2b3)
![WoWScrnShot_100224_105816](https://github.com/user-attachments/assets/1c48e2dd-dc7a-4050-9bf6-979330fefc27)

**Which version of DeadlyBossMods are you using?**
Core 11.0.19-14 alpha

**Comment by MysticalOS** [comment]
yeah I think they changed the bosses timers this week without notice. i saw errors on heroic, you saw on normal and molk saw on LFR, safe to say they changed every mode
