### ISSUE TITLE
DBM standard female voice announcer pronounces frontals "Fronthal" since one update ~ 1-2 weeks ago

### ISSUE THREAD

**Issue by MoundN** [DeadlyBossMods/DeadlyBossMods#1316]
**Describe the bug**
 I expect to hear "Frontal", but instead i hear "Fronthal"

**Do you have an error log of what happened?** Nah no errors on bugsack

**To Reproduce**
I guess intall update from 1 week ago?

**Screenshots** https://youtu.be/fshzvbahpSU

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?** Yes. it's the add-on

**Which version of DeadlyBossMods are you using?** Current

**Was it working in a previous version? If yes, which was the last good one?** Yes, the version before the update 1 week ago.

**Additional context**

**Comment by MysticalOS** [comment]
It's clearly saying frontal when I say it. it's using Amy British accent. but I hear no h in there. people always say she is saying "wash your feet" too when she says "watch your feet". some people just don't recognize words as well when spoken in other accents. Closing this as invalid as the audio is fine. If you do not like the default voice pack there are dozens of 3rd party ones you can check out on curseforge by searching for "DBM Voice"

**Comment by MoundN** [comment]
Nah. you haven't even watched the video where it literally says frontal, besides. my listening skills are fine AND it was fine before that update 1-2 weeks ago. it broke since then. she said frontal before and now says fronthal.

**Comment by MoundN** [comment]
> It's clearly saying frontal when I say it. it's using Amy British accent. but I hear no h in there. people always say she is saying "wash your feet" too when she says "watch your feet". some people just don't recognize words as well when spoken in other accents. Closing this as invalid as the audio is fine. If you do not like the default voice pack there are dozens of 3rd party ones you can check out on curseforge by searching for "DBM Voice"

Nah. you haven't even watched the video where it literally says fronthal, besides. my listening skills are fine AND it was fine before that update 1-2 weeks ago. it broke since then. she said frontal before and now says fronthal.

**Comment by MysticalOS** [comment]
i literlaly opened up audio file before responding to ticket and played it back 3x, it says frontal
