### ISSUE TITLE
11.0.2 Zekvir "?" bug in ZhCN client

### ISSUE THREAD

**Issue by leifan8440** [DeadlyBossMods/DeadlyBossMods#1320]
...ace/AddOns/DBM-Core/modules/objects/Difficulties.lua:480: attempt to concatenate local 'delveTier' (a nil value)
Count: 3

Version: 2023.01.27, Last Time: 17:28:34.200, Call Stack:
["A/DBM-Core/modules/objects/Difficulties.lua:480"]: in function `GetCurrentInstanceDifficulty'
["A/DBM-Core/modules/objects/Difficulties.lua:130"]: in function `RefreshCache'
["A/DBM-Core/DBM-Core.lua:3979"]: in function `func'
["A/DBM-Core/modules/Scheduler.lua:163"]: in function <@153>

https://github.com/DeadlyBossMods/DeadlyBossMods/blob/be3f5e7d1bb8ebe9c3e9d267e0a87463c8b98373/DBM-Core/modules/objects/Difficulties.lua#L472

in ZhCN client, maybe all east asian client

“?” should be "？" "？？"

**Comment by MysticalOS** [comment]
ugg they localize that too, that's stupid annoying. why blizz just couldn't use a damn number is beyond me.

**Comment by Mini-Dragon** [comment]
已经向暴雪中国翻译组提出抗议
A protest has been lodged to the Blizzard China Translation Team

**Comment by MysticalOS** [comment]
hopefully it doesn't need translation anymore either way, i have experimental changes that should work without it
