### ISSUE TITLE
Bugsack error 

### ISSUE THREAD

**Issue by rambutanMan** [DeadlyBossMods/DeadlyBossMods#1324]
**Describe the bug**

Completed the Zekvir challenge and noticed this error.

**Do you have an error log of what happened?**

1x DBM-Core/DBM-Core.lua:6203: attempt to compare number with nil
[string "@DBM-Core/DBM-Core.lua"]:6203: in function `EndCombat'
[string "@DBM-Core/DBM-Core.lua"]:5397: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1080: in function <DBM-Core/DBM-Core.lua:1067>

Locals:
Skipped (In Encounter)

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
What language? this may already be fixed in alpha

**Comment by MysticalOS** [comment]
Does this still occur?
