### ISSUE TITLE
LFR Ansurek

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DeadlyBossMods#1327]
**Describe the bug**
Timer error

**Do you have an error log of what happened?**
[LFR ansurek.zip](https://github.com/user-attachments/files/17348660/LFR.ansurek.zip)

**Screenshots**
![WoWScrnShot_101224_110503](https://github.com/user-attachments/assets/fe66c40c-8603-4677-abd0-ceaff7f5d87e)

**Which version of DeadlyBossMods are you using?**
DBM 10.0.20-24 alpha

**Comment by MysticalOS** [comment]
Seems like some buggy fluke. it should always be 10. but wasn't this time. gonna ignore that for now
