### ISSUE TITLE
localization Error

### ISSUE THREAD

**Issue by bagzli** [DeadlyBossMods/DeadlyBossMods#133]
**Describe the bug**

When the game loads DBM reports a problem as shown in log below. Also noticed in my raid that DBM does not show me any warnings on boss fights nor countdowns done by raid leader.

**Do you have an error log of what happened?**
Date: 2020-02-02 00:00:14
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\DBM-Core\localization.en.lua line 3:
   attempt to call field 'GetCurrentCalendarTime' (a nil value)
Debug:
   DBM-Core\localization.en.lua:3: in main chunk
Locals:
(*temporary) = nil
(*temporary) = "attempt to call field 'GetCurrentCalendarTime' (a nil value)"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.5
  AtlasLootClassicData, vv1.4.5
  AtlasLootClassicDungeonsAndRaids, vv1.4.5
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  AuctionDB, vv1.02.00
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BetterVendorPrice, vv1.11.00
  ClassicThreatMeter, v1.10
  ClassTrainerPlus, v0.6-beta
  DBMCore, v8.3.9
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=365)

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?** Yes I have, same error came up when i reload the ui.

**Which version of DeadlyBossMods are you using?**
I'm using 8.3.9

**Was it working in a previous version? If yes, which was the last good one?**
Yes, I don't keep track of versions but I would say it worked for me roughly 2 updates ago. I update daily through twitch.

**Additional context**

**Comment by MysticalOS** [comment]
8.3.9 is not intended to be used with Classic wow, you must be using 1.13.x

seems like twitch goofed up and installed wrong version. simply remove it and reinstall correct version which will always start with 1.13.x

**Comment by bagzli** [comment]
That solved the problem. Thank you. I can't seem to install classic via twitch anymore so I did a manual install.
