### ISSUE TITLE
Hide Talking Head

### ISSUE THREAD

**Issue by JBodkin** [DeadlyBossMods/DeadlyBossMods#1332]
Would it be possible to add an option to hide the talking heads (but still play the audio) in instances in a similar way to how cinematics are skipped after the first watch?

**Comment by JBodkin** [comment]
I looked around at a few of the addons, but they don't seem to have been updated in quite a while. Also I try not to run too many addons, which seems to be helpful in avoiding some of the performance others have experienced of late.

**Comment by MysticalOS** [comment]
I can understand that. that specific mod is like 3 lines of code that doesn't break with patches so it probably doesn't need updates often.
