### ISSUE TITLE
Information on N'Zoth Gatekeeper timings (normal)

### ISSUE THREAD

**Issue by Tequima** [DeadlyBossMods/DeadlyBossMods#134]
**Describe the bug**
DBM message came up during N'Zoth the Corrupter fight to "contact the author" & something about Gatekeeper timings (apologies - healing at time so couldn't pay too much attention).

**Do you have an error log of what happened?**
Raid logs are here: https://www.warcraftlogs.com/reports/ncYaNMwjvP8dHgxV/

**To Reproduce**
n/a
**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**
8.3.9 2020/02/01 16:02:51

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
the WCL is useless, I'd need screen shot or at least the typed numbers it gave. I appreciate the effort though :)

**Comment by Tequima** [comment]
There weren't any numbers shown. Just the message. We may be running again tomorrow after Heroic raid. If it comes up again I'll remember to screenshot.

**Comment by MysticalOS** [comment]
ah right the version in release had bugged, debug. :D
