### ISSUE TITLE
Lua Errer at Boss "the Seven"

### ISSUE THREAD

**Issue by Duderino84** [DeadlyBossMods/DeadlyBossMods#1346]
**Describe the bug**

**Do you have an error log of what happened?**
4x ...ddOns/DBM-Raids-Vanilla/BlackrockDepths/TheSeven.lua:201: attempt to index field '?' (a nil value)
[string "@DBM-Raids-Vanilla/BlackrockDepths/TheSeven.lua"]:201: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1084: in function <DBM-Core/DBM-Core.lua:1071>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1084: in function <DBM-Core/DBM-Core.lua:1071>
**To Reproduce**
<!-- Steps to reproduce the behavior:
just in boss fight. every 5-8 sek bugsack tells me this

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
i only use DBM

**Which version of DeadlyBossMods are you using?**
Last version

**Was it working in a previous version? If yes, which was the last good one?**
idk

**Additional context**

**Comment by MysticalOS** [comment]
download latest update to fix that. if you don't see it. it should appear soon
