### ISSUE TITLE
Minor inaccuracies with the messages in the N'zoth encounter

### ISSUE THREAD

**Issue by tharakadesilva** [DeadlyBossMods/DeadlyBossMods#135]
**Describe the bug**
There are a couple of minor messages which are inaccurate:
1) In the second phase, when only one tank is in the Mind Realm and an interrupt is missed on the Psychus, a "taunt" message is played to the other tank. This taunt can only happen in phases 1 and 3. Ideally all Mindwracks should be interrupted in this phase.
2) Interrupt is called for the Thought Harvester add on phase 3. The Thought Harvester add is not interruptible.
3) In phase 3, the taunt off mentioned in (1) can only happen if there is only one add. However, if there are two (or more) adds, it means that we have reached the soft enrage. At this point, each tank would have at least one add, so there wouldn't be any advantage of taunting.

**Comment by MysticalOS** [comment]
Closing ticket as invalid, because all 3 of those conditions ARE checked.

for number 2, the interrupt warning DEFINITELY only shows for psychus, it literally runs that code only after checking if source creatureID matches psychus.
		```
if args:GetSrcCreatureID() == 158376 then--Psychus
			timerMindwrackCD:Start(4.9, args.sourceGUID)
			if not castsPerGUID[args.sourceGUID] then
				castsPerGUID[args.sourceGUID] = 0
			end
			if (self.vb.interruptBehavior == "Four" and castsPerGUID[args.sourceGUID] == 4) or (self.vb.interruptBehavior == "Five" and castsPerGUID[args.sourceGUID] == 5) or (self.vb.interruptBehavior == "Six" and castsPerGUID[args.sourceGUID] == 6) then
				castsPerGUID[args.sourceGUID] = 0
			end
			castsPerGUID[args.sourceGUID] = castsPerGUID[args.sourceGUID] + 1
			local count = castsPerGUID[args.sourceGUID]
			if self:CheckInterruptFilter(args.sourceGUID, false, true) then
				specWarnMindwrack:Show(args.sourceName, count)
				if count == 1 then
					specWarnMindwrack:Play("kick1r")
				elseif count == 2 then
					specWarnMindwrack:Play("kick2r")
				elseif count == 3 then
					specWarnMindwrack:Play("kick3r")
				elseif count == 4 then
					specWarnMindwrack:Play("kick4r")
				elseif count == 5 then
					specWarnMindwrack:Play("kick5r")
				else--Shouldn't happen, but fallback rules never hurt
					specWarnMindwrack:Play("kickcast")
				end
			end
		end
```

As for 1 and 3
```
if (not self:IsMythic() and self.vb.phase == 1) or ((self:IsMythic() and self.vb.phase == 2) or self.vb.phase == 3) and self.vb.harvestersAlive == 1 then
			specWarnMindwrackTaunt:Show(args.destName)
			specWarnMindwrackTaunt:Play("changemt")
end
```
That says only show taunt warning if it's not mythic and first phase (so both tanks with big guy). or it's thought harvester phase and ONLY 1 is alive.

**Comment by MysticalOS** [comment]
also this site is dumb as hell because it can't do proper code blocks around code....on a coding website? wtf

**Comment by tharakadesilva** [comment]
`

> also this site is dumb as hell because it can't do proper code blocks around code....on a coding website? wtf

use triple backticks around the code block.
