### ISSUE TITLE
Error upon entering game - message posted below

### ISSUE THREAD

**Issue by nitemair** [DeadlyBossMods/DeadlyBossMods#136]
Date: 2020-02-04 03:16:55
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\DBM-Core\localization.en.lua line 3:
   attempt to call field 'GetCurrentCalendarTime' (a nil value)
Debug:
   DBM-Core\localization.en.lua:3: in main chunk
Locals:
(*temporary) = nil
(*temporary) = "attempt to call field 'GetCurrentCalendarTime' (a nil value)"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.5
  AtlasLootClassicData, vv1.4.5
  AtlasLootClassicDungeonsAndRaids, vv1.4.5
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  CEPGP, v
  ClassicCastbars, vv1.2.5
  ClassicCastbarsOptions, v
  DBMCore, v8.3.10-2-g2be3126
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=343)

**Comment by MysticalOS** [comment]
That happens when installing retail DBM on dbm classic, install correct version of DBM

**Comment by nitemair** [comment]
Is the classic version no longer in Twitch? Or is it named something other than Deadly Boss Mods (DBM) - Classic ?

**Comment by MysticalOS** [comment]
it's there, in same place it always was, the client just sometimes breaks and mixes retail with classic. no one knows why. which is why you shouldn't let twitch client AUTOMATICALLY update, set it to manual, and verify version always starts with 1.13. and not something else. if it's not 1.13.x it's not for classic. if it shows wrong dbm version, restart twitch client to refresh it and get it to hopefully show correct one.

**Comment by nitemair** [comment]
Ah that makes sense. Believe that did the trick! Appreciate the help
