### ISSUE TITLE
Harvester Spawn timers

### ISSUE THREAD

**Issue by MadJeff2k19** [DeadlyBossMods/DeadlyBossMods#138]
![image](https://user-images.githubusercontent.com/59944788/73786441-3a2bcb00-4791-11ea-9194-609afbdd3563.png)

Normal N'zoth

**Comment by MysticalOS** [comment]
Thanks, i added these into next update. if you get additional ones past 45 please be sure to post. I'll leave ticket open cause others will probably come here soon enough as well.

**Comment by DoctorBooooom** [comment]
I have the same:

![image](https://user-images.githubusercontent.com/3152959/73974692-dd1d4a00-4935-11ea-8144-0a02582e96b0.png)
Normal N'zoth

**Comment by bosskev** [comment]
In normal mode :
![image](https://user-images.githubusercontent.com/60900354/74189398-99d21c80-4c50-11ea-95b6-7cc447b3cba6.png)

**Comment by bosskev** [comment]
In normal mode again :
![image](https://user-images.githubusercontent.com/60900354/74190608-eae31000-4c52-11ea-942a-640e612a6ad9.png)

**Comment by bosskev** [comment]
In normal mode again :
![image](https://user-images.githubusercontent.com/60900354/74191814-8f198680-4c54-11ea-8d82-f9fc486bb50a.png)

**Comment by bosskev** [comment]
And in normal mode again :
![image](https://user-images.githubusercontent.com/60900354/74193064-04865680-4c57-11ea-80d7-f5a91e6b082a.png)

**Comment by MysticalOS** [comment]
Thanks, added the additional data

**Comment by Tequima** [comment]
![image](https://user-images.githubusercontent.com/54499085/74567529-e88ff700-4f6d-11ea-999b-6e23bb80f479.png)
Heroic mode

**Comment by smiley** [comment]
![image](https://user-images.githubusercontent.com/354181/74595469-47c33980-504a-11ea-80e8-6b0bfbea15c0.png)
On Heroic difficulty

**Comment by Chavez906** [comment]
Hi ! 
On HM last night, I got this ones 15.5 25.9 45.4 30.5 4.1

**Comment by periflo90** [comment]
Raid Finder:

![WoWScrnShot_031620_133550](https://user-images.githubusercontent.com/7262313/76759047-35dccf80-678b-11ea-93d3-deffb6990cae.jpg)

**Comment by Toniapat** [comment]
![unknown](https://user-images.githubusercontent.com/62588040/77396142-cfb80400-6dab-11ea-8639-f14ff07c3ffb.png)

On heroic Difficulty last night :)

**Comment by ekreiter** [comment]
![image](https://user-images.githubusercontent.com/64662943/80838399-90f14700-8bbe-11ea-991a-a363d9be0e39.png)


LFR!

**Comment by micolous** [comment]
LFR: 16.2, 26, 45.7, 30.3, 30.7, 44, 30.2, 31, 42.6, 30.9

Collected 2020-04-30.
