### ISSUE TITLE
DBM doesn't work on the Silken court (nerubar palace raid)

### ISSUE THREAD

**Issue by fr3dbayl3** [DeadlyBossMods/DeadlyBossMods#1390]
**Describe the bug**

There's no alert, no timer, simply nothing.

**Do you have an error log of what happened?**

Here's le test mode log :
Test: TWW/NerubarPalace/SilkenCourt/Mythic/Kill
Mod:  DBM-Raids-WarWithin/2608

Findings:
  Unused event registration: SPELL_AURA_APPLIED 438200 (Éclair de poison)
  Unused event registration: SPELL_AURA_APPLIED 438218 (Frappe transperçante)
  Unused event registration: SPELL_AURA_APPLIED 438708 (Essaim d’insectes piqueurs)
  Unused event registration: SPELL_AURA_APPLIED 440001 (Toiles liantes)
  Unused event registration: SPELL_AURA_APPLIED 440179 (Enchevêtrement)
  Unused event registration: SPELL_AURA_APPLIED 443598 (Rage incontrôlable)
  Unused event registration: SPELL_AURA_APPLIED 449857 (Empalement)
  Unused event registration: SPELL_AURA_APPLIED 450980 (Fracassement d’existence)
  Unused event registration: SPELL_AURA_APPLIED 451277 (Tempête de pointes)
  Unused event registration: SPELL_AURA_APPLIED 455080 (Persévérance du seigneur scarabée)
  Unused event registration: SPELL_AURA_APPLIED 455849 (Marque de paranoïa)
  Unused event registration: SPELL_AURA_APPLIED 455850 (Marque de rage)
  Unused event registration: SPELL_AURA_APPLIED 456235 (Délire piquant)
  Unused event registration: SPELL_AURA_APPLIED 456245 (Délire piquant)
  Unused event registration: SPELL_AURA_APPLIED 456252 (Essaim d’insectes piqueurs)
  Unused event registration: SPELL_AURA_APPLIED_DOSE 438200 (Éclair de poison)
  Unused event registration: SPELL_AURA_APPLIED_DOSE 438218 (Frappe transperçante)
  Unused event registration: SPELL_AURA_APPLIED_DOSE 456252 (Essaim d’insectes piqueurs)
  Unused event registration: SPELL_AURA_REMOVED 440001 (Toiles liantes)
  Unused event registration: SPELL_AURA_REMOVED 450980 (Fracassement d’existence)
  Unused event registration: SPELL_AURA_REMOVED 451277 (Tempête de pointes)
  Unused event registration: SPELL_AURA_REMOVED 455080 (Persévérance du seigneur scarabée)
  Unused event registration: SPELL_AURA_REMOVED 456252 (Essaim d’insectes piqueurs)
  Unused event registration: SPELL_CAST_START 438218 (Frappe transperçante)
  Unused event registration: SPELL_CAST_START 438343 (Pluie venimeuse)
  Unused event registration: SPELL_CAST_START 438355 (Entropie cataclysmique)
  Unused event registration: SPELL_CAST_START 438677 (Essaim d’insectes piqueurs)
  Unused event registration: SPELL_CAST_START 438801 (Appel de l’essaim)
  Unused event registration: SPELL_CAST_START 439838 (Bombe de toile)
  Unused event registration: SPELL_CAST_START 440246 (Charge téméraire)
  Unused event registration: SPELL_CAST_START 440504 (Éruption empalante)
  Unused event registration: SPELL_CAST_START 441626 (Vortex de rets)
  Unused event registration: SPELL_CAST_START 441782 (Brins de réalité)
  Unused event registration: SPELL_CAST_START 441791 (Éruption enfouie)
  Unused event registration: SPELL_CAST_START 442994 (Essaim déchaîné)
  Unused event registration: SPELL_CAST_START 443068 (Éruption de pointes)
  Unused event registration: SPELL_CAST_START 450045 (Bond grouillant)
  Unused event registration: SPELL_CAST_START 450129 (Désolation entropique)
  Unused event registration: SPELL_CAST_START 450483 (Pas du Vide)
  Unused event registration: SPELL_CAST_START 452231 (Essaim d’insectes piqueurs)
  Unused event registration: SPELL_CAST_START 456174 (S’enfouir)
  Unused event registration: SPELL_SUMMON 438249 (Appel de l’essaim)

Unused objects:
  [Announce] Éclair de poison sur >%s< (%d), type=stack, spellId=438200
  [Announce] Frappe transperçante sur >%s< (%d), type=stack, spellId=438218
  [Announce] Adds (%s), type=count, spellId=438801
  [Announce] Bombe de toile (%s), type=count, spellId=439838
  [Announce] Toiles liantes s'est dissipé, type=fades, spellId=440001
  [Announce] Enchevêtrement sur >%s<, type=target, spellId=440179
  [Announce] Fouir (%s), type=count, spellId=441791
  [Announce] Empalement sur >%s<, type=target, spellId=449857
  [Announce] Bondir (%s), type=count, spellId=450045
  [Special Warning] Frappe transperçante - défensif, type=defensive, spellId=438218
  [Special Warning] Frappe transperçante sur >%s< - provoquez maintenant, type=taunt, spellId=438218
  [Special Warning] Charge ! (%s), type=count, spellId=440246
  [Special Warning] Devant [B-Anub] (%s) - esquivez l'attaque, type=dodgecount, spellId=440504
  [Special Warning] Marque de paranoïa sur vous, type=you, spellId=455849
  [Special Warning] Marque de rage sur vous, type=you, spellId=455850
  [Timer] Rech. Frappe transperçante (%s), time=49.00, type=cdcount, spellId=438218
  [Timer] Adds (%s), time=49.00, type=cdcount, spellId=438801
  [Timer] Charge, time=49.00, type=cast, spellId=440246
  [Timer] Rech. Charge (%s), time=49.00, type=cdcount, spellId=440246
  [Timer] Devant [B-Anub] (%s), time=49.00, type=cdcount, spellId=440504
  [Timer] Rech. Fouir (%s), time=49.00, type=cdcount, spellId=441791
  [Yell] Empalement, type=shortyell, spellId=449857

Timers:
  None

Announces:
  None

Special warnings:
  None

Yells:
  None

Voice pack sounds:
  None

Icons:
  None

Event trace:
  [  0.00] ENCOUNTER_START: 2921, The Silken Court, 16, 20, 0
    StartCombat: ENCOUNTER_START
    RegisterEvents: Regular, SPELL_CAST_START 438218 438801 440246 440504 438343 439838 450045 438677 452231 441626 450129 441782 450483 438355 443068 456174 442994 441791, SPELL_SUMMON 438249, SPELL_AURA_APPLIED 455849 455850 438218 455080 449857 440001 450980 438708 451277 443598 440179 456245 438200 456235 456252, SPELL_AURA_APPLIED_DOSE 438218 438200 456252, SPELL_AURA_REMOVED 455080 450980 451277 440001 456252
  [535.36] ENCOUNTER_END: 2921, The Silken Court, 16, 20, 1, 0
    EndCombat: ENCOUNTER_END
    PlaySound: Interface\AddOns\DBM-Core\sounds\Victory\SmoothMcGroove_Fanfare.ogg
  Unknown trigger
    UnregisterEvents: Regular, SPELL_AURA_REMOVED 455080 450980 451277 440001 456252

**To Reproduce**

1. go to the test mode of the silken court
2. click on the test mode
3. execute the test. 
4. See error (no error but nothing happens during the test, these steps work on other bosses without any problem)

**Screenshots**

-

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

I tried testing it with DBM as the only loaded addon

**Which version of DeadlyBossMods are you using?**

11.0.32-20

**Was it working in a previous version? If yes, which was the last good one?**

It worked on the 11.0.25-26 but stopped working on the 11.0.25-27

**Additional context**

-

**Comment by MysticalOS** [comment]
what language you playing on?

**Comment by fr3dbayl3** [comment]
OK, let's wait and see :) Thank you for your feedback !

**Comment by fr3dbayl3** [comment]
Last update fixed the issue, thank you for your work :)
