### ISSUE TITLE
Two Bug Reports, Timers in Bossfights don't work...

### ISSUE THREAD

**Issue by Sarafira** [DeadlyBossMods/DeadlyBossMods#141]
Date: 2020-02-05 18:28:17
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\DBM-Core\localization.en.lua line 3:
   attempt to call field 'GetCurrentCalendarTime' (a nil value)
Debug:
   DBM-Core\localization.en.lua:3: in main chunk
Locals:
(*temporary) = nil
(*temporary) = "attempt to call field 'GetCurrentCalendarTime' (a nil value)"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.5
  AtlasLootClassicData, vv1.4.5
  AtlasLootClassicDungeonsAndRaids, vv1.4.5
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  Bartender4, v4.9.0
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  DBMCore, v8.3.10
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_deDE v1.13.3.11303 <none>
  (ck=2e1)

Date: 2020-02-05 18:28:17
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\DBM-Core\localization.de.lua line 297:
   attempt to index global 'DBM_CORE_AUTO_ANNOUNCE_TEXTS' (a nil value)
Debug:
   DBM-Core\localization.de.lua:297: in main chunk
Locals:
(*temporary) = nil
(*temporary) = "you"
(*temporary) = "%s auf DIR"
(*temporary) = "/dbm ltimer <sec> <text>: Startet einen Timer, der automatisch wiederholt wird, bis er abgebrochen wird."
(*temporary) = "/dbm broadcast timer/ltimer/cltimer <sec> <text>: schickt den Timer an den Schlachtzug (nur als Leiter/Assistent)."
(*temporary) = "/dbm timer endloop: Stoppt alle ltimer-."
(*temporary) = "/dbm version2: Führt eine Boss Mod Versionsprüfung durch und flüstert Nutzer mit veralteten Versionen an (Alias: ver2)."
(*temporary) = "/dbm lockout: Fragt die Schlachtzugsmitglieder nach ihren derzeitigen Instanzsperren (IDs) (nur als Leiter/Assistent) (Aliase: lockouts, ids)."
(*temporary) = "/dbm lag: Prüft die Latenz im gesamten Schlachtzug."
(*temporary) = "/dbm durability: Prüft die Haltbarkeit im gesamten Schlachtzug."
(*temporary) = "attempt to index global 'DBM_CORE_AUTO_ANNOUNCE_TEXTS' (a nil value)"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.5
  AtlasLootClassicData, vv1.4.5
  AtlasLootClassicDungeonsAndRaids, vv1.4.5
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  Bartender4, v4.9.0
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  DBMCore, v8.3.10
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_deDE v1.13.3.11303 <none>
  (ck=2e1)

**Comment by MysticalOS** [comment]
I'm just gonna delete the april fools joke on Retail DBm since twitch client keeps installing it in classic. that'll at least solve this error. won't solve the fact twitch client keeps installing wrong DBM, but at least it'll go back to reporting it's the wrong DBM instead of throwing an error.


As for what you need to do, probably uninstall twitch client and start installing addons manually because that seems to be the only way you'll not constantly get the wrong versions of addons. you need DBM 1.13.30, NOT dbm 8.3.10
