### ISSUE TITLE
Harvester Spawn Timer

### ISSUE THREAD

**Issue by DuskeZ** [DeadlyBossMods/DeadlyBossMods#142]
![ererer](https://user-images.githubusercontent.com/32484831/73887414-c27e9e80-486b-11ea-8c7e-4ff9ac987846.png)

**Comment by DuskeZ** [comment]
Heroic

**Comment by MysticalOS** [comment]
Thanks, closing issue/combining into https://github.com/DeadlyBossMods/DeadlyBossMods/issues/138 though. :)
