### ISSUE TITLE
Error in DBM

### ISSUE THREAD

**Issue by Sharpthorne** [DeadlyBossMods/DeadlyBossMods#144]
Date: 2020-02-06 12:27:53
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\DBM-Core\localization.en.lua line 3:
   attempt to call field 'GetCurrentCalendarTime' (a nil value)
Debug:
   DBM-Core\localization.en.lua:3: in main chunk
Locals:
(*temporary) = nil
(*temporary) = "attempt to call field 'GetCurrentCalendarTime' (a nil value)"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.5
  AtlasLootClassicData, vv1.4.5
  AtlasLootClassicDungeonsAndRaids, vv1.4.5
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BetterVendorPrice, vv1.11.00
  DBMCore, v8.3.9
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=334)

**Comment by MysticalOS** [comment]
Don't install retail DBm in classic. install only 1.13.x versions of mod, with latest being 1.13.31

**Comment by houlia** [comment]
It would seem the Twitch app has been auto-updating classic users to the retail version.  Not sure if a flag is set incorrectly somewhere, or this is just a mess up on Twitch's end.  But you can probably expect to see a lot more of this complaint.

**Comment by MysticalOS** [comment]
twitches end. and i recommend to all users to DISABLE auto udpating in twitch client. manually review it every time. I still use twitch to update addons, but i fire it up and it does nothing unless i HIT update. that way I can review what file it wants to do first
