### ISSUE TITLE
LUA ERRORS - ENTERING HEROIC 10 MAN ICECROWN RAID

### ISSUE THREAD

**Issue by Wyr3d** [DeadlyBossMods/DeadlyBossMods#1444]
On entering this raid for farming, the following LUA errors popped up:

Error 1

Message: Interface/AddOns/DBM-Core/DBM-Core.lua:8443: DBM iconType must be a number. If you are seeing this error your content mods are probabably out of date
Time: Tue Dec 17 17:02:20 2024
Count: 1
Stack: Interface/AddOns/DBM-Core/DBM-Core.lua:8443: DBM iconType must be a number. If you are seeing this error your content mods are probabably out of date
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:8443: in function `AddSetIconOption'
[string "@Interface/AddOns/DBM-Raids-WoTLK/Ulduar/XT002.lua"]:53: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:4241: in function `LoadMod'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:4177: in function `LoadModsOnDemand'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:4045: in function `func'
[string "@Interface/AddOns/DBM-Core/modules/Scheduler.lua"]:163: in function <Interface/AddOns/DBM-Core/modules/Scheduler.lua:153>

Locals: self = <table> {
 inCombatOnlyEvents = <table> {
 }
 timers = <table> {
 }
 categorySort = <table> {
 }
 combatInfo = <table> {
 }
 modelId = 28611
 SyncThreshold = 8
 numBoss = 1
 usedIcons = <table> {
 }
 encounterId = 1142
 creatureId = 33293
 modId = "DBM-Raids-WoTLK"
 groupSpells = <table> {
 }
 statTypes = "normal,timewalker"
 isTrashMod = false
 specwarns = <table> {
 }
 zones = <table> {
 }
 revision = 20230522065847
 Options = <table> {
 }
 DefaultOptions = <table> {
 }
 id = "XT002"
 inCombat = false
 addon = <table> {
 }
 iconRestore = <table> {
 }
 isDummyMod = false
 groupOptions = <table> {
 }
 optionCategories = <table> {
 }
 yells = <table> {
 }
 localization = <table> {
 }
 announces = <table> {
 }
 vb = <table> {
 }
 subTab = 5
}
name = "SetIconOnLightBombTarget"
spellId = 65121
default = true
iconType = true
iconsUsed = <table> {
 1 = 1
}
conflictWarning = nil
groupSpellId = nil
DBM = <table> {
 DungeonMusic = <table> {
 }
 ReleaseRevision = 20241214000000
 TaintedByTests = false
 Arrow = <table> {
 }
 RangeCheck = <table> {
 }
 Test = <table> {
 }
 Voices = <table> {
 }
 BattleMusic = <table> {
 }
 InfoFrame = <table> {
 }
 Flash = <table> {
 }
 ModLists = <table> {
 }
 Difficulties = <table> {
 }
 Music = <table> {
 }
 classicSubVersion = 0
 HighestRelease = 20241214000000
 registeredUnitEvents = <table> {
 }
 VoiceVersions = <table> {
 }
 AddOns = <table> {
 }
 Options = <table> {
 }
 Victory = <table> {
 }
 Revision = 20241214215312
 Defeat = <table> {
 }
 DefaultOptions = <table> {
 }
 Counts = <table> {
 }
 Nameplate = <table> {
 }
 HudMap = <table> {
 }
 DisplayVersion = "11.0.38"
 Mods = <table> {
 }
}
L = <table> {
 AUTO_RRANGE_OPTION_TEXT = "Show reverse range frame (%s) for $spell:%s"
 ANNOUNCE_PULL = "Pull in %d sec. (Sent by %s)"
 OUT_OF_DATE_NAG = "Your version of DBM is out-of-date and this specific fight mod has newer features or bug fixes. It is recommended you update for this fight to improve your experience."
 VERSIONCHECK_ENTRY_TWO = "%s: %s (%s) & %s (%s)"
 MPROFILE_COPY_SUCCESS = "%s's (%d spec) mod settings have been copied."
 OPTION_CATEGORY_WARNINGS_ROLE = "Role Announces"
 TIMER_FORMAT_MINS = "%d |4minute:minutes;"
 ANNOUNCE_PULL_TARGET = "Pulling %s in %d sec. (Sent by %s)"
 OVERRIDE_ACTIVATED = "Configuration overrides have been activated for this encounter by RL"
 LAG_FOOTER = "No Response: %s"
 AUTO_ICONS_OPTION_TARGETS_ALPHA = "Set icons on $spell:%s targets with alphabetical priority"
 INFOFRAME_TITLE = "DBM Info Frame"
 PROFILE_APPLIED = "'%s' profile applied."
 PIZZA_SYNC_INFO = "[%1$s] sent you a DBM timer: '%2$s'
[Cancel this timer]  [Ignore timers from %1$s]"
 AUTO_ICONS_OPTION_TARGETS = "Set icons on $spell:%s targets"
 RANGECHECK_HEADERT = "Range Check (%dy-%dP)"
 GEAR_WARNING = "Warning: Check gear. Your equipped ilvl is %d lower than bag ilvl"
 AUTO_YELL_OPTION_TEXT = <table> {
 }
 RANGECHECK_RHEADER = "R-Range Check (%dy)"
 RANGERADAR_HEADER = "Range:%d Players:%d"
 DBM_INSTALL_REMINDER_DISABLE2 = "Do not show this mes
 
 
 Error 2
 
 Message: Interface/AddOns/DBM-Core/DBM-Core.lua:8443: DBM iconType must be a number. If you are seeing this error your content mods are probabably out of date
Time: Tue Dec 17 17:02:20 2024
Count: 1
Stack: Interface/AddOns/DBM-Core/DBM-Core.lua:8443: DBM iconType must be a number. If you are seeing this error your content mods are probabably out of date
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:8443: in function `AddSetIconOption'
[string "@Interface/AddOns/DBM-Raids-WoTLK/Ulduar/YoggSaron.lua"]:84: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:4241: in function `LoadMod'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:4177: in function `LoadModsOnDemand'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:4045: in function `func'
[string "@Interface/AddOns/DBM-Core/modules/Scheduler.lua"]:163: in function <Interface/AddOns/DBM-Core/modules/Scheduler.lua:153>

Locals: self = <table> {
 inCombatOnlyEvents = <table> {
 }
 timers = <table> {
 }
 specwarns = <table> {
 }
 hotfixNoticeRev = 20230122000000
 categorySort = <table> {
 }
 modelId = 28817
 isTrashMod = false
 numBoss = 1
 usedIcons = <table> {
 }
 SyncThreshold = 8
 combatInfo = <table> {
 }
 modId = "DBM-Raids-WoTLK"
 groupSpells = <table> {
 }
 encounterId = 1143
 creatureId = 33288
 statTypes = "normal,timewalker"
 zones = <table> {
 }
 revision = 20240113024857
 yells = <table> {
 }
 DefaultOptions = <table> {
 }
 iconRestore = <table> {
 }
 Options = <table> {
 }
 id = "YoggSaron"
 inCombat = false
 isDummyMod = false
 groupOptions = <table> {
 }
 addon = <table> {
 }
 optionCategories = <table> {
 }
 localization = <table> {
 }
 announces = <table> {
 }
 vb = <table> {
 }
 subTab = 5
}
name = "SetIconOnBeacon"
spellId = 64465
default = true
iconType = true
iconsUsed = <table> {
 1 = 1
 2 = 2
 3 = 3
 4 = 4
 5 = 5
 6 = 6
 7 = 7
 8 = 8
}
conflictWarning = nil
groupSpellId = nil
DBM = <table> {
 DungeonMusic = <table> {
 }
 ReleaseRevision = 20241214000000
 TaintedByTests = false
 Arrow = <table> {
 }
 RangeCheck = <table> {
 }
 Test = <table> {
 }
 Voices = <table> {
 }
 BattleMusic = <table> {
 }
 InfoFrame = <table> {
 }
 Flash = <table> {
 }
 ModLists = <table> {
 }
 Difficulties = <table> {
 }
 Music = <table> {
 }
 classicSubVersion = 0
 HighestRelease = 20241214000000
 registeredUnitEvents = <table> {
 }
 VoiceVersions = <table> {
 }
 AddOns = <table> {
 }
 Options = <table> {
 }
 Victory = <table> {
 }
 Revision = 20241214215312
 Defeat = <table> {
 }
 DefaultOptions = <table> {
 }
 Counts = <table> {
 }
 Nameplate = <table> {
 }
 HudMap = <table> {
 }
 DisplayVersion = "11.0.38"
 Mods = <table> {
 }
}
L = <table> {
 AUTO_RRANGE_OPTION_TEXT = "Show reverse range frame (%s) for $spell:%s"
 ANNOUNCE_PULL = "Pull in %d sec. (Sent by %s)"
 OUT_OF_DATE_NAG = "Your version of DBM is out-of-date and this specific fight mod has newer features or bug fixes. It is recommended you update for this fight to improve your experience."
 VERSIONCHECK_ENTRY_TWO = "%s: %s (%s) & %s (%s)"
 MPROFILE_COPY_SUCCESS = "%s's (%d spec) mod settings have been copied."
 OPTION_CATEGORY_WARNINGS_ROLE = "Role Announces"
 TIMER_FORMAT_MINS = "%d |4minute:minutes;"
 ANNOUNCE_PULL_TARGET = "Pulling %s in %d sec. (Sent by %s)"
 OVERRIDE_ACTIVATED = "Configuration overrides have been activated for this encounter by RL"
 LAG_FOOTER = "No Response: %s"
 AUTO_ICONS_OPTION_TARGETS_ALPHA = "Set icons on $spell:%s targets with alphabetical priority"
 INFOFRAME_TITLE = "DBM Info Frame"
 PROFILE_APPLIED = "'%s' profile applied."
 PIZZA_SYNC_INFO = "[%1$s] sent you a DBM timer: '%2$s'
[Cancel this timer]  [Ignore timers from %1$s]"
 AUTO_ICONS_OPTION_TARGETS = "Set icons on $spell:%s targets"
 RANGECHECK_HEADERT = "Range Check (%dy-%dP)"
 GEAR_WARNING = "Warning: Check gear. Your equipped ilvl is %d lower than bag ilvl"
 AUTO_YELL_OPTION_TEXT = <table> {
 }
 RANGECHECK_RHEADER = "R-Range Check (%dy)"
 RANGERADAR_HEA

**Comment by jungheeMW** [comment]
The error message indicates that your DBM is incredibly out of date. What version is your DBM?

**Comment by Wyr3d** [comment]
I updated it yesterday :S

**Comment by MysticalOS** [comment]
DBM isn't out of date, your wrath modules are.
