### ISSUE TITLE
Restarting variable timer as non-variable keeps it variable

### ISSUE THREAD

**Issue by emmericp** [DeadlyBossMods/DeadlyBossMods#1454]
Reproducer:

```
foo = DBM:NewMod("Foo")
t = foo:NewCDTimer(123, "test")
t:Start("v20-30")
t:Start(50)
```

That should yield a normal 50 second timer but instead creates a 40-50 variable timer. If you add an explicit :Stop() between the calls it works as expected. If you restart it twice it also works.

**Comment by MysticalOS** [comment]
Should be fixed by https://github.com/DeadlyBossMods/DeadlyBossMods/commit/b02995e5800074b835dd60f37f6c2b771f4b299b

**Comment by Zidras** [comment]
Indeed, I left the newBar reuse untouched, and it caused the issue you're describing.
https://github.com/DeadlyBossMods/DeadlyBossMods/blob/95f79343e84ed61984a2d794f9d15f07f2a968d4/DBM-StatusBarTimers/DBT.lua#L340-L341
This should also be added to keep the newBar data filled with all variance variables:
```lua
newBar.minTimer = varianceMinTimer or nil
```

**Comment by Zidras** [comment]
https://github.com/DeadlyBossMods/DeadlyBossMods/commit/7d94c55db504afed2648e8505490f6f6ed429fae 
Can be closed
