### ISSUE TITLE
An error message occured in Conclave

### ISSUE THREAD

**Issue by Elnarfim** [DeadlyBossMods/DeadlyBossMods#15]
1x DBM-Core\DBM-Core-8.1.26-15-g6c32bc4ff.lua:10840: usage: DBM:Schedule(time, func, [args...])
[C]: in function `error'
DBM-Core\DBM-Core-8.1.26-15-g6c32bc4ff.lua:1736: in function `Schedule'
DBM-Core\DBM-Core-8.1.26-15-g6c32bc4ff.lua:10840: in function `AddTime'
...faceDBM-ZuldazarRaid\ConclaveoftheChosen.lua:441: in function `handler'
DBM-Core\DBM-Core-8.1.26-15-g6c32bc4ff.lua:711: in function <DBM-Core\DBM-Core.lua:698>

Locals:
InCombatSkipped

**Comment by MysticalOS** [comment]
It should be fixed, but I didn't close ticket right away because I want to make sure.

**Comment by Elnarfim** [comment]
No errors now
