### ISSUE TITLE
BWL - Broodlord Mortal Strike Countdown Timer

### ISSUE THREAD

**Issue by specialt123** [DeadlyBossMods/DeadlyBossMods#155]
I wanted to confirm if this was expected to anticipate the MS timer from Broodlord Lashslayer or if it was to count for how long the debuff was on your tank? Between our guild run the last night, the majority were not seeing this activate in advance of the MS coming, yet 1 person stated it was. We did ensure it was turned on as we noticed by default it was not. Just looking for clarification as that fight is much easier knowing when Priests need to bubble tank prior to MS.

**Comment by MysticalOS** [comment]
A CD timer for it is not really doable, it's got too large of a timer range.

a target timer for when it expires on tank already exists but it's only on by default for those in a mostly tank tree spec. so fury tanks probably won't even see it by default (all they need to do is enable timer though).

**Comment by specialt123** [comment]
Got it, that helps us plan then so what exists right now is just the CD to have it expire there, not the advance notice. We'll plan accordingly then, appreciate the quick response.

**Comment by MysticalOS** [comment]
I realize the target timer and target warning should be tank AND healer by default so I'm making that weak. healers need to know too by default, not just tanks.

**Comment by specialt123** [comment]
That works, appreciate it!
