### ISSUE TITLE
Darkmoon Cannon Countdown not working

### ISSUE THREAD

**Issue by nearlysober80** [DeadlyBossMods/DeadlyBossMods#158]
**Describe the bug**
Darkmoon Canon countdown to assist with timing the landing is no longer working.  Confirmed the module is loaded, even reset addon preferences (although I hadn't changed any).

**To Reproduce**
1. Launch from the darkmoon cannon

**Comment by MysticalOS** [comment]
this was removed because it got too many tickets about "being wrong" when all it ever did was countdown til buff expired, not for when you should push button.
