### ISSUE TITLE
REQ: Council fights - Health info

### ISSUE THREAD

**Issue by FuxieDK** [DeadlyBossMods/DeadlyBossMods#163]
For counsil fights where bosses DOES NOT share health pool (e.g. Hivemind@Ny'alotha, Hellfire High Council@Hellfire Citadel), can we have the info-frame display the percentage of each boss?

Most of these fights, the bosses need to go down at the same time (or within seconds of eachother), so having a clear constant display of health would make it easier to focus on balancing the damage.

**Comment by MysticalOS** [comment]
No, this is built into default UI, the boss frames on right. in addition most unit frames replace that with better ones. this is why dbm got rid of bosshealth in first place. DBM will usually call out when the 10 second cast starts for bosses like this and that's about all it needs. health monitoring should be done via unit frames.

**Comment by FuxieDK** [comment]
The frames on the right are small, unclickable and most important WITHOUT TEXT.


And most people probably have them covered by something, as they rarely are displayed ;)
