### ISSUE TITLE
Question regarding old DBM (WOTLK), Huge bars animation transition

### ISSUE THREAD

**Issue by djabawabadza** [DeadlyBossMods/DeadlyBossMods#167]
I just waned to know where (in the code) is the timer that controls the transition from small bar to a huge one and is it possible to be instant with no animation?

**Comment by MysticalOS** [comment]
no idea, i am not gonna look at code from 10 years ago either. Private servers are not supported by DBM. You use those old versions of addons as is.

If and when TBC, and wrath servers officially happen, DBM versions released for them will be based off current code, not the code used in those original versions.
