### ISSUE TITLE
Add leeroy sound on countdown

### ISSUE THREAD

**Issue by alexis35115** [DeadlyBossMods/DeadlyBossMods#170]
This is just an idea, but would be awesome to have the "leeroy jenkins" sound when the pull timer ends up.

https://www.youtube.com/watch?v=yOMj7WttkOA

**Comment by grahamers2002** [comment]
Having a planned time when the Leeroy effect goes off so that everyone can start the fight in a coordinated manner goes against all that is Leeroy!
