### ISSUE TITLE
DBM update issue

### ISSUE THREAD

**Issue by Zen-Karma** [DeadlyBossMods/DeadlyBossMods#172]
For some reason my DBM retail wants to update to classic in the twitch app. Is this a known issue? If so is there a fix? So far only way to prevent it is to ignore the addon in twitch.

**Comment by QartemisT** [comment]
Along with 23 other reports (https://github.com/DeadlyBossMods/DeadlyBossMods/issues?q=is%3Aissue+is%3Aclosed+twitch), this is a twitch issue and only twitch can fix it.
So unless they decide to actually "do work", we're all doomed :(

**Comment by Zen-Karma** [comment]
Sorry to add another but thanks for letting me know what is going on. Guess it's time to annoy twitch to fix this haha
