### ISSUE TITLE
wowinterface.com incorrectly lists 8.2.20 as the current version

### ISSUE THREAD

**Issue by StevenSlater** [DeadlyBossMods/DeadlyBossMods#180]
hi,

the DBM page on wowinterface.com incorrectly lists 8.2.20 as the current version of (at least) DBM core. this results in the download button (as well as minion) getting the vastly outdated 8.2.20 instead of the current 8.3.20, which can still be downloaded manually under "files").

br
Steven

**Comment by MysticalOS** [comment]
oh right the tad tag got pushed there too, @QartemisT 's fault

**Comment by MysticalOS** [comment]
apparently it can't be fixed their site doesn't support deleting "current version" file, so it's probably gonna have to stay broken for a few months since there are no planned releases for a while.

**Comment by MysticalOS** [comment]
Decided to go ahead and tag a new release to just resolve the WoWI file issue that way, as well as get some timer improvements out.
