### ISSUE TITLE
Icons instead of Bars

### ISSUE THREAD

**Issue by Bibimbapi** [DeadlyBossMods/DeadlyBossMods#182]
with the rise in WeakAuras showing boss abilities in icon form, would it be possible to implement the option to convert bars to icons? 

icon+timer gives you the information you need a tiny bit faster than bar+text+icon.

maybe in Shadowlands?

cheers

**Comment by MysticalOS** [comment]
Not something I'm intending to do locally, but many have already done that with weak auras that are fully able to read all the timer data from DBM. https://wago.io/B1pfxTOtb for example (although I believe that doesn't work anymore) but I still use it as an exampl that anyone can make a weak aura to present bars any way they like.
