### ISSUE TITLE
1.13.44 version, may 2 2020 (classic) updates every day from twitch client

### ISSUE THREAD

**Issue by fagitomania** [DeadlyBossMods/DeadlyBossMods#183]
This is not the problem of twitch installing the retail version on my classic installation, my DBM is working correctly on classic as well. 
Its just that since the last update, on the twitch client it shows theres a new update every time i open it. I have installed multiple times in the same day as well

**Comment by MysticalOS** [comment]
If it's set to alpha version, there has been an update every day sometimes multiple. if it says just 1.13.44 that'd be odd, but if it says 1.13.44-7 then that's completely normal and if you don't want alpha versions you can turn that off.

If it's repeatedly showing same file though then I imagine something is wrong with install and twitch client is having trouble fixing it/detecting it right. either way though neither of those are issues with DBM so closing this issue.
