### ISSUE TITLE
Loading into Dungeon

### ISSUE THREAD

**Issue by DRYLOFFA** [DeadlyBossMods/DeadlyBossMods#185]
Hello,

I get this all the time loading into dungeons.

1x DBM-Core\DBM-Core-8.3.21.lua:3971: script ran too long
[string "@DBM-Core\DBM-Core-8.3.21.lua"]:3971: in function `LoadMod'
[string "@DBM-Core\DBM-Core-8.3.21.lua"]:3917: in function `LoadModsOnDemand'
[string "@DBM-Core\DBM-Core-8.3.21.lua"]:3869: in function `func'
[string "@DBM-Core\DBM-Core-8.3.21.lua"]:1747: in function <DBM-Core\DBM-Core.lua:1738>

Locals:
self = <table> {
 CHAT_MSG_ADDON_LOGGED = <function> defined @DBM-Core\DBM-Core.lua:4998
 StopLogging = <function> defined @DBM-Core\DBM-Core.lua:6374
 FindScenarioIDs = <function> defined @DBM-Core\DBM-Core.lua:7222
 PLAY_MOVIE = <function> defined @DBM-Core\DBM-Core.lua:7271
 FindDungeonMapIDs = <function> defined @DBM-Core\DBM-Core.lua:7194
 GetUnitIdFromGUID = <function> defined @DBM-Core\DBM-Core.lua:3073
 CopyProfile = <function> defined @DBM-Core\DBM-Core.lua:1891
 CHAT_MSG_MONSTER_EMOTE = <function> defined @DBM-Core\DBM-Core.lua:5568
 CHAT_MSG_WHISPER = <function> defined @DBM-Core\DBM-Core.lua:6926
 SendPVPTimers = <function> defined @DBM-Core\DBM-Core.lua:6730
 DeleteProfile = <function> defined @DBM-Core\DBM-Core.lua:1908
 DungeonMusic = <table> {
 }
 ShowUpdateReminder = <function> defined @DBM-Core\DBM-Core.lua:5132
 PLAYER_REGEN_DISABLED = <function> defined @DBM-Core\DBM-Core.lua:5363
 FireEvent = <function> defined @DBM-Core\DBM-Core.lua:1548
 CreateModLocalization = <function> defined @DBM-Core\DBM-Core.lua:12027
 SCENARIO_COMPLETED = <function> defined @DBM-Core\DBM-Core.lua:3727
 IsEnabled = <function> defined @DBM-Core\DBM-Core.lua:7019
 GetMyPlayerInfo = <function> defined @DBM-Core\DBM-Core.lua:2934
 Capitalize = <function> defined @DBM-Core\DBM-Core.lua:7118
 ADDON_LOADED = <function> defined @DBM-Core\DBM-Core.lua:1271
 IconNumToTexture = <function> defined @DBM-Core\DBM-Core.lua:7188
 BattleMusic = <table> {
 }
 ShowRaidIDRequestResults = <function> defined @DBM-Core\DBM-Core.lua:4853
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @DBM-Core\DBM-Core.lua:2854
 GetBossUnitId = <function> defined @DBM-Core\DBM-Core.lua:3056
 AddDefaultOptions = <function> defined @DBM-Core\DBM-Core.lua:3121
 RegisterEvents = <function> defined @DBM-Core\DBM-Core.lua:948
 InfoFrame = <table> {
 }
 FilterRaidBossEmote = <function> defined @DBM-Core\DBM-Core.lua:1109
 RequestTimers = <function> defined @DBM-Core\DBM-Core.lua:6635
 RequestInstanceInfo = <function> defined @DBM-Core\DBM-Core.lua:4922
 CheckNearby = <function> defined @DBM-Core\DBM-Core.lua:3103
 CHAT_MSG_MONSTER_YELL = <function> defined @DBM-Core\DBM-Core.lua:5560
 LFG_PROPOSAL_SHOW = <function> defined @DBM-Core\DBM-Core.lua:3637
 ShowNoteEditor = <function> defined @DBM-Core\DBM-Core.lua:5282
 RegisterShortTermEvents = <function> defined @DBM-Core\DBM-Core.lua:1050
 LOADING_SCREEN_DISABLED = <function> defined @DBM-Core\DBM-Core.lua:3890
 GetUnitFullName = <function> defined @DBM-Core\DBM-Core.lua:2938
 UNIT_DIED = <function> defined @DBM-Core\DBM-Core.lua:6600
 ReceiveCombatInfo = <function> defined @DBM-Core\DBM-Core.lua:6663
 PLAYER_SPECIALIZATION_CHANGED = <function> defined @DBM-Core\DBM-Core.lua:3669
 RegisterCallback = <function> defined @DBM-Core\DBM-Core.lua:1563
 FindInstanceIDs = <function> defined @DBM-Core\DBM-Core.lua:7208
 UnregisterCallback = <function> defined @DBM-Core\DBM-Core.lua:1572
 RepositionFrames = <function> defined @DBM-Core\DBM-Core.lua:1931
 LFG_ROLE_CHECK_SHOW = <function> defined @DBM-Core\DBM-Core.lua:3628
 Disable = <function> defined @DBM-Core\DBM-Core.lua:7007
 ReceiveTimerInfo = <function> defined @DBM-Core\DBM-Core.lua:6672
 AddWarning = <function> defined @DBM-Core\DBM-Core.lua:8788
 RangeCheck = <table> {
 }
 BN_CHAT_MSG_AD

**Comment by MysticalOS** [comment]
That really should just not happen, blizzard gave addons massively long load time allowance for loading addons to prevent from script ran to long checks ages ago, even in combat.

I have to ask, but what are specs of machine? are they really low?

**Comment by DRYLOFFA** [comment]
Hello,

No not that low.
i5 8600K
16GB ram
GTX1070 GPU
m.2 SSD

**Comment by MysticalOS** [comment]
Don't have an explanation. It's not fixable though. You're only it's happening to so I have no idea why or how. No modifications or 3rd party DBM modules added in?

**Comment by DRYLOFFA** [comment]
No no mods and only DBM modules by MysticalOS install.

Guess ill just live with a slow load into dungeons.

Cheers

**Comment by MysticalOS** [comment]
script ran too long means it's not loading at all. the dungeon mod shouldn't take more than a couple seconds to load either.
