### ISSUE TITLE
Modules not loading on demand upon instancing.

### ISSUE THREAD

**Issue by Nadejha** [DeadlyBossMods/DeadlyBossMods#190]
Since the last update pushed to live (Shadowlands content update), I have been having issues with the individual modules not being loaded. I will enter a dungeon and the Dungeon (BfA) module won't load. Or I'll enter Ny'Alotha and not notice I have no timers or warnings until half way through Wrathion. I manually have to open Addon Control Panel and activate each module I need myself. 

Version: 8.3.21
WoW Version: 8.3.0.34220
OS: Windows 10 Pro 1909 (18363.836)
<details>
<summary>List of addons: (all updated to current live release)</summary>

Addon Control Panel
AdvancedInterfaceOptions
Altoholic
Angry Keystones
AzeritePowerWeights
Azeroth Auto Pilot
Coolline Cooldowns
Corruption Tooltips
Details! Damage Meter
ElvUI + AddonSkins
Pawn
Pitbull Unit Frames 4.0
Raider.IO
SimulationCraft
Titan Panel
WeakAuras 2
World Quest Tracker
</details>

**Comment by MysticalOS** [comment]
Nothing wrong in DBMs, end, whatever is causing this it's either a matter of module not being fully enabled (such as having a gray checkbox or none instead of gold indicating it's FULLY enabled on CURRENT character) or a conflict with an addon manager blocking load on demand.
