### ISSUE TITLE
r201904162 is considered older than r2019041517

### ISSUE THREAD

**Issue by serena-yu17** [DeadlyBossMods/DeadlyBossMods#2]
**Describe the bug**
I installed DBM r201904162, which is the latest version on the official website

**Do you have an error log of what happened?**
Upon starting the game, DBM reports "your version of DBM is out of date. Version 8.1.16 (r2019041517) is available to download. However in the /DBM window, it shows 8.1.16 (r201904162)

**To Reproduce**
Install r201904162, and join a party with members who have r2019041517.

**Screenshots**
![image](https://user-images.githubusercontent.com/12408446/56205926-75d49780-608e-11e9-8180-e67ee1fbfb25.png)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I have a minimal UI and I am sure the other addons are irrelevant.
 
**Which version of DeadlyBossMods are you using?**
Version 8.1.16 r201904162
**Was it working in a previous version? If yes, which was the last good one?**
Yes. It has to be r2019041517 to work.
**Additional context**
I think it is because 201904162 is mathematically smaller than 2019041517 due to one less digit.
Possible fix: 
DBM-Core.lua line 44: 
Revision = tonumber(string.sub("2019041620938", 1, -5)) 
to:
Revision = tonumber(string.sub("2019041620938", 1, -4)),

**Comment by MysticalOS** [comment]
Sadly -4 won't work, lua doesn't like math with those large of numbers, I just screwed up on r2019041517. it should have been r201904151

so I'm going to have to do a dirty fix now to not only fix it but ignore the bad versions continuing to trigger update notifications.

**Comment by MysticalOS** [comment]
Fixed in new published release (it'll take a while to show on other sites like curse)

**Comment by MysticalOS** [comment]
Not fixed yet, it's going to take a lot more work, which I don't have time for until after MANY hours of raiding, sadly. so i'll have to get to it later

**Comment by MysticalOS** [comment]
Problem has been identified and is more complicated than I thought

2019041620938
20190416140818

the date integer auto insert isn't putting a leading 0 on the 2 hour. so hour 14 build has a diff integer length. if this can't be fixed I'll have to overhaul the version system entirely
