### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by ppaatrik** [DeadlyBossMods/DeadlyBossMods#202]
**Twitch client installed classic/retail version on retail/classic**

**Describe the bug**

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**

20-05-25 | 1.13.45-48-g8d5484d-classic | Alpha | Installerad
-- | -- | -- | --

**

**

20-05-25 | 1.13.45-48-g8d5484d-classic | Alpha | Installerad
-- | -- | -- | --

**

**essage: Interface\AddOns\DBM-Core\DBM-Core-1.13.45-48-g8d5484d.lua:5583: attempt to index field 'WORLD_BUFFS' (a nil value)
Time: Mon May 25 12:15:23 2020
Count: 16
Stack: Interface\AddOns\DBM-Core\DBM-Core-1.13.45-48-g8d5484d.lua:5583: attempt to index field 'WORLD_BUFFS' (a nil value)

Locals: **

**Comment by QartemisT** [comment]
Being fixed by https://github.com/DeadlyBossMods/DBM-Classic/pull/155
