### ISSUE TITLE
[retail] lua error when typing /dbm and SpellTimers r119 is installed

### ISSUE THREAD

**Issue by brittyazel** [DeadlyBossMods/DeadlyBossMods#210]
Using the freshly released version of DBM, version 8.3.22 on retail WoW, when I type /dbm to load the GUI I get this LUA error:

```
2x DBM-GUI\DBM-GUI.lua:479: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@DBM-GUI\DBM-GUI.lua"]:479: in function <DBM-GUI\DBM-GUI.lua:463>
[string "@DBM-GUI\DBM-GUI.lua"]:1460: in function `UpdateModList'
[string "@DBM-GUI\DBM-GUI.lua"]:135: in function <DBM-GUI\DBM-GUI.lua:125>
[string "=(tail call)"]: ?
[string "@DBM-Core\DBM-Core-8.3.22.lua"]:2331: in function `?'
[string "@FrameXML\ChatFrame.lua"]:4859: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4523: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4559: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

```

**Comment by MysticalOS** [comment]
Did you in game update? or were you out of game when you updated?
This update has such significant changes that you cannot in-game update it and reload. game MUST be restarted.

Also, ALL sub modules need to be updated. if even a single one isn't, might get errors then too. This means if legion mods are installed, they need updating, etc.

**Comment by brittyazel** [comment]
I had the game closed when I updated. I rebooted the game client two or three times as well. I tracked down the source of the issue to Deadly BOss Mods (DBM) - SpellTimers, when that is installed the GUI is fully broken. Uninstalling it seems to have fixed the issues with the GUI loading

**Comment by MysticalOS** [comment]
That has an update too, does using that update also cause problems?

But if you don't need that mod then yes that's best solution.

**Comment by brittyazel** [comment]
Twitch shows that it had an update on 27/05/2020 and is on version r119, but the game version is still listed as 8.0.1. Is version r119 the correct version for SpellTimers? If so, then yes, r119 is the version I had installed and was the one causing me issues

**Comment by MysticalOS** [comment]
I checked, new version doesn't work either. I made a note of it and put out word

**Comment by brittyazel** [comment]
kk awesome. I'll keep it uninstalled for now, but I appreciate you looking into it

**Comment by MysticalOS** [comment]
Closing this and merging into Issue #204
