### ISSUE TITLE
[classic] bad argument #1 to 'mrandom' (interval is empty)

### ISSUE THREAD

**Issue by blotter** [DeadlyBossMods/DeadlyBossMods#211]
after fresh install of 1.13.46-classic

Message: Interface\AddOns\DBM-Core\DBM-Core.lua:4444: bad argument #1 to 'mrandom' (interval is empty)
Time: Wed May 27 19:53:21 2020
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:4444: bad argument #1 to 'mrandom' (interval is empty)
[C]: ?
[C]: ?
Interface\AddOns\DBM-Core\DBM-Core.lua:4444: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:4432>
(tail call): ?
Interface\AddOns\DBM-Core\DBM-Core.lua:4976: in function `handler'
Interface\AddOns\DBM-Core\DBM-Core.lua:843: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:830>

Locals:

**Comment by MysticalOS** [comment]
oh, are you guildless in classic? that code missed a very important check

**Comment by blotter** [comment]
no, i'm not guildless

**Comment by MysticalOS** [comment]
That's very odd then. how many guildies were online?

**Comment by MysticalOS** [comment]
Either way, i added redundant extra checks, whatever caused error, it should be fixed.
