### ISSUE TITLE
Check for active pull timer

### ISSUE THREAD

**Issue by Sqoops** [DeadlyBossMods/DeadlyBossMods#214]
Can you implement a function for outside addons to call if there currently is an active DBM pull timer?

**Comment by QartemisT** [comment]
Short answer: Ye
Long answer: Yes

**Comment by MysticalOS** [comment]
There already is one. any timer creations and stops have a callback.

**Comment by Sqoops** [comment]
Thank you. Unfortunately fireEvent for the pull timer is commented out in the classic version

`Line4245	--fireEvent("DBM_TimerStart", "pull", L.TIMER_PULL, timer, "132349", "utilitytimer", nil, 0)
`

**Comment by MysticalOS** [comment]
that's because it doesn't start there that was a duplicate event
