### ISSUE TITLE
DBM-RaidLeadTools

### ISSUE THREAD

**Issue by ItsNordstrom** [DeadlyBossMods/DeadlyBossMods#216]
Hi,

I installed the new update for dbm today, and I am getting some weird error that keeps spamming me. Not sure how to get it fixed. If anyone knows, please let me know. Would be great! :>

Here is a picture so you can see:
https://gyazo.com/3cde861c43fc0c09d2adeb49bab251e9

**Comment by QartemisT** [comment]
Do as the message says... Disable DBM-RaidLeadTools from your addon panel.

**Comment by ItsNordstrom** [comment]
Thanks! 
I guess there will be an addon update on it later :)
