### ISSUE TITLE
DBM-SpellTimers breaks DBM

### ISSUE THREAD

**Issue by Paragalla** [DeadlyBossMods/DeadlyBossMods#221]
DBM-Core-8.3.24-10-g77ffec2.zip

I loged in today and DBM wont work ... Just the warning from the titel .. 
Disablening SpellTimers => next error message

DBM-RaidLeadTool breaks DBM

Looking at  the AddOns in my AddOn List has a interesting thing to show

DBM Default Skin show a sice of 0kb and shows no information
all other addons do this ..

can u help me ?

**Comment by QartemisT** [comment]
Disable both DBM-SpellTimers and DBM-RaidLeadTools, as both have been discontinued.

https://twitter.com/deadlybossmods/status/1266867979465240581
