### ISSUE TITLE
DBM Fails due to RaidLeadTools problem

### ISSUE THREAD

**Issue by wieniec17** [DeadlyBossMods/DeadlyBossMods#227]
Hi guys,

Thanks for your awesome job with delivering the best addon for Wow in the world for so many years!

I have an issue. It started this morning without a reason..

When I log into the character, I get the following message:
<dBM> WARNING: DBM-RaidLeadTools is not compatible with this version of DBM. It must be removed before DBM can proceed, to avoid conflict

It stops my DBM from working completely.
It seems to work when I turn off the RaidLeadTools but I need those tools :)

Thanks for your support

**Comment by MysticalOS** [comment]
What do you need from those tools?
They are currently not compatible with DBM right now so they must stay disabled. This is likely not to change for a while, so I'm curious what feature it is you are using that I can help you find replacement for.

**Comment by wieniec17** [comment]
Hi,

I think it enabled the pull timer functionality. Judging by what you just
said, it seems I don't need it. Can I use the pull timer without
raidleadtools?

I may have had bunch of tools installed for years in my addon folder that
are no longer required.

**Comment by QartemisT** [comment]
Nope, they are all part of DBM-Core :)

**Comment by wieniec17** [comment]
Ok thanks. I need to do a clean up then 😁
