### ISSUE TITLE
Spelltimer error

### ISSUE THREAD

**Issue by morticianoire** [DeadlyBossMods/DeadlyBossMods#228]
*getting this error when logging on. checked dbm and its up to date version. and dbm tells me spelltimers are out of date
**Do you have an error log of what happened?**

1x DBM-SpellTimers\SpellTimers.lua:89: table index is nil
[string "@DBM-SpellTimers\SpellTimers.lua"]:89: in function <DBM-SpellTimers\SpellTimers.lua:84>
[string "@DBM-SpellTimers\SpellTimers.lua"]:309: in function <DBM-SpellTimers\SpellTimers.lua:290>

Locals:
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
}
(for control) = 3
k = 3
v = <table> {
 enabled = true
 spell = 6346
 cooldown = 180
 bartext = ""
}
(*temporary) = <table> {
 Aura Mastery = 2
 Guardian of Ancient Kings = 1
}
(*temporary) = nil
(*temporary) = <table> {
 CHAT_MSG_ADDON_LOGGED = <function> defined @DBM-Core\DBM-Core.lua:5065
 StopLogging = <function> defined @DBM-Core\DBM-Core.lua:6457
 FindScenarioIDs = <function> defined @DBM-Core\DBM-Core.lua:7301
 PLAY_MOVIE = <function> defined @DBM-Core\DBM-Core.lua:7350
 FindDungeonMapIDs = <function> defined @DBM-Core\DBM-Core.lua:7273
 GetUnitIdFromGUID = <function> defined @DBM-Core\DBM-Core.lua:3121
 CopyProfile = <function> defined @DBM-Core\DBM-Core.lua:1917
 CHAT_MSG_MONSTER_EMOTE = <function> defined @DBM-Core\DBM-Core.lua:5651
 CHAT_MSG_WHISPER = <function> defined @DBM-Core\DBM-Core.lua:7009
 SendPVPTimers = <function> defined @DBM-Core\DBM-Core.lua:6813
 DeleteProfile = <function> defined @DBM-Core\DBM-Core.lua:1934
 DungeonMusic = <table> {
 }
 ShowUpdateReminder = <function> defined @DBM-Core\DBM-Core.lua:5207
 PLAYER_REGEN_DISABLED = <function> defined @DBM-Core\DBM-Core.lua:5446
 FireEvent = <function> defined @DBM-Core\DBM-Core.lua:1574
 CreateModLocalization = <function> defined @DBM-Core\DBM-Core.lua:12111
 SCENARIO_COMPLETED = <function> defined @DBM-Core\DBM-Core.lua:3775
 IsEnabled = <function> defined @DBM-Core\DBM-Core.lua:7102
 GetMyPlayerInfo = <function> defined @DBM-Core\DBM-Core.lua:2982
 Capitalize = <function> defined @DBM-Core\DBM-Core.lua:7201
 ADDON_LOADED = <function> defined @DBM-Core\DBM-Core.lua:1282
 IconNumToTexture = <function> defined @DBM-Core\DBM-Core.lua:7267
 BattleMusic = <table> {
 }
 ShowRaidIDRequestResults = <function> defined @DBM-Core\DBM-Core.lua:4920
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @DBM-Core\DBM-Core.lua:2902
 GetBossUnitId = <function> defined @DBM-Core\DBM-Core.lua:3104
 AddDefaultOptions = <function> defined @DBM-Core\DBM-Core.lua:3169
 UPDATE_MOUSEOVER_UNIT = <function> defined @DBM-Core\DBM-Core.lua:4078
 InfoFrame = <table> {
 }
 FilterRaidBossEmote = <function> defined @DBM-Core\DBM-Core.lua:1120
 RequestTimers = <function> defined @DBM-Core\DBM-Core.lua:6718
 RequestInstanceInfo = <function> defined @DBM-Core\DBM-Core.lua:4989
 CheckNearby = <function> defined @DBM-Core\DBM-Core.lua:3151
 CHAT_MSG_MONSTER_YELL = <function> defined @DBM-Core\DBM-Core.lua:5643
 LFG_PROPOSAL_SHOW = <function> defined @DBM-Core\DBM-Core.lua:3685
 ReleaseRevision = 20200527120000
 RegisterShortTermEvents = <function> defined @DBM-Core\DBM-Core.lua:1061
 LOADING_SCREEN_DISABLED = <function> defined @DBM-Core\DBM-Core.lua:3938
 GetUnitFullName = <function> defined @DBM-Core\DBM-Core.lua:2986
 UNIT_DIED = <function> defined @DBM-Core\DBM-Core.lua:6683
 ReceiveCombatInfo = <function> defined @DBM-Core\DBM-Core.lua:6746
 PLAYER_SPECIALIZATION_CHANGED = <function> defined @DBM-Core\DBM-Core.lua:3717
 RegisterCallback = <function> defined @DBM-Core\DBM-Core.lua:1589
 FindInstanceIDs = <function> defined @DBM-Core\DBM-Core.lua:7287
 UnregisterCallback = <function> defined @DBM-Core\DBM-Core.lua:15
**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
Disable/Remove spelltimers, that message is notifying you it's no longer compatible and to disable it or update it (there is no update for it at this time so just disable it)

the clarity of message is improved in future version
