### ISSUE TITLE
Shadowlands Castle Nathria Support 

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DeadlyBossMods#236]
**Castle Nathria**
- Shriekwing
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Altimor the Huntsman
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Hungering Destroyer
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Artificer Xy'Mox
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Kael'thas (Sun King's Redemption)
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Lady Inerva Darkvein
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- The Council of Blood
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Sludgefist
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Stoneborne Generals
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod
  - [x] Encounter prepped for Mythic Testing with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties
- Sire Denathrius
  - [x] Mod created with loading, stats, and combat detection
  - [x] Mod drycoded with warnings/timers/feature
  - [x] Encounter tested with mod and drycode bugs squashed, post testing
  - [x] Encounter prepped for Mythic Progression (on live) with mythic specific mechanics
  - [x] Encounter re-tested with mod and mythic drycode bugs squashed, post testing
  - [x] Mod finished with real data from remaining difficulties

**Comment by MysticalOS** [comment]
All progress on generals was lost because blizzard scrapped original fight and redid it with less than 24 hours notice before the LAST time it's going to be tested. It's likely I'll fix it up best I can from tomorrows test data, but because the new mod likely won't ever get any testing before live, it's going to be in bad shape compared to other encounters. It's effectively going to be an untested drycode unless blizzard retests it on heroic and normal at a later time, which I hope they do to be fair to mod authors.

**Comment by MysticalOS** [comment]
Council mod reverted back to untested state since blizzard redid a ton of mechanics on fight so the mod is now back into drycode status and needs new timers/warning verification.

**Comment by beaucephus** [comment]
@MysticalOS Would you add a bar for Shriekwing's Wave of Blood cast?

**Comment by QartemisT** [comment]
MitälieToday at 13:26
DBM tries to set same markers on both Dimensional Tear targets on Artificer Xy'mox

**Comment by Xores** [comment]
DBM crashes on Council when Frieda casts Dreadbolt Volley

`Message: Interface\AddOns\DBM-Core\DBM-Core.lua:12390: attempt to index field 'findFastestComputer' (a nil value)
Time: Tue Dec 15 00:17:24 2020
Count: 7
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:12390: attempt to index field 'findFastestComputer' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:12390: in function `ScanForMobs'
[string "@Interface\AddOns\DBM-CastleNathria\TheCouncilofBlood.lua"]:409: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:896: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:883>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:896: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:883>

Locals: `

**Comment by MysticalOS** [comment]
That's already fixed in alpha.

**Comment by Xores** [comment]
true i was in a run when i posted it cheers

**Comment by thecontrarycat** [comment]
It seems that the Ember Blast spell on Sun King's Salvation needs another look.  While wowhead and earlier videos show the spell having a 5 second cast time, the currently live version casts in 3 seconds.  DBMs "Fading in 3 seconds" warning is therefore misleading.

**Comment by MysticalOS** [comment]
even on non mythic? It's annoying working with invalid spell data. I tried setting it to 3 on mythic and 5 on non mythic.

**Comment by thecontrarycat** [comment]
Yep, I've checked logs for Normal and Heroic and he's casting it in 3 seconds but DBM is expecting it to last 5 seconds.  Was very confusing!

**Comment by MysticalOS** [comment]
The 5 second spell data has to be coming from somewhere, I wonder if it remains that in LFR. but you confirmed already it's 3 sec on even normal?

**Comment by thecontrarycat** [comment]
Yes, confirmed as 3 seconds on Normal as well: https://www.warcraftlogs.com/reports/PwNYjcxtndpZfhgq#fight=21&type=casts&hostility=1&source=220&ability=325877&view=events

I checked LFR, and you are correct.  It's 5 seconds on LFR: https://www.warcraftlogs.com/reports/2LTwZRDaxJNBqcrG#fight=8&type=casts&hostility=1&source=106&ability=325877&view=events

**Comment by RedSkotina** [comment]
How i can change [dark recital](https://www.wowhead.com/spell=331634/dark-recital) marks? They are both yellow and it is mess me.
Can i change it at my personal computer or we need global change?

**Comment by MysticalOS** [comment]
the aren't actually marked with raid icons, just chat bubbles that show your pair. You can't change this because they are universal otherwise it wouldn't actually show your pair. pair 1 is star pair 2 is circle, etc.
