### ISSUE TITLE
DBM-RaidLeadTools

### ISSUE THREAD

**Issue by Ravenouschaos** [DeadlyBossMods/DeadlyBossMods#237]
**Twitch client installed classic/retail version on retail/classic**
Twitch client installed
Retail wow up to date
8.3.24 version of dbm installed and up to date

**Describe the bug**
DBM is not loading. Upon loading into the game i get the following message: "WARNING: DBM-RaidLeadTools is not compatible with this version of DBM. It must be removed before DBM can proceed, to avoid conflict." (screenshot attached)

**Do you have an error log of what happened?**
I do not

**To Reproduce**
<!-- Steps to reproduce the behavior:
1. Log in
2. (immediate error on log in)
3. (Identical error when typing /dbm in game

**Screenshots**
![DMB error](https://user-images.githubusercontent.com/66386479/83681361-ea76d800-a5a7-11ea-97be-0322eeb8d6d1.PNG)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?**
8.3.24

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
No need for screen shot or report. Just do what it says, disable or remove RaidleadTools and dbm will work.

**Comment by Ravenouschaos** [comment]
Sorry, should have specified that I do not have RaidLeadTools installed, nor have I ever. Triple checked in game and in twitch.
