### ISSUE TITLE
My classic files updating to retail.

### ISSUE THREAD

**Issue by saveandaid** [DeadlyBossMods/DeadlyBossMods#242]
Hi,

When using the twitch mob manager it suggest that i update my classic addons to the retail version. I know this problem might mainly be with twitch/curseforge but if there is anything you can do in your end to solve this, it would be awesome as they seem to be either compliant or unable to fix the problem. 

Let me know if there is any additional information i can provide to help.

**Comment by MysticalOS** [comment]
Trust me we've complained plenty, and they swore the last time it was fixed that time, guess not. not much can do about this on our end.
