### ISSUE TITLE
Twitch update for DBM downloads BfA version when on Classic channel

### ISSUE THREAD

**Issue by jayesquire** [DeadlyBossMods/DeadlyBossMods#25]
Twitch addons now has a selector for _retail_ or _classic_ World of Warcraft installation. When the _classic_ selection is chosen, Twitch update for DBM downloads the _retail_ version instead. The end user then gets the improper version message upon login to the game and has to manually correct.
![dbm_classic_indicated_but_downloads_retail](https://user-images.githubusercontent.com/51282518/59970072-77f22100-952b-11e9-83bd-be8e635de92f.png)

**Comment by MysticalOS** [comment]
Nothing I can do on my end. you'll have to open a ticket with twitch about that.

**Comment by Stanzilla** [comment]
That is not a bug, the Deadly Boss Mods main package is not what you install on retail, you need DBM Classic

**Comment by MysticalOS** [comment]
Actually i was able to get mac client to see classic version of game and definitely see same bug, but yeah I still can't do anything about it. Twitch has to fix this.
