### ISSUE TITLE
Bug when doing Blast Furnace boss in Blackrock Foundry Mythic

### ISSUE THREAD

**Issue by brittyazel** [DeadlyBossMods/DeadlyBossMods#257]
4x DBM-Core\DBM-Core-8.3.26.lua:9920: attempt to compare nil with number
[string "@DBM-Core\DBM-Core-8.3.26.lua"]:9920: in function `Play'
[string "@DBM-BlackrockFoundry\BlastFurnace.lua"]:573: in function `handler'
[string "@DBM-Core\DBM-Core-8.3.26.lua"]:845: in function <DBM-Core\DBM-Core.lua:832>
[string "=(tail call)"]: ?
[string "@DBM-Core\DBM-Core-8.3.26.lua"]:845: in function <DBM-Core\DBM-Core.lua:832>

Locals:
Skipped (In Encounter)****

**Comment by MysticalOS** [comment]
Pushed a fix for this, thanks
