### ISSUE TITLE
INFO FRAME WILL NOT STAY HIDDEN.

### ISSUE THREAD

**Issue by OdessaGrimaldus** [DeadlyBossMods/DeadlyBossMods#263]
**Twitch client installed classic/retail version on retail/classic**
Retail WoW

**Describe the bug**
On all characters, all with Info Frame disabled..I still get this frame appearing. All are using the same profile for DBM and nothing changes despite it is even right there in the options disabled..it still appears.

**Do you have an error log of what happened?**
I do not have an error log.

**To Reproduce**
There is nothing I can say to reproduce it, it is rather simply done.

**Screenshots**
There is no screenshots, as they would just be showing the frame there on the screen as if enabled, nothing more.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?
I tried it with only DBM active and this does nothing to remedy the issue.

**Which version of DeadlyBossMods are you using?**
v202006300600  - And this issue has been something I've experienced for the past several months.

**Was it working in a previous version? If yes, which was the last good one?**
I cannot say I remember.

**Additional context**

**Comment by QartemisT** [comment]
Is this popping up for ALL bosses that have infoframes, or have you noticed certain ones not show it, or certain ones showing it?

**Comment by OdessaGrimaldus** [comment]
> Is this popping up for ALL bosses that have infoframes, or have you noticed certain ones not show it, or certain ones showing it?

All bosses, yes, nomatter which character I am on. I can for example go do Maut or N'Zoth and I will have this frame appear for one character, disable it, next time I come in with the character it is there again, or if I bring in another character entirely it will appear again.

This is ofcourse as stated while I am using the same single profile for DBM across all characters.

**Comment by QartemisT** [comment]
Do you have "Do not show info frame" enabled in the "Spam" section of `/dbm` ?

**Comment by MysticalOS** [comment]
if you disable it at mod level, it's only disabled on THAT character and spec. if you disable it in core, it's disabled globally. i suspect you turn it off at mod level, which only applies to current char-spec which means diff character or even same char with diff spec it's on again. mod options are per spec. Also if intent is to globally disable a feature, doing it at mod level is incorrect way to do it.

Refer to:
https://github.com/DeadlyBossMods/DeadlyBossMods/wiki/%5BGuide%5D-DBM-Global-Filter-Options

**Comment by QartemisT** [comment]
Also, I presume what you're doing is right clicking and selecting "hide", which would only hide it for the current session. Hence why it's re-appearing on relog.

**Comment by OdessaGrimaldus** [comment]
I have it disabled in the Misc Global Disable & Filter Options.

This has been where its been turned off the entire time and still these info pop-ups appear. There is no actual information to them or anything but it has the resource of the fight's name and a small square under the word..thats all that appears and its just well..there.
![WoWScrnShot_070220_013038](https://user-images.githubusercontent.com/67622191/86320047-f3d57d80-bc03-11ea-8175-bcaf8b3ffa6a.jpg)

**Comment by OdessaGrimaldus** [comment]
What do you mean by sub functions?

**Comment by QartemisT** [comment]
Oh comit message doesn't matter, its just something so Myst understands whats happening easier.

**Comment by OdessaGrimaldus** [comment]
> Oh comit message doesn't matter, its just something so Myst understands whats happening easier.

Gotcha. ..Also, I have just gone and checked with having the info frame display set to off..it does indeed still show these info frames for bosses upon entering combat..and going into further investigation of the boss fight specific mechanic timers and whatnot..that at their very bottom there is "show info frame for Obsidian skin" for example on Maut..it is checked as enabled, even with them all disabled by the global option as I have show above..but if I disable it here from each boss one by one, it doesn't seem to return.

So long and short of it..turning each off manually keeps them gone, but the global disable for them is doing nothing.

**Comment by QartemisT** [comment]
Yeh its due to the fact the frame is still being crated, but just not updated/populated. Those frame creations now actually respect the disable option :)

**Comment by OdessaGrimaldus** [comment]
> Yeh its due to the fact the frame is still being crated, but just not updated/populated. Those frame creations now actually respect the disable option :)

Well..let us hope that this solves the problem and keeps it from creating this supposedly disabled frames
