### ISSUE TITLE
DBM Boss Settings Keep Resetting.

### ISSUE THREAD

**Issue by OdessaGrimaldus** [DeadlyBossMods/DeadlyBossMods#269]
Twitch client installed classic/retail version on retail/classic:
Retail WoW

Describe the bug:
On all characters, all with Info Frame disabled globally..I still get this frame appearing. I tried going in and singularly disabling the info and ranged frames on every single boss fight..as soon as I change characters they are all back on for both that new character and previous I disabled them on. All characters are using the same profile for DBM and nothing changes despite it is even right there in the options disabled..it still appears.

I have tried making a new profile and doing these tactics with it to see if the problem persists, aswell as made multiple profiles each for every character individually, and disabled all these settings, saved the profiles..and as soon as I log off and back in all of them are enabled again.

Do you have an error log of what happened?:
I do not have an error log.

To Reproduce:
There is nothing I can say to reproduce it, it is rather simply done.

Screenshots:
There is no screenshots, as they would just be showing the frame there on the screen as if enabled, nothing more.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?:
I tried it with only DBM active and this does nothing to remedy the issue.

Which version of DeadlyBossMods are you using?:
8.3.26-43-gb702f9c - And this issue has been something I've experienced for the past several months.

Was it working in a previous version? If yes, which was the last good one?:
I cannot say I remember.

**Comment by MysticalOS** [comment]
Infoframe issue is fixed in alpha, NOT current release, don't open another ticket on it, just wait for a new release

can't do anything about twitch client installing wrong stuff. at this point twitch has given up on their client and we'll have to wait for overwolf client and hope it works better

**Comment by OdessaGrimaldus** [comment]
> Infoframe issue is fixed in alpha, NOT current release, don't open another ticket on it, just wait for a new release
> 
> can't do anything about twitch client installing wrong stuff. at this point twitch has given up on their client and we'll have to wait for overwolf client and hope it works better

Thank you very much for this Mystic. I am glad to hear it has been addressed and is not just a unique issue that only I was experiencing. I appreciate the reply.
