### ISSUE TITLE
Some count voices are broken in BoD

### ISSUE THREAD

**Issue by Elnarfim** [DeadlyBossMods/DeadlyBossMods#27]
**Describe the bug**

Some count voices are broken. Maybe mekka and baricades

**Which version of DeadlyBossMods are you using?**
8.1.26-72-ga49cd6257-alpha

**Was it working in a previous version? If yes, which was the last good one?**
Yes. 8.1.26.67 alpha

**Comment by MysticalOS** [comment]
Can you be more specific? you know what's not working? just not hearing countdowns? that's literally only playsoundfile i did NOT change in last few days, not sure how that would have broken, at least recently. You sure it worked recently and didn't break longer ago?

**Comment by Elnarfim** [comment]
I didn't adjust any options. Just can't hear some countdowns. I guess Wormhole. I'll check this again today

**Comment by MysticalOS** [comment]
That definitely wouldn't be broken. Wormhole has nothing special about it. Remember too that if you play with SFX on, sound clipping/muting is still a thing. blizzard no longer prioritizes addon sounds over other sounds period. if you hit channel limit, addon sounds are just as hit or miss as any other. https://www.patreon.com/posts/addon-sound-work-16575915 is still 100% true with same work arounds still being valid. 128 sound channels best one if you want to keep sound effects channel.

**Comment by Elnarfim** [comment]
I've checked countdown for wormhole and everything's ok. I confused something
