### ISSUE TITLE
N'Zoth Glare

### ISSUE THREAD

**Issue by Nicthalon** [DeadlyBossMods/DeadlyBossMods#272]
When N'Zoth does his glare during P3 of the fight, the Glare direction posted by DBM is almost never accurate. It seems to think we always go right on the first glare, and when it's left instead, DBM announcement still says right. Second Glare always says left, regardless of the actual direction.

**Comment by MysticalOS** [comment]
It tells you which direction beam is going, not what direction YOU should go. if it says beam is going right it means YOU need to be left of it

**Comment by Nicthalon** [comment]
uhh, no. it says right, and the beam goes left, and we have to go left to
not get hit by it.

**Comment by MysticalOS** [comment]
Never seen that. what difficulty? it's always been correct on mythic and LFR, I assumed normal/heroic would use same directions as LFR, if that's not case I'll just kill feature on those difficulties and call it a day

**Comment by Nicthalon** [comment]
Heroic. Here's a link to our kill last Friday. At about 1:07:55 you can see
it announce Glare:Right and the beams are following us to the left.
https://www.twitch.tv/videos/666442806
