### ISSUE TITLE
InfoFrame Broken

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DeadlyBossMods#287]
![LOL](https://media.discordapp.net/attachments/419696269456572416/741391362439643277/Screen_Shot_2020-08-07_at_4.24.19_PM.jpg)

Settings: Rows suggested by mod, Columns suggested by mod.
Boss: Hungering Destroyer

Replicatable by visions: https://twitter.com/FuxieDK/status/1292475524300910592
![LOL](https://pbs.twimg.com/media/Ee_Ld8kXsAQzHPH?format=jpg&name=small)

**Comment by QartemisT** [comment]
Did you select to show more than 1 column in the right click menu? :P

**Comment by MysticalOS** [comment]
Changing it in menu doesn't work either, throws this error

2x DBM-Core\DBM-InfoFrame.lua:933: attempt to index field '?' (a nil value)
[string "@DBM-Core\DBM-InfoFrame.lua"]:933: in function <DBM-Core\DBM-InfoFrame.lua:821>
[string "@DBM-Core\DBM-InfoFrame.lua"]:1009: in function `Show'
[string "DBM.InfoFrame:Show(25, "test2")"]:1: in main chunk
[string "=[C]"]: in function `RunScript'
[string "@FrameXML\ChatFrame.lua"]:2177: in function `?'
[string "@FrameXML\ChatFrame.lua"]:4859: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4523: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4559: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
