### ISSUE TITLE
Playsoundfile error on Ivus

### ISSUE THREAD

**Issue by Elnarfim** [DeadlyBossMods/DeadlyBossMods#29]
**Describe the bug**

**Do you have an error log of what happened?**

2x DBM-Core\DBM-Core-8.2.1-5-gf3d0b691f.lua:6567: PlaySoundFile Error - Invalid fileDataID for sound.
[C]: ?
DBM-Core\DBM-Core-8.2.1-5-gf3d0b691f.lua:6567: in function <DBM-Core\DBM-Core.lua:6546>
DBM-Core\DBM-Core-8.2.1-5-gf3d0b691f.lua:6576: in function `PlaySoundFile'
DBM-Core\DBM-Core-8.2.1-5-gf3d0b691f.lua:9082: in function `Play'
DBM-Azeroth-BfA\Ivus.lua:96: in function `handler'
DBM-Core\DBM-Core-8.2.1-5-gf3d0b691f.lua:753: in function <DBM-Core\DBM-Core.lua:740>
(tail call): ?
DBM-Core\DBM-Core-8.2.1-5-gf3d0b691f.lua:753: in function <DBM-Core\DBM-Core.lua:740>

Locals:
InCombatSkipped
**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by agjs** [comment]
Getting the similar or the same error.

```
Message: Interface\AddOns\DBM-Core\DBM-Core.lua:6416: PlaySoundFile Error - Invalid fileDataID for sound.
Time: Tue Sep 10 20:43:07 2019
Count: 4
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:6416: PlaySoundFile Error - Invalid fileDataID for sound.
[C]: ?
Interface\AddOns\DBM-Core\DBM-Core.lua:6416: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:6394>
Interface\AddOns\DBM-Core\DBM-Core.lua:6428: in function `PlaySoundFile'
Interface\AddOns\DBM-Core\DBM-Core.lua:9974: in function `PlaySpecialWarningSound'
Interface\AddOns\DBM-Core\DBM-Core.lua:9574: in function `func'
Interface\AddOns\DBM-Core\DBM-Core.lua:1700: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:1691>

Locals: (*temporary) = "Interface\AddOns\DBM-Core\sounds\ClassicSupport\UR_Algalon_BHole01.ogg"
(*temporary) = "Dialog"
```

**Comment by MysticalOS** [comment]
Grab latest version, probably same cause

**Comment by agjs** [comment]
I'm on the latest version, updated using Twitch tool.

**Comment by MysticalOS** [comment]
and it didn't auto correct that? i literally added code to that version and tagged a release just to auto correct the damage twitch client caused when it installed DBM-Classic on retail clients. :\

**Comment by MysticalOS** [comment]
Ok I found the problem, I'm just going to do another release to get the real fix out.

**Comment by agjs** [comment]
Awesome, I guess its 8.2.18, will update to that :-). Cheers
