### ISSUE TITLE
DBM Broken after update on 10.8.2020

### ISSUE THREAD

**Issue by Vazygos** [DeadlyBossMods/DeadlyBossMods#292]
Hello!

An update sprung up on my curseforge app to update the addon for wow classic. Since the update the addon keeps telling me it's not the correct version of the game I am playing. It appears a retail version was pushed to classic wow. 

I'm thankful for your
![WoWScrnShot_081020_202135](https://user-images.githubusercontent.com/69479438/89816837-88a69180-db47-11ea-8f55-829ada82dc11.jpg)
 assisstance.

**Comment by Chianah** [comment]
I'm also having this problem. Chianah Mythrael

**Comment by QartemisT** [comment]
Please go into Twitch, and make sure you have the CLASSIC version installed. The file will end with "-classic".

This is an issue with Twitch, and not something we can resolve.

**Comment by Chianah** [comment]
Yes, I know. I was still getting the error so I uninstalled it. Hoping to re-install without error.

**Comment by MysticalOS** [comment]
Twitch client appears to have broken earlier today, and gave several users out of date addons/incorrect ones.

this goes back to what I always tell users. Make sure twitch client isn't messing it up. look at game version, look at file version, if something looks off (such as version being 8.3.x but it should be for classic). It seems resolved for now but yes always keep an eye on twitch client

**Comment by Chianah** [comment]
Ahhh. I see. Thanks for that info. Guess I really do tend to think of Twitch as being "uninvolved". Thanks again.
