### ISSUE TITLE
Sounds turned off getting chatframe error of missing soundfile

### ISSUE THREAD

**Issue by Anothersignup** [DeadlyBossMods/DeadlyBossMods#31]
**Describe the bug**
Turned off all sounds. Got same error message in chatlog many times.
Was running DBM for the first time, in Gnomeregan 5-man dungeon.

**Do you have an error log of what happened?**
Here is the first line of the error, I don't have the rest:
"Playsoundfile failed do to missing media at." Yes, with bad English.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of DeadlyBossMods are you using?**
Downloaded it today.

**Was it working in a previous version? If yes, which was the last good one?**
I don't think I have run the mod with sounds turned off before.

After I started WoW again:
![Untitled](https://user-images.githubusercontent.com/44720447/60754407-c5b56180-9fe0-11e9-8849-9e2587762fa9.jpg)

**Comment by MysticalOS** [comment]
This is already fixed in next version, I've just had trouble finishing up a few things and tagging a new release because I keep losing power when trying to work on things. I hope to finish things up tonight and get release out so this issue doesn't affect users when new content starts.
