### ISSUE TITLE
Good afternoon, I want to make a pull button in my addon, is there a way to call a function from your addon?

### ISSUE THREAD

**Issue by DygDyg** [DeadlyBossMods/DeadlyBossMods#316]
Good afternoon, I want to make a pull button in my addon, is there a way to call a function from your addon?

**Comment by QartemisT** [comment]
Can always do this;

`SendAddonMessage("D4", "PT\t" .. pullTime .. "\t" .. instanceMapID)`

Where pullTime is the time in seconds, and instanceMapID is the instance ID

See here for detailed information about instanceID's: https://wow.gamepedia.com/InstanceID

**Comment by MysticalOS** [comment]
Be aware that DBM will ignore pull sync from players not permitted to send them though (not assist/leader) Locally DBM prevents sending those syncs as well but has protections in place to ensure other addons that don't have those protections are ignored if user doesn't have appropriate permission

**Comment by DygDyg** [comment]
/script SendAddonMessage("D4", "PT\t" .. 10)

I tried using the chat, but it gives an error. I'm new to writing Addons, what am I doing wrong?

``Message: [string "SendAddonMessage("D4", "PT\t" .. 10)"]:1: attempt to call global 'SendAddonMessage' (a nil value)``

**Comment by QartemisT** [comment]
Apologies;

`C_ChatInfo.SendAddonMessage("D4", "PT\t" .. 10, "RAID")`
