### ISSUE TITLE
Bar font issue

### ISSUE THREAD

**Issue by Matthieusch** [DeadlyBossMods/DeadlyBossMods#348]
Hi and thank you for this amazing addon!

I've one issue with font option for bars: font looks awful, very pixelated and even if i changed it with de dropdown menu it'll not change anything. After a complete reinstall I saw a font on the bars, not the one I wanted but not the ugly one. To start my settings I've changed the bar texture and then... the ugly font was back again and I can't change it.

I guess you'll need more informations which I could provide, just tell me where to look!

Bests regards,
Matthieu

**Comment by MysticalOS** [comment]
If it's not changing when you change it in DBM options, it's being overrided by something like AddonSkins, and you have to change the font in addonskin options instead.

**Comment by Matthieusch** [comment]
@MysticalOS Yes! AddonSkins was the problem! Thank you.
