### ISSUE TITLE
Mythic Jaina timers

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DeadlyBossMods#354]
**Describe the bug**
Timers are off:
- [x] Howling Winds dbe84988230a8881b10adb38d5be33565f22ee28
- [ ] Grasp of Frost

**Do you have an error log of what happened?**
Howling Winds in the first pull and Grasp of Frost in the second.
https://gist.github.com/Molkree/a5f93b3c12b795b2a158aee239522825

**Screenshots**
![image](https://user-images.githubusercontent.com/12860284/94321733-24297f80-ff99-11ea-919d-a060639e1295.png)
![image](https://user-images.githubusercontent.com/12860284/94321739-2ab7f700-ff99-11ea-9967-852d0b69f38e.png)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of DeadlyBossMods are you using?**
Latest alpha at the time of fight.

**Was it working in a previous version? If yes, which was the last good one?**
No idea.

**Comment by MysticalOS** [comment]
have a theory on what caused fails timer report for frost so fixed that. Grasp doesn't have enough information so it remains unchanged. Grasp isn't a count timer so I can't see which grasp is wrong without previous events in shot
