### ISSUE TITLE
Group Interrupt tracker/bars

### ISSUE THREAD

**Issue by Tollingbell** [DeadlyBossMods/DeadlyBossMods#360]
**Is your feature request related to a problem? Please describe.**
It's not a problem more of a QoL improvement. Previous versions you could pull individual bars where u wanted on your ui. One of the more recent updates takes all the timers and puts them in a block and the drag me moves the entire block not just one bar. I currently use a plugin that tracks interrupts and it worked great and i had interrupts off to one side so they didn't get stuck with all the other timers but i recently clean installed wow/addons and i can't pull the interrupt tracker bars out any longer nor more any timers for that matter other then the whole "box". I really enjoy the addon either way and it's been great. Just those couple of QoL things if possible would be great

**Describe the solution you'd like**
If possible take the interrupt tracker and bake it into base dbm? I''m not familiar with that would entail but i think it would be great and the ability to move individual timer bars again rather then moving just the timer "box"
https://imgur.com/a/OjZoFIC SS of the box and drag me just moves the whole thing

**Describe alternatives you've considered**

**Additional context**

**Comment by MysticalOS** [comment]
I have made no changes that'd affect any behaviors. if changes were made they were made in 3rd party Interrupts plugin which I have no control over it.

DBM only has two bar anchors. Small and large/huge. It has never supported a feature where different bars could be dragged out of the anchors. Maybe one day DBM can add support for a 3rd anchor for plugins like spell timers and 3rd party ones like interrupts, but that's a very long off stretch goal. I do not predict this happening any time soon.

**Comment by QartemisT** [comment]
Closing issue as is now on my tracking list :)
