### ISSUE TITLE
Map won't switch from default area

### ISSUE THREAD

**Issue by Chyvalri** [DeadlyBossMods/DeadlyBossMods#371]
**Describe the bug**
Regardless of what area I enter, while DBM is active, the map will not change from Kul Tiras without manual intervention.
When I turn off DBM, when I go to Zandalar, the map of Zandalar loads when I press 'M'. Otherwise, it stays on Kul Tiras until I right click back one level then click manually on Zandalar.

**Do you have an error log of what happened?**
1/2
Message: ...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:831: CreateFrame(): Couldn't find inherited node "MicroButtonAlertTemplate"
Time: Mon Oct 19 20:49:41 2020
Count: 3
Stack: ...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:831: CreateFrame(): Couldn't find inherited node "MicroButtonAlertTemplate"
[string "=[C]"]: in function `CreateFrame'
[string "@Interface\AddOns\WorldQuestTracker\WorldQuestTracker.lua"]:831: in function <...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:827>

Locals: (*temporary) = "frame"
(*temporary) = "WorldQuestTrackerTutorialAlert1"
(*temporary) = WorldQuestTrackerWorldMapPOI {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface\SharedXML\Backdrop.lua:205
 GetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:443
 SetupTextureCoordinates = <function> defined @Interface\SharedXML\Backdrop.lua:267
 OnBackdropSizeChanged = <function> defined @Interface\SharedXML\Backdrop.lua:235
 HasBackdropInfo = <function> defined @Interface\SharedXML\Backdrop.lua:331
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:475
 GetEdgeSize = <function> defined @Interface\SharedXML\Backdrop.lua:241
 fadeInAnimation = <unnamed> {
 }
 ApplyBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:382
 ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:335
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:400
 SetupPieceVisuals = <function> defined @Interface\SharedXML\Backdrop.lua:299
 SetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:452
 mouseoverHighlight = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @Interface\SharedXML\Backdrop.lua:319
}
(*temporary) = "MicroButtonAlertTemplate"

2/2
Message: ...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:652: attempt to index local 'tagInfo' (a nil value)
Time: Mon Oct 19 20:42:35 2020
Count: 1
Stack: ...rface\AddOns\WorldQuestTracker\WorldQuestTracker.lua:652: attempt to index local 'tagInfo' (a nil value)
[string "@Interface\AddOns\WorldQuestTracker\WorldQuestTracker.lua"]:652: in function `GetQuest_Info'
[string "@Interface\AddOns\WorldQuestTracker\WorldQuestTracker_WorldMap.lua"]:1328: in function `UpdateWorldQuestsOnWorldMap'
[string "@Interface\AddOns\WorldQuestTracker\WorldQuestTracker_WorldMap.lua"]:1188: in function <...Ons\WorldQuestTracker\WorldQuestTracker_WorldMap.lua:1185>
[string "@Interface\SharedXML\C_TimerAugment.lua"]:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals: questID = 56328
title = "Do Not Drink"
factionID = 2391
tagInfo = nil
(*temporary) = nil
(*temporary) = 56328
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'tagInfo' (a nil value)"
HaveQuestData = <function> defined =[C]:-1
GetQuestInfoByQuestID = <function> defined =[C]:-1

**To Reproduce**
1. While in any zone (example, Stormwind, Boralus, anywhere I can), while playing as alliance in this case, press M.

**Screenshots**
I can get them if required.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, I tested it with all of my add-ons. It only happens when using both DBM and WorldQuestTracker.

**Which version of DeadlyBossMods are you using?**
DBM-Core-9.0.1.zip

**Was it working in a previous version? If yes, which was the last good one?**

Last time was before Shadowlands Pre-patch to my knowledge.

**Additional context**

**Comment by MysticalOS** [comment]
Nothing to do with DBM, closing issue. I recommend passing issue onto World Quest Tracker
