### ISSUE TITLE
5 min timer

### ISSUE THREAD

**Issue by meia120** [DeadlyBossMods/DeadlyBossMods#374]
Every time someone sets a pull timer of 5, 10, 15 etc. seconds, or every time I start a mythic plus dungeon, a 5 minute timer will appear at the top of my screen and will countdown in huge numbers when it gets to 100 seconds. Please tell me how to turn this off as it's very annoying and never used to do this! 

Thanks

**Comment by MysticalOS** [comment]
https://github.com/DeadlyBossMods/DeadlyBossMods/issues/372

**Comment by meia120** [comment]
Thanks so much!
