### ISSUE TITLE
Problems with countdown pull

### ISSUE THREAD

**Issue by Rinkyhober** [DeadlyBossMods/DeadlyBossMods#380]
Dbm pull doesn't show countdown, doesn't show count numbers, just sound.

**Comment by MysticalOS** [comment]
the timer should still show, the numbered countdown has been removed from now because blizzard broke it and I'm waiting for blizzard to fix it before enabling it again.

**Comment by eightflat** [comment]
Pardon the piggy backing of this comment, but is this related to any experiences with the timer being off? It seems like the "gates" open around 2-3 for events like the start of M+, BG, and arena.

**Comment by MysticalOS** [comment]
Are they still off in 9.0.2? because if so then I can't re-addd feature back into DBM

**Comment by eightflat** [comment]
I believe, yes. I was doing M+, BG, and arena all this week and noticed the timer discrepancy each time.
