### ISSUE TITLE
An error message Frame (어둠땅) already exists

### ISSUE THREAD

**Issue by Elnarfim** [DeadlyBossMods/DeadlyBossMods#383]
**Describe the bug**
When the gui window opens it occurs. I think it is related to ## X-DBM-Mod-Category in DBM-Shadowlands toc

There are two 'SHADOWLANDS' (어둠땅 in Korean) now

**Comment by MysticalOS** [comment]
I don't see any duplication anywhere in current code. the toc for shadowlands looks fine, only one 어둠땅 entry. only other place 어둠땅 exists is in shadowlands party, but it's 던전 (어둠땅) which isn't the same thing.
Also can't reproduce frame error. If you can post screen shot of it

**Comment by QartemisT** [comment]
Resolved as of latest GUI commit in alpha.
