### ISSUE TITLE
Displacement of bars

### ISSUE THREAD

**Issue by masterjokr** [DeadlyBossMods/DeadlyBossMods#387]
Hello
( I use google translation )
I have a problem when I want to move the announcement bar. I click on "Move me" and I cannot move anything.
I can see the bars appear to move them and whatever I do I can't do anything.
I disabled all my addons, to see if it's not one of them that is causing me trouble, but it's still the same.
I'm using the latest version available on Twitch

Sorry for the inconvenience

**Comment by QartemisT** [comment]
Use `/dbm move` for the time being, till I resolve this inside of GUI :)

**Comment by masterjokr** [comment]
Work fine ! Thanks a lot
