### ISSUE TITLE
LUA ERROR ON LATEST BUILD 

### ISSUE THREAD

**Issue by Wyr3d** [DeadlyBossMods/DeadlyBossMods#388]
Just updated to the latest version of DBM. Looked fine at first, but hearthing to the Garrison (fast travel) it popped up with the following lua error:

Message: Interface\AddOns\DBM-Core\DBM-Core.lua:3409: bad argument #1 to 'ipairs' (table expected, got nil)
Time: Wed Nov 18 17:48:25 2020
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:3409: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:3409: in function `LoadModOptions'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4280: in function `LoadMod'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4213: in function `LoadModsOnDemand'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4151: in function `func'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:1837: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:1828>

**Comment by Wyr3d** [comment]
Also this one:

Message: Couldn't open Interface\AddOns\DBM-GarrisonInvasions\DBM-GarrisonInvasions.toc
Time: Wed Nov 18 17:48:25 2020
Count: 2

**Comment by MysticalOS** [comment]
what exactly did you use to update your addons?

**Comment by Wyr3d** [comment]
The new Curse on Wolf

**Comment by MysticalOS** [comment]
I can't find any reason this error would occur if you havae DBM 9.0.4 as well as updated all old sub packages too.

Updating DBM-WoD mods would have automatically removed DBM-GarrisonInvasions, but even if it hadn't, if you had DBM 9.0.4 DBM-GarrisonInvasions should have been ignored and not attempted to load it in first place, so soemthing odd is going on.

**Comment by Wyr3d** [comment]
I'm gonna put it down to an Overwolf glitch. I force reinstalled it for now. and will see if it happens again
