### ISSUE TITLE
Missing files after 9.0.4 update

### ISSUE THREAD

**Issue by LinXhi** [DeadlyBossMods/DeadlyBossMods#389]
I always have all my addon updated before I launch the game and today after I update everything and play the game, I join Ny'alotha raid but somehow my DBM isnt appear when the encounter starts, I thought it just bug so I reload UI and continue to second boss and when encounter starts DBM still not appear/active

So after it I close the game and reinstall the addon, I tried both ways via Twitch and CurseForge app and check them 1 by 1 but nothing works, so I went through my files and then I realize the files for Ny'alotha and BFA party are missing

I tried to delete the addon via app and install it again but its not working, so I after know which files Im missing, I manually download it from the website and add it to my addons folder

And because Im still curious what happened, I try to update it again from both twitch app and curseforge while I having my addon folder window up in the background and yes, so after I update it the files just disappear again

Please help me if theres anything I did wrong, thank you

DBM 9.0.4 ( 18 nov 2020 )

**Comment by Tetsemi** [comment]
Does this announcement help at all?

DBM 9.0.4 Released for Retail wow for patch 9.0.2.

Very important if you are still raiding bfa this final week. BfA mods are no longer included in DBMs core package. They are now a separate download. Search DBM BFA in curseforge client, or manually on curseforge or wowinterface

**Comment by LinXhi** [comment]
> Does this announcement help at all?
> 
> https://twitter.com/deadlybossmods/status/1328743166711717891
> 
> DBM 9.0.4 Released for Retail wow for patch 9.0.2.
> 
> Very important if you are still raiding bfa this final week. BfA mods are no longer included in DBMs core package. They are now a separate download. Search DBM BFA in curseforge client, or manually on curseforge or wowinterface
> 
> Did you download the new DBM BFA and still have issues?

Thank you for your replies! I didnt know about this before and yes I just tried and this works fine now :)
