### ISSUE TITLE
Error when starting fight with Queen Azshara

### ISSUE THREAD

**Issue by LNMaarten** [DeadlyBossMods/DeadlyBossMods#39]
Message: Interface\AddOns\DBM-EternalPalace\QueenAzshara.lua:210: attempt to compare two nil values
Time: Sun Jul 14 19:35:49 2019
Count: 6
Stack: Interface\AddOns\DBM-EternalPalace\QueenAzshara.lua:210: attempt to compare two nil values
[C]: ?
Interface\AddOns\DBM-EternalPalace\QueenAzshara.lua:210: in function <Interface\AddOns\DBM-EternalPalace\QueenAzshara.lua:210>
[C]: ?
Interface\AddOns\DBM-EternalPalace\QueenAzshara.lua:240: in function `func'
Interface\AddOns\DBM-Core\DBM-InfoFrame.lua:696: in function `?'
Interface\AddOns\DBM-Core\DBM-InfoFrame.lua:918: in function `Show'
Interface\AddOns\DBM-EternalPalace\QueenAzshara.lua:317: in function `OnCombatStart'
Interface\AddOns\DBM-Core\DBM-Core.lua:5937: in function `StartCombat'
Interface\AddOns\DBM-Core\DBM-Core.lua:5550: in function `handler'
Interface\AddOns\DBM-Core\DBM-Core.lua:753: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:740>

Locals:

Happens every time I engage the fight. Error disappears right away after.

**Comment by MysticalOS** [comment]
This is already fixed in alpha
