### ISSUE TITLE
DBM Pull countdown text not shown

### ISSUE THREAD

**Issue by KSeyffarth** [DeadlyBossMods/DeadlyBossMods#390]
**Describe the bug**
DBM Pull countdown text not shown, only timer bar appears.

**Do you have an error log of what happened?**
no

**To Reproduce**
Use `/pull 10` or simply `/pull` , but no countdown text appears, no "wush-wush" sounds as the numbers got bigger or else.

**Screenshots**
This is what iam talking about, but the "14" pull timer text does not appear anymore:
![image](https://user-images.githubusercontent.com/24591955/99587961-33053f00-29ea-11eb-836b-6384b3d83ac6.png)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes i just activated DBM no more addons, no pulltimer text.

**Which version of DeadlyBossMods are you using?**
`Version 9.0.4 | (2020/11/17 16:29:18)`

**Was it working in a previous version? If yes, which was the last good one?**
also not 9.0.3, were it was working was 9.0.1 (did not check but i think it was) , there was still a countdown text visible.

**Question from my side**
I only tested it with a 5 man group / solo, do i need to be in a raid? (Also, i had no timer text with 9.0.3 in last raid)

**Comment by MysticalOS** [comment]
It was removed because of a bug on blizzards end, it'll be re-enabled when that bug is confirmed fixed

**Comment by KSeyffarth** [comment]
Thanks for the quick answer :)
