### ISSUE TITLE
Finishing Torghast and exiting causes fail message

### ISSUE THREAD

**Issue by dgossage** [DeadlyBossMods/DeadlyBossMods#396]
DBM 9.06

Complete Torghast to whatever is current amount unlocked and you then exit at stairs.  Shortly after porting in to entry area you get the failed Bwonsamdi laugh and being told it was incomplete.

Not a major bug in any way, but it is a little irritating at times.

**Comment by QartemisT** [comment]
Hi there,

This has been reported and we have since disabled statistics on torghast that shows this message. The original mod was written pre-change (aka when you had to do 40+ floors).
Updating to the latest alpha of DBM-Challenges will fix this :)
