### ISSUE TITLE
Mists of Tyrna Sithe maze

### ISSUE THREAD

**Issue by Webrow** [DeadlyBossMods/DeadlyBossMods#397]
**Is your feature request related to a problem? Please describe.**
Hey Maintainer, I was thinking of implementing a maze solver for the dungeon. You see this working for / in DBM? 
I am new to the Wow Mods and wanted to pick it up as something to do, but if DBM can incorporate it easier would be stupid for me to waste time on, I dont mind writing something for a PR. but I would have to know if you want it, or if it shouldnt be in DBM

**Describe the solution you'd like**
I dont know the possibilities (what you can read from memory or what the game exposes. 
But assuming you are not able to "read"  the icons from the pillars, have a small panel where users can select what each pillar is. 
Have 3 checkboxes per pillar hollow, circle, leaf and you can click them, and solve them with some boolean algebra. 

**Describe alternatives you've considered**
Using my brain, and it works. But I want to make sure my party stops resetting us.

**Comment by QartemisT** [comment]
Generally speaking, we cannot read anything from the pillars directly, and would require a user input.
However, I don't think this is within the scope of DBM, but I will let @MysticalOS  confirm if this is the case.

**Comment by Webrow** [comment]
Cool, no problemo. I dont mind making a small thing for it then :) Ill see what @MysticalOS pings. Thanks for all your work on the project btw.
