### ISSUE TITLE
Mists of Tirna Spell warning

### ISSUE THREAD

**Issue by wolfman4500** [DeadlyBossMods/DeadlyBossMods#404]
**Twitch client installed classic/retail version on retail/classic**

**Describe the bug**

The Bug took place in the Mists of Tirna Dungeon, on mythic 0.  shortly after the start of the dungeon, DBM continues to trigger Target spell warnings from the harvesters (cant remember the name exactly, its nourish - something)  even in between pack pulls DBM is just steady with the spell alert triggers.

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**  Yes.

**Which version of DeadlyBossMods are you using?**
   DBM-Core-9.0.6
**Was it working in a previous version? If yes, which was the last good one?**
    No, this started when the dungeon released. but otherwise not sure
**Additional context**

**Comment by MysticalOS** [comment]
Already fixed in alpha with aggressive unit affecting combat filtering.
