### ISSUE TITLE
Bar Appearance Options per-bar

### ISSUE THREAD

**Issue by mspykerez** [DeadlyBossMods/DeadlyBossMods#409]
It would be great if the Bar Appearance Options could be set per bar, meaning it would have separate options for the Small Bar and the Huge Bar. I am most interested on the font size option. Currently it appears that the Bar width and scale are the only options that can be set separately.

**Comment by QartemisT** [comment]
This is officially now on my todo list :) I do plan on doing a LOT of bar reworks in the near future, so I am sure it will come as part of that batch update.

**Comment by QartemisT** [comment]
Closing issue as is now on my tracking list :)
