### ISSUE TITLE
Dependency Missing

### ISSUE THREAD

**Issue by nimuemoonwolf** [DeadlyBossMods/DeadlyBossMods#41]
I extracted the file and added all the folders into the addons folder.
What am I missing? Here is a screenshot of addons that is in:
https://imgur.com/a/OpkdFTL

**Comment by MysticalOS** [comment]
GUI and default skins are both missing and both required.

**Comment by nimuemoonwolf** [comment]
Where can I find them to download and add to the addons folder? (Odd as this is the 2nd time I downloaded this and never had an issue before.)

**Comment by MysticalOS** [comment]
they're already included in zip on any of trusted download sites like curse/twitch and WowInterface. If you are downloading from somewhere else, it's not recommended.

**Comment by nimuemoonwolf** [comment]
I am pretty sure I downloaded it from curse like I normally do.

**Comment by nimuemoonwolf** [comment]
Yep, it was from Curse and I hit the download button that is at the top right hand side of the DBM page.

**Comment by nimuemoonwolf** [comment]
Ok I redownloaded and looks to have more files then my last download, very odd. Hopefully will work now!
