### ISSUE TITLE
'sort by remaining time' and bar grow direction

### ISSUE THREAD

**Issue by mspykerez** [DeadlyBossMods/DeadlyBossMods#410]
I'd like that when you have the option 'sort by remaining time' enabled in conjunction with 'expand upward' the bar with the shortest time appear always on top of a bar with a longer timer. The problem is that currently the bars with the shortest timers always appear bellow the ones with the longest timers and I do not see any option to make it the other way around.

**Comment by QartemisT** [comment]
Also now added to my list :) Some sort of "Reversed sort by remaining time"

**Comment by QartemisT** [comment]
Closing issue as is now on my tracking list :)
