### ISSUE TITLE
an error occured in Azshara

### ISSUE THREAD

**Issue by Elnarfim** [DeadlyBossMods/DeadlyBossMods#42]
**Describe the bug**

**Do you have an error log of what happened?**
2x DBM-EternalPalace\QueenAzshara.lua:625: attempt to concatenate local 'text' (a nil value)
DBM-EternalPalace\QueenAzshara.lua:625: in function `handler'
DBM-Core\DBM-Core-8.2.5-2-g54d6db0bc.lua:757: in function <DBM-Core\DBM-Core.lua:744>
(tail call): ?
DBM-Core\DBM-Core-8.2.5-2-g54d6db0bc.lua:757: in function <DBM-Core\DBM-Core.lua:744>

Locals:
InCombatSkipped

1x DBM-EternalPalace\QueenAzshara.lua:629: attempt to concatenate local 'text' (a nil value)
DBM-EternalPalace\QueenAzshara.lua:629: in function `handler'
DBM-Core\DBM-Core-8.2.5-2-g54d6db0bc.lua:757: in function <DBM-Core\DBM-Core.lua:744>
(tail call): ?
DBM-Core\DBM-Core-8.2.5-2-g54d6db0bc.lua:757: in function <DBM-Core\DBM-Core.lua:744>

Locals:
InCombatSkipped

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
Possibly fixed in latest commit but hoestly don't know anymore. Having trouble getting this to work right.

**Comment by Elnarfim** [comment]
I already have done EP heroic, can check this in few days later

**Comment by MysticalOS** [comment]
have you recleared yet, is this issue resolved?
