### ISSUE TITLE
Shadow Priest Void Form causes callouts to not mark targets

### ISSUE THREAD

**Issue by TheMusicMeister** [DeadlyBossMods/DeadlyBossMods#424]
When a Shadow Priest is in Void Form, their spoken language changes to "Shath'Yar", which makes everything they say come out differently than what DBM expects.  This causes things like "Star" callouts for marking targets to not work, as the Shadow Priest will instead say something like "shN", which doesn't mark them.

Would it be possible to track these translated callouts and bind them to the proper markings?  Similar to spoken languages of other races and factions, the language of Void Form should be consistent and able to be translated.

**Comment by MysticalOS** [comment]
Only if someone does translation work for me. I certainly don't have the means to test/figure this out. I'm also not sure if raid icons will work even if translations are figured out. You may be able to do something like get it to say "s Tar" instead f showing a star but I doubt there'd ever be a magic translation that translates to `{rt1}`
