### ISSUE TITLE
Option to enable raid progression tracking messages tagged by raid leader (or guild event)

### ISSUE THREAD

**Issue by dgouk** [DeadlyBossMods/DeadlyBossMods#425]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Could you please add an option to the Options/Global Disables & Filters/Privacy Controls config page to add the raid leader's name to the Raid progression tracking messages?
e.g. `<DBM-Rogueleader> [Message]`
This will allow guild members to track multiple raid teams in parallel by the raid leader's name.

**Describe alternatives you've considered**
I have checked the options, there does not appear to be a toggle for this feature.
I don't really want to dig into and mod the code myself.

**Additional context**
There might also be other ways to achieve this if you can pull the name of the guild event from the calendar?

**Comment by MysticalOS** [comment]
Not an option i'm considering at this time. besides you can already track multiple raid teams with guild engage/defeat/wipe messages feature that you'll see when guild groups you are not in engage bosses
