### ISSUE TITLE
Dropdown menu doesn't show scroll bar or arrows.

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DeadlyBossMods#43]
The DBM drop down menu has had this major bug since wrath. It just never was a huge issue since most realized you could mouse wheel the menu to get around it, plus it was in places it wasn't used much such as setting announce font. You do that once then never again.

However, now that special warning sounds, timer countdowns etc are getting MUCH more use of menu, it's important it actually be fixed so it has clickable arrows and scroll bar. This way users are actually aware there are dozens of sounds/countdowns and not just 5-6.

**Comment by Megamurlocs** [comment]
Also having a similar issue. Really need to be able to change sounds and alerts I really dont care about. My drop down doesn't even show the name of the spells. [Screenshot](https://imgur.com/a/6TeDyb1)

**Comment by MysticalOS** [comment]
You can do that from /dbm main GUI, the broker for that doesn't really work well since it hasn't been updated in about a decade and has no way of supporting the drop downs for special warning sounds and coutndowns at all. If anything I may prune that feature since it doesn't really work anymore.

**Comment by MysticalOS** [comment]
Current Issues:

Sometimes the scroll bar isn't visible, until you scroll the frame (which you can't if you don't have a mousewheel)

The scrollbar seems to think there are more entries than there are.

**Comment by MysticalOS** [comment]
https://www.youtube.com/watch?v=VewN6uzFGOc&feature=youtu.be  reference video
