### ISSUE TITLE
freeze at pull boss or pull M+ keys

### ISSUE THREAD

**Issue by Ay-ukii** [DeadlyBossMods/DeadlyBossMods#445]
**Twitch client installed classic/retail version on retail/classic**

i'm on Shadowlands official version
 

**Describe the bug**

when the fight starts my game freezes for 5 seconds

**Do you have an error log of what happened?**

no

**To Reproduce**

1. start dbm pull when a boss combat or key start
2. wait the end 
3. See freeze at start

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes i try to disable Weak aura and Elvui no success

**Which version of DeadlyBossMods are you using?**

the last

**Was it working in a previous version? If yes, which was the last good one?**

no

**Comment by QartemisT** [comment]
Have you tried disabling DBM, and see if the freezes still occur?
