### ISSUE TITLE
WoW Classic Kel'Thuzad Initial Mind Control TImer

### ISSUE THREAD

**Issue by addohm** [DeadlyBossMods/DeadlyBossMods#454]
**Is your feature request related to a problem? Please describe.**
No initial indication of KT mind control

**Describe the solution you'd like**
Add a KT Initial Mind Control Timer, ability seems to be used >1.5 minutes after KT becomes actively engagable.

**Comment by MysticalOS** [comment]
I looked specifically at logs and it was highly variable, maybe even health based, i doubt it's a timed trigger, probably a condition one. Closing issue as it's already something that's been reviewed and declined
