### ISSUE TITLE
Castle Nathria Sludge Fist counter bug

### ISSUE THREAD

**Issue by TerrifiedOne** [DeadlyBossMods/DeadlyBossMods#457]
**Twitch client installed classic/retail version on retail/classic**

**Describe the bug**
 **** There were certain counters when doing the Sludgefist on normal that werent counting correctly or timed right. They would count down, reach zero and then start counting up. So the timing was off.**** 

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No
**Which version of DeadlyBossMods are you using?** Newest one. I update everyday

**Was it working in a previous version? If yes, which was the last good one?** I didnt do this fight before. So I wouldnt know. 

**Additional context**
I was luckily streaming and made a clip of it so you can see. https://clips.twitch.tv/SassyRespectfulMochaShadyLulu

**Comment by MysticalOS** [comment]
Not a bug, these are not static timers and can be spell queued. the timers do  that to show the spell cd is complete and spell is queued (and amount of time it's been queued).

**Comment by TerrifiedOne** [comment]
But with other bosses the count down timer was on time when the spell was going to be cast.

**Comment by MysticalOS** [comment]
That's because other bosses were designed better. Sometime bosses just spell queue. All DBM does is present the information too othe user.
