### ISSUE TITLE
shorttext.

### ISSUE THREAD

**Issue by coolaken** [DeadlyBossMods/DeadlyBossMods#460]
if L.AUTO_TIMER_TEXTS[timerType.."short"] and DBM.Bars:GetOption("StripCDText") then
	return pformat(L.AUTO_TIMER_TEXTS[timerType.."short"], spellName)
else
	return pformat(L.AUTO_TIMER_TEXTS[timerType], spellName)
end

translate error or bug?

**Comment by QartemisT** [comment]
No, this looks fine?

**Comment by coolaken** [comment]
the check button of shorttext this is stripcdtext ? is that right?

**Comment by QartemisT** [comment]
Yes, its the option in the GUI that says "Strip CD/Next out of timers"

**Comment by coolaken** [comment]
but it does the shortcdtext thing?

**Comment by QartemisT** [comment]
Yes.

**Comment by coolaken** [comment]
what about shortcdtext checkbutton do..

**Comment by QartemisT** [comment]
It changes the text on bars from say "Next <spell>: <time>" to "<spell>: <time>", making it a bit more visable.

**Comment by coolaken** [comment]
thank you.
