### ISSUE TITLE
Blood Council nil errors

### ISSUE THREAD

**Issue by Elnarfim** [DeadlyBossMods/DeadlyBossMods#461]
**Twitch client installed classic/retail version on retail/classic**

**Describe the bug**

210x ...rfaceDBM-CastleNathria\TheCouncilofBlood.lua:683: attempt to index field 'Infoframe' (a nil value)
[string "@DBM-CastleNathria\TheCouncilofBlood.lua"]:683: in function `handler'
[string "@DBM-Core\DBM-Core-9.0.15-8-g7008697.lua"]:896: in function <DBM-Core\DBM-Core.lua:883>
[string "=(tail call)"]: ?
[string "@DBM-Core\DBM-Core-9.0.15-8-g7008697.lua"]:896: in function <DBM-Core\DBM-Core.lua:883>

Locals:
Skipped (In Encounter)
**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
That bug has been there since launch and no one reported it for nearly 4 weeks. Explains why I never saw the frame on any streams

**Comment by Elnarfim** [comment]
I'm using latest alpha. No ElvUI. previous version was also broken. it just happen when encounter has launched
