### ISSUE TITLE
Shows warning for spell even though warning is disabled (Condemn, Lady Inerva Heroic)

### ISSUE THREAD

**Issue by Elehiggle** [DeadlyBossMods/DeadlyBossMods#467]
**Describe the bug**
The option to deactivate the warning for the [Condemn](https://www.wowhead.com/spell=331550/condemn) spell from the [Conjured Manifestation](https://www.wowhead.com/npc=173484/conjured-manifestation) add that Lady Inerva spawns on Heroic difficulty is not working.

DBM should honor the setting and not show the warning to interrupt the Condemn spell.

**Screenshots**
![1653929_2021-01-04_03-00-00-956](https://user-images.githubusercontent.com/20746115/103495681-eb246500-4e3b-11eb-8fa1-18e578105a09.jpg)
![ssss](https://user-images.githubusercontent.com/20746115/103495812-51a98300-4e3c-11eb-9a0b-6016ff2fdee0.png)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?**
9.0.15

**Was it working in a previous version? If yes, which was the last good one?**
Unknown

**Additional context**
The Condemn spell is cast many times and thus is very annoying to get 10 warnings within 2 seconds when the spell gets interrupted and it recasts the spell. You can't see the real important warnings like having to cut the orbs. I wanted to disable the warning. I went into the DBM options for Lady Inerva and the spell was already disabled (I assume its the default setting then). Either the options screen is showing me a wrong configuration (I never changed DBM settings, ever), or DBM does not honor the setting. Maybe it has something to do with my client being German?

**Comment by MysticalOS** [comment]
that's incorrect warning option. That's not the special warning to interrupt optino, that's just general announce that's already off by default for non tanks. Look for the other Condemn option

**Comment by Elehiggle** [comment]
> 
> 
> that's incorrect warning option. That's not the special warning to interrupt optino, that's just general announce that's already off by default for non tanks. Look for the other Condemn option

Thanks. I made sure to double check for any other option that could remove this annoyance, but there is not a single option related to this, not even mentioning Condemn anywhere else.

**Comment by MysticalOS** [comment]
It wasn't supposed to be on by default anyways so I fixed it with a force reset regardless, but there is a second option somewhere. It's not cleanest UI in world. if I could come up with a good idea in my head of how to merge warning and special warning object types in GUI I'd work towards that end but every brain storm I've had on it had big caveates
