### ISSUE TITLE
Missing some sounds

### ISSUE THREAD

**Issue by banta84** [DeadlyBossMods/DeadlyBossMods#47]
![WoWScrnShot_072619_164704](https://user-images.githubusercontent.com/53343442/61957861-b7d77880-afaf-11e9-8566-ae8c61bc56b0.jpg)
![WoWScrnShot_072619_165131](https://user-images.githubusercontent.com/53343442/61957872-be65f000-afaf-11e9-8cdc-dc7bacacaaa7.jpg)

Missing some alert ingame sounds in dropdown menu when customuzing some events, like Kazrogal "you marked". Yogg-saron laught and many others. They just dissapear even before 8.2 addon.

BUT in options->Special warnings->dropdown menu those sounds still selectable and looks like works.

BugSack no get any errors.

Removing all other addons/wtf no helps

DBM version 8.2.9

I also found https://github.com/DeadlyBossMods/DeadlyBossMods/issues/31
but in recent version problem still here.

**Comment by MysticalOS** [comment]
If you're still getting issue 31, then you still have bad sounds, there is no bug left with that that I can find. If sound path = string and path isn't "" and path is not registered in LibSharedMedia, then path is invalid. That's how logic works. It means you still have some sound somewhere set to media that doesn't exist that wasn't set to None/No Sound

**Comment by banta84** [comment]
in DBM_GUI i found only this block with some sounds and no one of them works now:
		local Sounds = MixinSharedMedia3("sound", {
			{	text	= L.NoSound,			value	= "" },
			{	text	= "PvP Flag",			value 	= 8174, 		sound=true },--"Sound\\Spells\\PVPFlagTaken.ogg"
			{	text	= "Blizzard",			value 	= 37666, 		sound=true },--"Sound\\interface\\UI_RaidBossWhisperWarning.ogg"
			{	text	= "Beware!",			value 	= 15391, 		sound=true },--"Sound\\Creature\\AlgalonTheObserver\\UR_Algalon_BHole01.ogg"
			{	text	= "AirHorn",			value 	= "Interface\\AddOns\\DBM-Core\\sounds\\AirHorn.ogg", 		sound=true },
			{	text	= "Destruction",		value 	= 12506, 		sound=true },--"Sound\\Creature\\KilJaeden\\KILJAEDEN02.ogg"
			{	text	= "NotPrepared",		value 	= 11466, 		sound=true },--"Sound\\Creature\\Illidan\\BLACK_Illidan_04.ogg"
			{	text	= "NotPrepared2",		value 	= 68563, 		sound=true },--"Sound\\Creature\\Illidan_Stormrage\\VO_703_Illidan_Stormrage_03.ogg"
			{	text	= "RunAwayLittleGirl",	value 	= 9278, 		sound=true },--"Sound\\Creature\\HoodWolf\\HoodWolfTransformPlayer01.ogg"
			{	text	= "NightElfBell",		value 	= 11742, 		sound=true },--"Sound\\Doodad\\BellTollNightElf.ogg"
			{	text	= "Headless Horseman: Laugh", value = 11965, sound = true },
			{	text	= "Yogg Saron: Laugh", value = 15757, sound = true },
			{	text	= "Loatheb: I see you", value = 128466, sound = true },
			{	text	= "Lady Malande: Flee", value = 11482, sound = true },
			{	text	= "Milhouse: Light You Up", value = 49764, sound = true },
			{	text	= "Void Reaver: Marked", value = 11213, sound = true },
			{	text	= "Kaz'rogal: Marked", value = 11052, sound = true },
			{	text	= "C'Thun: You Will Die!", value = 8585, sound = true }
		})

but in OPTIONS block they still selectable. Once more reinstall DBM and remove all other addons.

https://youtu.be/2UZx-jlcVP4

**Comment by MysticalOS** [comment]
Video says unavailable. all the sounds appear in dropdown just fine, and when i select one i hear it play.

**Comment by banta84** [comment]
Sorry for video - radio station was recorded also=) Try this
https://youtu.be/W7VPpnfhEy4

**Comment by banta84** [comment]
Sorry for video - tadio station was recorded also. 
try this https://youtu.be/2UZx-jlcVP4

**Comment by MysticalOS** [comment]
Sorry if i wasn't clear earlier, I fixed this in alpha with that commit. if you aren't using alpha you'll still not see the fix. anything newer than https://github.com/DeadlyBossMods/DeadlyBossMods/commit/b8208508572d998c3941cf3743b9020db281eef7

**Comment by banta84** [comment]
Тow after some correcting those 2 files in 2.8.10a sounds works fine again! Thank you for your patience!
