### ISSUE TITLE
Chains of Kel'Thuzad does not show up

### ISSUE THREAD

**Issue by HIghCommander540** [DeadlyBossMods/DeadlyBossMods#470]
My guild just downed KT last night and the biggest issue was the Chains of Kel'Thuzad.

There is no indicator in DBM either before or right as the ability happens.

We were all expected to be informed by DBM ahead of the chains, but it also never showed when they were actually cast.

Is this expected?

**Comment by MysticalOS** [comment]
it announces who they are on, that's it. no pre cast and no timer since timing wise it's too variable to ever have a functional timer that'd be useful. It's also instant cast so can't pre warn it either. it's basically already as good as it can be.

**Comment by HIghCommander540** [comment]
Ok, thanks! Go ahead and close ticket.
