### ISSUE TITLE
Error message in the castle of nathria

### ISSUE THREAD

**Issue by Johunn** [DeadlyBossMods/DeadlyBossMods#476]
**WowUp 2.03 / WoW 9.02**

**Describe the bug**
I had an error message when I was in the castle of Nathria, I can't say exactly when because I saw this error message in BugSack at the end of the raid .

**Do you have an error log of what happened?**
14x DBM-StatusBarTimers\DBT.lua:1118: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: DBT_Bar_7:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@DBM-StatusBarTimers\DBT.lua"]:1118: in function `Update'
[string "@DBM-StatusBarTimers\DBT.lua"]:947: in function `SetElapsed'
[string "@DBM-StatusBarTimers\DBT.lua"]:890: in function <DBM-StatusBarTimers\DBT.lua:886>
[string "=(tail call)"]: ?
[string "@DBM-CastleNathria\TheCouncilofBlood.lua"]:769: in function `handler'
[string "@DBM-Core\DBM-Core-9.0.17.lua"]:896: in function <DBM-Core\DBM-Core.lua:883>
[string "=(tail call)"]: ?
[string "@DBM-Core\DBM-Core-9.0.17.lua"]:896: in function <DBM-Core\DBM-Core.lua:883>

Locals:
Skipped (In Encounter) 

**To Reproduce**

IDK

**Screenshots**
//
**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I only have DBM, and yes I have Elvui last version, and I can't try without it because I don't know when exactly I had the error :s.
**Which version of DeadlyBossMods are you using?**
<DBM 9.017>
**Was it working in a previous version? If yes, which was the last good one?**
Can't say...
**Additional context**
//

**Comment by MysticalOS** [comment]
I'll do more work on this issue tomorrow. The hack artemis put in would silence it but not fix core issue, I believe I identified actual issue and have some shotty code to fix it at source, but that needs testing.

**Comment by MysticalOS** [comment]
Based on my testing, this issue should be resolved in latest alpha, of course you need to use alpha to be sure of it, but all my internal testing allowed me to spam add/remove time for timers without any failures, even timers that were under the "moving" condition while they were updated when I was running the Classic bar behavior.

**Comment by Johunn** [comment]
Okay ty for your fast support. I will test that on my next raid ^^.

**Comment by MysticalOS** [comment]
I'm gonna leave issue open until we're 100% sure

**Comment by Johunn** [comment]
No more error message during the raid :). Ty ;)
