### ISSUE TITLE
Remove obsolete BigBrother checks, and support ExRT or Ora3 checks instead.

### ISSUE THREAD

**Issue by Addonman** [DeadlyBossMods/DeadlyBossMods#481]
I was going through options in DBM when i noticed in extra features menioning of Bigbrother addon. Since its still in options -is it there since it was long ago added and never removed or do you know of current version of BB that is updated for SL? 
I myself is using old version that still kinda works but gets bugs from using ace 2 instead of ace 3.

**Comment by MysticalOS** [comment]
no idea, if BB not updated for SL then that should be removed from DBM
