### ISSUE TITLE
Errors in bugsack during arena skirmishes

### ISSUE THREAD

**Issue by addonaddict** [DeadlyBossMods/DeadlyBossMods#487]
error 1:

14x DBM-StatusBarTimers\DBT.lua:1521: attempt to perform arithmetic on a nil value
[string "@DBM-StatusBarTimers\DBT.lua"]:1521: in function `MoveToNextPosition'
[string "@DBM-StatusBarTimers\DBT.lua"]:559: in function `Remove'
[string "@DBM-StatusBarTimers\DBT.lua"]:1219: in function `RemoveFromList'
[string "@DBM-StatusBarTimers\DBT.lua"]:1231: in function <DBM-StatusBarTimers\DBT.lua:1227>
[string "=(tail call)"]: ?
[string "@DBM-StatusBarTimers\DBT.lua"]:1611: in function <DBM-StatusBarTimers\DBT.lua:1605>

Locals:
self = <table> {
 totalTime = 686.979000
 lastUpdate = 277329.228000
 next = <table> {
 }
 id = "TimerWin"
 owner = <table> {
 }
 delta = 0.042000
 countdownMax = 4
 countdown = 0
 colorType = 0
 curTime = 277329.228000
 prev = <table> {
 }
 timer = 3.046000
 frame = DBT_Bar_4 {
 }
}
newAnchor = DBT_Bar_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = nil
(*temporary) = 97.500000
(*temporary) = DBT_Bar_4 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = 195
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on a nil value"

error 2:
15x DBM-StatusBarTimers\DBT.lua:1521: attempt to perform arithmetic on a nil value
[string "@DBM-StatusBarTimers\DBT.lua"]:1521: in function `MoveToNextPosition'
[string "@DBM-StatusBarTimers\DBT.lua"]:559: in function `Remove'
[string "@DBM-StatusBarTimers\DBT.lua"]:1219: in function `RemoveFromList'
[string "@DBM-StatusBarTimers\DBT.lua"]:1231: in function <DBM-StatusBarTimers\DBT.lua:1227>
[string "=(tail call)"]: ?
[string "@DBM-StatusBarTimers\DBT.lua"]:1611: in function <DBM-StatusBarTimers\DBT.lua:1605>

Locals:
self = <table> {
 totalTime = 686.979000
 lastUpdate = 277329.228000
 next = <table> {
 }
 id = "TimerWin"
 owner = <table> {
 }
 delta = 0.042000
 countdownMax = 4
 countdown = 0
 colorType = 0
 curTime = 277329.228000
 prev = <table> {
 }
 timer = 3.046000
 frame = DBT_Bar_4 {
 }
}
newAnchor = DBT_Bar_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = nil
(*temporary) = 97.500000
(*temporary) = DBT_Bar_4 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = 195
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on a nil value"

error 3

3x DBM-StatusBarTimers\DBT.lua:1514: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_2:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@DBM-StatusBarTimers\DBT.lua"]:1514: in function `SetPosition'
[string "@DBM-StatusBarTimers\DBT.lua"]:538: in function `Append'
[string "@DBM-StatusBarTimers\DBT.lua"]:812: in function `CreateBar'
[string "@DBM-Core\DBM-Core-9.0.18.lua"]:10997: in function `Start'
[string "@DBM-PvP\PvPGeneral.lua"]:319: in function `func'
[string "@DBM-Core\DBM-Core-9.0.18.lua"]:1874: in function <DBM-Core\DBM-Core.lua:1865>

Locals:
(*temporary) = DBT_Bar_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = DBT_Bar_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 0

**Comment by QartemisT** [comment]
You need to run the latest DBM alpha :) We fixed this there.

**Comment by addonaddict** [comment]
Ok sorry, i saw an update to DBM so i figured that was already included, will try alpha

**Comment by QartemisT** [comment]
You want the alpha update for Deadly Boss Mods, not DBM-PvP :D
