### ISSUE TITLE
Castle Nathria LFR timers

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DeadlyBossMods#489]
**Describe the bug**
Some timers are being off on first 3 bosses + weird empty frame on Hungering Destroyer.

**Do you have an error log of what happened?**
Screenshots and [Transcriptor log](https://gist.github.com/Molkree/17ece7f1c98695bd6628ff80e3a5d9e7).

**Screenshots**
First timers
Altimor
![image](https://user-images.githubusercontent.com/12860284/105911711-82e03200-603b-11eb-92fa-0cf93c122189.png)

Inerva Darkvein
![image](https://user-images.githubusercontent.com/12860284/105911753-8f648a80-603b-11eb-9a4f-d0d72713e874.png)
![image](https://user-images.githubusercontent.com/12860284/105911765-92f81180-603b-11eb-8240-3fab4004883b.png)
![image](https://user-images.githubusercontent.com/12860284/105911775-95f30200-603b-11eb-8a4a-a31556bfa108.png)

Empty frame that stayed empty for the whole fight on Hungering Destroyer. Possibly not a bug and I just haven't seen stuff that should be there? But reporting just in case.
![image](https://user-images.githubusercontent.com/12860284/105912207-29c4ce00-603c-11eb-8f76-e1579dae34b0.png)

**Which version of DeadlyBossMods are you using?**
9.0.18-11

**Was it working in a previous version? If yes, which was the last good one?**
I don't know.

**Additional context**
This is before weekly reset in EU, but shouldn't matter because these fights should be unchanged.

**Comment by MysticalOS** [comment]
It's normal for infoframe to be blank if nothing is going on, that's not bugged.

Other stuff fixed in latest commit
