### ISSUE TITLE
LUA Error - StatusBarTimes

### ISSUE THREAD

**Issue by mjdeans** [DeadlyBossMods/DeadlyBossMods#490]
ders\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_3:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1513: in function `SetPosition'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:538: in function `Append'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:958: in function `SetElapsed'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:751: in function `CreateBar'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:10998: in function `Start'
[string "@Interface\AddOns\DBM-PvP\PvPGeneral.lua"]:593: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:893: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:880>

Locals: (*temporary) = DBT_Bar_3 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = DBT_Bar_3 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 0

**Comment by MysticalOS** [comment]
Error seems incomplete, is this latest DBM update from today?

**Comment by mjdeans** [comment]
I just made the update, and it seems to be working. I apologize!

**Comment by MysticalOS** [comment]
ok, so confirming you had old dbm, new dbm no issues?

**Comment by mjdeans** [comment]
So far, that's correct! If anything changes, I'll come back and report!

**Comment by MysticalOS** [comment]
Thanks, closing

**Comment by mjdeans** [comment]
Got the error again today when in Wintergrasp.
--------------------
Message: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_2:SetPoint.
Time: Thu Jan 28 11:28:12 2021
Count: 1
Stack: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_2:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1513: in function `SetPosition'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:518: in function `Append'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:812: in function `CreateBar'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:10998: in function `Start'
[string "@Interface\AddOns\DBM-PvP\PvPGeneral.lua"]:313: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:893: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:880>

Locals: (*temporary) = DBT_Bar_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = DBT_Bar_2 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 0
