### ISSUE TITLE
Status Bar Timer Issue

### ISSUE THREAD

**Issue by mjdeans** [DeadlyBossMods/DeadlyBossMods#491]
Message: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_1:SetPoint.
Time: Thu Jan 28 22:36:48 2021
Count: 1
Stack: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_1:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1513: in function `SetPosition'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:538: in function `Append'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:812: in function `CreateBar'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:10998: in function `Start'
[string "@Interface\AddOns\DBM-PvP\PvPGeneral.lua"]:313: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:893: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:880>

Locals: (*temporary) = DBT_Bar_1 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = DBT_Bar_1 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 0

**Comment by QartemisT** [comment]
Update DBM-PvP to r114 :)

**Comment by mjdeans** [comment]
Thank you very much!

**Comment by MysticalOS** [comment]
ii'm not 100% convinced that'll fix problem yet since at this point just taking shots in dark. I can't reproduce problem.

**Comment by mjdeans** [comment]
Fair enough! If it happens again, I'll let you know and will be more
specific about the context it arises.
