### ISSUE TITLE
Addon No updating via twitch

### ISSUE THREAD

**Issue by kaseyd24** [DeadlyBossMods/DeadlyBossMods#5]
There is no in game issue, just not updating via twitch.. the two addons DBM and RaiderIO are not updating.. all other addons are.. Just these two.

**Comment by MysticalOS** [comment]
This is just something you have to report to twitch,I have no control over it on this end. Twitch/curse has their own ticket system you can try using, but I have been told they are aware of and working on issue. I had believed they had hotfixed issue already, but perhaps it didn't get pushed, or didn't take.
