### ISSUE TITLE
A nil error in Denathrius

### ISSUE THREAD

**Issue by Elnarfim** [DeadlyBossMods/DeadlyBossMods#508]
**Twitch client installed classic/retail version on retail/classic**
I'm using 9.0.20 alpha 30 version

**Describe the bug**

1x DBM-CastleNathria\SireDenathrius.lua:800: attempt to index field '?' (a nil value)
[string "@DBM-CastleNathria\SireDenathrius.lua"]:800: in function `OnSync'
[string "@DBM-Core\DBM-Core-9.0.19-30-g74e6e8c.lua"]:12217: in function `ReceiveSync'
[string "@DBM-Core\DBM-Core-9.0.19-30-g74e6e8c.lua"]:12193: in function `SendSync'
[string "@DBM-CastleNathria\SireDenathrius.lua"]:774: in function `handler'
[string "@DBM-Core\DBM-Core-9.0.19-30-g74e6e8c.lua"]:892: in function <DBM-Core\DBM-Core.lua:879>

Locals:
Skipped (In Encounter)
**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
Error makes no sense, were you sitting outside the raid?

**Comment by MysticalOS** [comment]
I added two possible fixes regardless, it definitely shouldn't happen now.
