### ISSUE TITLE
Pandaria raids causing various errors to occur.

### ISSUE THREAD

**Issue by Ookami313** [DeadlyBossMods/DeadlyBossMods#512]
**Twitch client installed classic/retail version on retail/classic**
Retail version.

**Describe the bug**
Running an alt through Pandaria raids and the following error kept occurring during various fights through out the runs.

**Do you have an error log of what happened?**
2x DBM-StatusBarTimers\DBT.lua:1511: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_5:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@DBM-StatusBarTimers\DBT.lua"]:1511: in function `SetPosition'
[string "@DBM-StatusBarTimers\DBT.lua"]:538: in function `Append'
[string "@DBM-StatusBarTimers\DBT.lua"]:812: in function `CreateBar'
[string "@DBM-Core\DBM-Core-9.0.21.lua"]:11000: in function `Start'
[string "@DBM-Core\DBM-Core-9.0.21.lua"]:11639: in function `Start'
[string "@DBM-ThroneofThunder\Tortos.lua"]:100: in function `OnCombatStart'
[string "@DBM-Core\DBM-Core-9.0.21.lua"]:6282: in function `StartCombat'
[string "@DBM-Core\DBM-Core-9.0.21.lua"]:5862: in function `handler'
[string "@DBM-Core\DBM-Core-9.0.21.lua"]:892: in function <DBM-Core\DBM-Core.lua:879>

Locals:
(*temporary) = DBT_Bar_5 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = DBT_Bar_5 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = 0
(*temporary) = 0

2x DBM-StatusBarTimers\DBT.lua:1520: attempt to perform arithmetic on a nil value
[string "@DBM-StatusBarTimers\DBT.lua"]:1520: in function `MoveToNextPosition'
[string "@DBM-StatusBarTimers\DBT.lua"]:553: in function `Remove'
[string "@DBM-StatusBarTimers\DBT.lua"]:1218: in function `RemoveFromList'
[string "@DBM-StatusBarTimers\DBT.lua"]:1158: in function `Update'
[string "@DBM-StatusBarTimers\DBT.lua"]:1610: in function <DBM-StatusBarTimers\DBT.lua:1604>

Locals:
Skipped (In Encounter)

8x DBM-StatusBarTimers\DBT.lua:1511: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: DBT_Bar_5:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@DBM-StatusBarTimers\DBT.lua"]:1511: in function `SetPosition'
[string "@DBM-StatusBarTimers\DBT.lua"]:526: in function `Append'
[string "@DBM-StatusBarTimers\DBT.lua"]:812: in function `CreateBar'
[string "@DBM-Core\DBM-Core-9.0.21.lua"]:11000: in function `Start'
[string "@DBM-ThroneofThunder\Tortos.lua"]:124: in function `handler'
[string "@DBM-Core\DBM-Core-9.0.21.lua"]:892: in function <DBM-Core\DBM-Core.lua:879>
[string "=(tail call)"]: ?
[string "@DBM-Core\DBM-Core-9.0.21.lua"]:892: in function <DBM-Core\DBM-Core.lua:879>

Locals:
Skipped (In Encounter)

**Comment by MysticalOS** [comment]
Had you run pvp before? can you make a COMPLETE list of all addons installed as well. also, please reply in this thread. https://github.com/DeadlyBossMods/DeadlyBossMods/issues/506

**Comment by Ookami313** [comment]
In answer to your question in ticket #512, I have not played any PVP since last expansion. As for an addon list, I will try to post one when I have a second to make it.
