### ISSUE TITLE
DBM core fails to load on OSX

### ISSUE THREAD

**Issue by laundrevity** [DeadlyBossMods/DeadlyBossMods#514]
Message: Interface\AddOns\DBM-Core\DBM-Core.lua:538: attempt to call local 'LibStub' (a nil value)
Time: Wed Feb 24 17:45:21 2021
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:538: attempt to call local 'LibStub' (a nil value)
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:538: in main chunk

Locals: L = <table> {
 INSTANCE_INFO_STATS_AWAY = "Away: %s"
 AUTO_RRANGE_OPTION_TEXT = "Show reverse range frame (%s) for $spell:%s"
 MIDDLE = "Middle"
 SCENARIO_ENDED_AT = "%s ended after %s."
 VERSIONCHECK_ENTRY_TWO = "%s: %s (%s) & %s (%s)"
 MPROFILE_COPY_SUCCESS = "%s's (%d spec) mod settings have been copied."
 INSTANCE_INFO_ALL_RESPONSES = "Received responses from all raid members"
 OPTION_CATEGORY_WARNINGS_ROLE = "Role Announces"
 TIMER_FORMAT_MINS = "%d |4minute:minutes;"
 ANNOUNCE_PULL_TARGET = "Pulling %s in %d sec. (Sent by %s)"
 POISON_ICON = ""
 BIG_ADD = "Big Add"
 ADDS = "Adds"
 BOSS = "Boss"
 SAFE = "Safe"
 LAG_FOOTER = "No Response: %s"
 PROFILE_APPLIED = "'%s' profile applied."
 PIZZA_SYNC_INFO = "[%1$s] sent you a DBM timer: '%2$s'
[Cancel this timer]  [Ignore timers from %1$s]"
 SILENTMODE_IS = "SilentMode is "
 RANGECHECK_HEADERT = "Range Check (%dy-%dP)"
 FAR_AWAY = "Far Away"
 GEAR_WARNING = "Warning: Check gear. Your equipped ilvl is %d lower than bag ilvl"
 AUTO_YELL_OPTION_TEXT = <table> {
 }
 RANGECHECK_RHEADER = "R-Range Check (%dy)"
 RANGERADAR_HEADER = "Range:%d Players:%d"
 VOICE_COUNT_MISSING = "Countdown voice %d is set to a voice/count pack that could not be found. It has been reset to default setting: %s."
 LOAD_MOD_COMBAT = "Loading of '%s' delayed until you leave combat"
 OUTDATEDRLT = "WARNING: DBM-RaidLeadTools breaks DBM. DBM-RaidLeadTools is no longer supported and must be removed for DBM to function properly."
 SOUNDKIT_MIGRATION = "One or more of your warning/special warning sounds were reset to defaults do to incompatability media type or invalid sound path. DBM now only supports sound files residing your addons folder, or SoundKit IDs for playing media"
 LOAD_MOD_TOC_MISMATCH = "%s could not be loaded because it is designed for a WoW patch (%s) that's not currently available. When patch becomes available, this mod will automatically work."
 RANGECHECK_OPTION_FRAMES = "Frames"
 PROFILE_DELETED = "'%s' profile deleted. 'Default' profile will be applied."
 SCENARIO_ENDED_AT_LONG = "%s ended after %s. You have %d total incompletes on this difficulty."
 HEALER_ICON = ""
 BOSS_DOWN_NR = "%s down after %s! This is a new record! (Old record was %s). You have %d total victories."
 RANGECHECK_SOUND_1 = "Default sound"
 BOSS_DOWN_I = "%s down! You have %d total victories."
 RANGECHECK_SOUND_OPTION_1 = "Sound when one player is in range"
 BREAK_SEC = "Break ends in %s seconds!"
 TRANSCRIPTOR_LOG_START = "Transcriptor logging started."
 NOTE_SHARE_SUCCESS = "%s has shared their note for %s"
 NEXT = "Next %s"
 UNKNOWN = "Unknown"
 RANGECHECK_SOUND_0 = "No sound"
 GENERIC_WARNING_BERSERK = "Berserk in %s %s"
 HEALER_ICON_SMALL = ""
 GENERIC_WARNING_OTHERS2 = "and %d others"
 SOUTH = "South"
 COMBAT_ENDED_AT = "Combat against %s (%s) ended after %s."
 NONE = "None"
 RANGECHECK_OPTION_BOTH = "Show both frames"
 NO_ARROW = "Arrow can not be used in instances"
 MPROFILE_COPYS_S_ERROR = "Source is corrupted. Sound or note settings not copied or partly copied. Copy failed."
 LDB_CAT_MOP = "Mists of Pandaria"
 AUTO_ANNOUNCE_TEXTS = <table> {
 }
 SLASHCMD_HELP2 = <table> {
 }
 TRANSCRIPTOR_LOG_END = "Transcriptor logging ended."
 NOTESHAREERRORGROUPFINDER = "Notes cannot be shared in BGs, LFR, or LFG"
 INSTANCE_INFO_DETAIL_DEBUG = "Sender: %s ResultType: %s InstanceName: %s InstanceID: %s Difficulty: %d Size: %d Progress: %s"
 MOVABLE_BAR = "Drag me!"
 NOTE_SHARE_FAIL = "%s attempted to share note text with you for %s. However, mod associated with this ability is not installed or is not loaded. If you need this note, make sure you load the mod they are sharing notes for and ask them to share again"
 INS

**Comment by MysticalOS** [comment]
Trying to install it libless or via github checkout without pulling remotes?

libstub cannot be nil with a proper install

**Comment by QartemisT** [comment]
Sounds like whichever addon installer you have, failed to install it properly with libraries.
In any real-user case, this should never happen, and as such is a user error. Closing :)

**Comment by MysticalOS** [comment]
just want to add that my primary platform is macOS. dbm and other addon definitely work here. use curseforge app. it works well

**Comment by laundrevity** [comment]
Ah, I didn't realize an addon manager was necessary for DBM, I had just copied the folder to Interface/Addons. Installed using curseforge and works fine, thanks!

**Comment by MysticalOS** [comment]
It's not required, just helpful. to install it you probably just didn't put all/required folders in right place.
