### ISSUE TITLE
Error when clicking minimap buton

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DeadlyBossMods#52]
Upon first click at the minimap button for DBM I get this error message in chat. DBM still opens normally and when opening it again new error messages in chat don't appear. So only the first click after login causes it.

I tried to catch some logs using BugSack but it didn't work, it doesn't see anything. First screenshot was taken before I installed BugSack and second after. Notice the difference.

**To Reproduce**
1. Login into WoW.
2. Click on DBM minimap button.
4. See error in chat.

**Screenshots**

![dbm_first](https://user-images.githubusercontent.com/12860284/62823781-a9878000-bb9d-11e9-9871-dd32d02ec1a5.jpg)

![dbm_second](https://user-images.githubusercontent.com/12860284/62823789-c58b2180-bb9d-11e9-949f-fdf702dbc494.jpg)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Tried it with everything else disabled, still getting this error.

**Which version of DeadlyBossMods are you using?**

Latest stable 8.2.12. But latest alpha too.

**Was it working in a previous version? If yes, which was the last good one?**

Not sure, because I don't open it that much.

**Additional context**

I think it might be the problem with that lib LibDBIcon? Should I contact dev of the lib instead?

**Comment by MysticalOS** [comment]
Do you have any 3rd party modules installed that shouldn't be? such as DBM-VictorySounds or DBM-Profiles or DBM-Interrupts?

**Comment by Molkree** [comment]
Yes, Interrupts. No errors when I disabled it, thank you.

**Comment by MysticalOS** [comment]
Yes that'll do it. That module is no longer compatible with DBM, it's very out of date and no longer maintained by it's author.
