### ISSUE TITLE
Throne of Thunder Errors

### ISSUE THREAD

**Issue by reale411** [DeadlyBossMods/DeadlyBossMods#523]
DBM-Core-9.0.22-15-ge08cb53.zip
DBM-Pandaria-r140.zip

Happens on Tortos, Megaera nad Ji-Kun:

Message: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_4:SetPoint.
Time: Thu Mar 11 14:47:49 2021
Count: 1
Stack: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_4:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1513: in function `SetPosition'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:538: in function `Append'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:813: in function `CreateBar'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:11021: in function `Start'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:11660: in function `Start'
[string "@Interface\AddOns\DBM-ThroneofThunder\Tortos.lua"]:96: in function `OnCombatStart'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:6300: in function `StartCombat'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:5880: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:892: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:879>

Locals: (*temporary) = DBT_4 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = DBT_4 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = 0
(*temporary) = 0

**Comment by QartemisT** [comment]
This issue has been resolved in the latest alpha version of DBM-Core :)
