### ISSUE TITLE
Add more BrutalCombo timers to Xav the Unfallen encounter

### ISSUE THREAD

**Issue by REVERSE-MISAYA** [DeadlyBossMods/DeadlyBossMods#528]
There are only 5 hardcoded timers for the Xav encounter in the Theater of Pain dungeon. Could you please add some more, especially for groups that are slow with killing it? 8 timers max should be more than enough until it dies.

**Comment by MysticalOS** [comment]
Do you have a log of such an encounter? That'd help a lot

**Comment by REVERSE-MISAYA** [comment]
I will try to get you one soon :)

**Comment by behub-torch** [comment]
Hopefully this helps. Result of a DC at the start of the fight ;)

https://www.warcraftlogs.com/reports/WYMFwLcph7KTjRzn/#fight=last&type=casts&pull=10&hostility=1&source=41&ability=320644
