### ISSUE TITLE
DBM Warning: BFA version updates to 1.13

### ISSUE THREAD

**Issue by athonel** [DeadlyBossMods/DeadlyBossMods#53]
I updated the addon DBM. I did have the 8.2 release version. Automatic update went to 1.13 version for Classic wow. I had a warning pop up in my chat telling me to uninstall and find the correct version. 

![dbm warning](https://user-images.githubusercontent.com/54158428/63132886-59872f80-bf88-11e9-9751-2c0cad12d150.png)

**Comment by MysticalOS** [comment]
this was probably caused by having clent already running when the update to support classic rolled out (twitch client update)

I would hope restarting twitch client should fix this, if not though, there is literally nothing I can do about it and you'll have to report issue to curseforge.
