### ISSUE TITLE
attempt to index field 'mainAnchor' (a nil value) Error is Release version 9.0.23

### ISSUE THREAD

**Issue by Siniq** [DeadlyBossMods/DeadlyBossMods#530]
**Describe the bug**
Received an error with a weakaura that calls the mainAnchor index field.
Disabled the WA, and tried running 
`/run DBM.Bars.mainAnchor:SetPoint("LEFT",nil,"LEFT",200,200);DBM.Bars.secAnchor:SetPoint("LEFT",nil,"LEFT",200,0)` and received the same error.

Installed 9.0.22 and error cleared both in the weakaura and when running the above code (Did receive a different error regarding anchor family connection)

Upgraded to DBM-Core-9.0.22-23-gea0a4e5.zip and did not receive the error in the weakaura or the reset code.

**Do you have an error log of what happened?**
"attempt to index field 'mainAnchor' (a nil value)"

**To Reproduce**
1. Run the following `/run DBM.Bars.mainAnchor:SetPoint("LEFT",nil,"LEFT",200,200);DBM.Bars.secAnchor:SetPoint("LEFT",nil,"LEFT",200,0)`

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of DeadlyBossMods are you using?**
9.0.23

**Was it working in a previous version? If yes, which was the last good one?**
9.0.22

**Additional context**
Is this an outlier from the DBT rewrite that was part of 9.0.23 that will require a re-write/update to WA's that utilize the mainAnchor field?

**Comment by MysticalOS** [comment]
if using the timeline phoguild weak aura that's been broken for a while now. it's just even more broken now. it's an abandoned aura that doesn't support bar pausing nor the rewrite. maybe someone else will take it over and fix it but dbm will not be undoing its changes to make it work again. changes were made with good intent/ reason. any custom weak auras will need updating

**Comment by Siniq** [comment]
Thanks for the reply, I assumed it was something that would need fixed with the WA itself.

I am using that weakaura, and it is only broken for me in 9.0.23, works fine in 9.0.22-23

**Comment by MysticalOS** [comment]
it's actually broken on council longer then that. it doesn't support the bar pause callbacks so when dbm pauses bars the timeline doesn't.

**Comment by QartemisT** [comment]
There's a working version of this weakaura now available;

https://wago.io/RaidAbilityTimeline

If there's any other weakauras that have broken during this time, please direct them to our discord where we can provide future support :)
