### ISSUE TITLE
DBM DefaultSkin issue

### ISSUE THREAD

**Issue by Eagle9114** [DeadlyBossMods/DeadlyBossMods#537]
When entering the WOW Shadowlands game, a popup opens and states 👍 

Message: Interface\AddOns\DBM-DefaultSkin\Skin.lua:1: DBM-DefaultSkin no longer used, please remove
Time: Fri Mar 19 18:04:37 2021
Count: 1
Stack: Interface\AddOns\DBM-DefaultSkin\Skin.lua:1: DBM-DefaultSkin no longer used, please remove
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1106: in function `RegisterSkin'
[string "@Interface\AddOns\DBM-DefaultSkin\Skin.lua"]:1: in main chunk

Locals: (*temporary) = "DBM-DefaultSkin no longer used, please remove"
Message: (null)
Time: Fri Mar 19 18:04:58 2021
Count: 3

**Comment by QartemisT** [comment]
Simply delete "DBM-DefaultSkin" from your addons directory :)
