### ISSUE TITLE
LUA warning

### ISSUE THREAD

**Issue by macaire63** [DeadlyBossMods/DeadlyBossMods#539]
**Describe the bug**
I get the following error window popup on login, even after updating to most recent update from 10 min ago:

Message: Interface\AddOns\DBM-DefaultSkin\Skin.lua:1: DBM-DefaultSkin no longer used, please remove
Time: Sun Mar 21 18:50:43 2021
Count: 1
Stack: Interface\AddOns\DBM-DefaultSkin\Skin.lua:1: DBM-DefaultSkin no longer used, please remove
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1106: in function `RegisterSkin'
[string "@Interface\AddOns\DBM-DefaultSkin\Skin.lua"]:1: in main chunk

Locals: (*temporary) = "DBM-DefaultSkin no longer used, please remove"

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by QartemisT** [comment]
Delete "DBM-DefaultSkin" from your addons folder :)
