### ISSUE TITLE
Update changed my language to italian?

### ISSUE THREAD

**Issue by SavieSIlverfall** [DeadlyBossMods/DeadlyBossMods#56]
**Describe the bug**

My DBM should stay english by default into warning me. My menu's did not change. Just the warnings in general, I noticed that in particilaur on the ashara fight in eternal palace on normal. I think its italian as it gave Spaghetti on the degree.
**Do you have an error log of what happened?**

I am not getting any errors, whatsoever.

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Nope, Because I dont think this is an issue with any addon I have installed. 
**Which version of DeadlyBossMods are you using?**
8.2.14

**Was it working in a previous version? If yes, which was the last good one?**
Its working but its the language that is not in english ffor the warnings as well as some menu options.
**Additional context**
Edit: Parts seem to be in italian too.
https://gyazo.com/66b0c6a8e234c5ae37840eb39a9fa6ba

**Comment by MysticalOS** [comment]
Guess I should have reviewed that pull request more closely, i actually looked specifically for that happening in most of the mods, and figured "it looked good in most, probably good in all"

I'll push a new release for this

**Comment by SavieSIlverfall** [comment]
I updated my post with a gyazu screenshot some parts of the azshara menu specifically is also in italian, or what the language is.
