### ISSUE TITLE
DBM Classic Doesn't reconize TBC Classic

### ISSUE THREAD

**Issue by Hawkx1** [DeadlyBossMods/DeadlyBossMods#575]
As I'm playing on TBC Classic on my new Blood Elf Paladin I keep getting "<DBM> WARNING: This version of DBM is only meant to used with World of Warcraft: Classic. Uninstall this version and install correct version of DBM for Retail WoW." I will be disabling DBM on BC until this is fixed.

EDIT: Even after overwriting DBM Classic with DBM TBC the error is still appearing hence why I reopened this issue.

**Comment by MysticalOS** [comment]
perhaps overwriting in wrong addons folder or something, or installing INCORRECT TBC version (ie the retail one).

install https://www.curseforge.com/wow/addons/deadly-boss-mods/files/3290405
