### ISSUE TITLE
Wrong Version Warning

### ISSUE THREAD

**Issue by LotG-Catherine** [DeadlyBossMods/DeadlyBossMods#579]
**Describe the bug**
When entering a dungeon (WC), I get a warning notice that DBM Dungeons (Classic) could not be loaded because it is not designed for Classic WoW.  

**Do you have an error log of what happened?**
No. 

**To Reproduce**
1. Go to Wailing Caverns.
2. Enter dungeon.

**Screenshots**
![image](https://user-images.githubusercontent.com/19659259/119409017-47cdd280-bcac-11eb-8e47-618907f61051.png)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.  Same warning was generated.

**Which version of DeadlyBossMods are you using?**
I've got DBM-Core-2.5.3-bc.zip downloaded.  I deleted all of the old DBM folders, and installed from the zip file.  

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
Are you playing classic era or burning crusade classic? DBM 2.5.3 is NOT for classic era servers
