### ISSUE TITLE
Updated DBM and large/small bar sizes swapped

### ISSUE THREAD

**Issue by bgodbgg** [DeadlyBossMods/DeadlyBossMods#580]
I updated DBM.  Suddenly I noticed all my small bars were large and all my large bars were small.  In the settings, they got swapped, not sure how.  https://imgur.com/a/R270tkR

**To Reproduce**
It didn't happen for anyone else that I know of?

**Screenshots**

**Which version of DeadlyBossMods are you using?**
Alpha 9.0.28-26-ge49be96

**Was it working in a previous version? If yes, which was the last good one?**
I don't remember the last version I was using unfortunately - I last updated 1-2 weeks ago.

**Additional context**
omegal told me to open the bug report

**Comment by QartemisT** [comment]
Notice in your settings, small bar height is 35, and large bar height is 20 :)

**Comment by bgodbgg** [comment]
Yes, I didn't change that.  It happened automatically when I updated.  That's why I was creating the ticket.

**Comment by bgodbgg** [comment]
Asked again and 2 other people in my guild said it happened to them

**Comment by QartemisT** [comment]
Do you have any 3rd party addons that skin DBM bars at all? The default values for the heights are both set to 20...

**Comment by bgodbgg** [comment]
I do not

**Comment by QartemisT** [comment]
Have you at any point modified your bar heights, or were they always 20 prior to the update?

**Comment by bgodbgg** [comment]
I had modified them at one point which I believe is why it's that the weird 257.  MysticalOS mentioned maybe I had changed it during some pixel bug?

**Comment by QartemisT** [comment]
Do you have any quirky WeakAuras that work with timer bars at all? Could you send your "DBM-StatusBarTimers.lua" file located within the WTF folder.

**Comment by bgodbgg** [comment]
I do not.  It won't let me update a lua file so I put it in a txt.
[DBM-StatusBarTimers.lua.txt](https://github.com/DeadlyBossMods/DeadlyBossMods/files/6543800/DBM-StatusBarTimers.lua.txt)

**Comment by QartemisT** [comment]
Sadly, I've had 3 people test this, and unable to replicate it. I've reviewed the code, and couldn't see anything that could have caused that. So it has to be something 3rd party involved, and not much I can really do here to help.
Sorry for not being much further help.

**Comment by bgodbgg** [comment]
Np I understand.
