### ISSUE TITLE
[Classic] Error on login with DBMCore 1.13.4

### ISSUE THREAD

**Issue by kernighan** [DeadlyBossMods/DeadlyBossMods#59]
Date: 2019-08-31 10:14:02
ID: 1
Error occured in: Global
Count: 1
Message: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceComm-3.0".
Debug:
   [C]: ?
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:189: EmbedLibrary()
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:171: EmbedLibraries()
   ...ddOns\DBM-Core\Libs\ThreatClassic-1.0\ThreatBoot.lua:20: in main chunk
Locals:
(*temporary) = "Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceComm-3.0"."

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ACP, v3.5.6 
  AtlasLootClassic, vv1.1.8-beta
  BadBoy, vv1-classic
  BagBrother, v
  Bagnon, v8.2.3
  BetterVendorPrice, vv1.05.00-classic
  DBMCore, v1.13.4
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=121)

**Comment by MysticalOS** [comment]
Does error still happen if you turn off Wildpants?

**Comment by kernighan** [comment]
I don't have any such addon installed, is it somewhere in DBM?  It doesn't show up in ACP either.

**Comment by kernighan** [comment]
ah I see, Wildpants is part of Bagnon

**Comment by MysticalOS** [comment]
I know what problem is though. apparently threat lib requires ace for now. so I gotta redo release embedding ace libraries in it (yuck, a lot of bloat for a single threat function call). but hopefully the threatlib does some bloat culling in future

**Comment by MysticalOS** [comment]
Try the new version I just released 1.13.5

**Comment by kernighan** [comment]
No errors. :)
