### ISSUE TITLE
Add option to disable update notification

### ISSUE THREAD

**Issue by mariusandersen** [DeadlyBossMods/DeadlyBossMods#596]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when DBM messages me about updating the addon

**Describe the solution you'd like**
An option setting to disable DBM from spamming my chat about updating the addon

**Describe alternatives you've considered**
I tried BigWigs, I prefer DBM

**Additional context**
I think spamming about updating your addon is the same situation that led to end users starting to use AdBlock on websites. You update your addon several times each week and demand we update it immediately or you annoy us with an update notification, is how it feels to me. While I appreciate your continuous improvements to the addon, I don't want to see the "please update" notification every single time I log in to a character.

**Comment by MysticalOS** [comment]
This is never going to happen. I did this once and it resulted in users ignoring updates for really long periods of time and then the LFR/pugging experience got much worse. I decided that such an option simply shoudln't exist. A user should always be made aware that not updating their mods could have a negative impact on theirs (and other players) play experience.

DBM isn't a mod that makes your minimap prettier, it's a mod that helps group content go smoother, so it's in besst interest of community as a whole to keep users up to date.

it's literally only updated once a week early on then later on every 2-4 weeks. it's not even a popup it's just a chat message you see once per session (so it doesn't spam either). Updating it ensures you have all latest fixes and improvements to mods which is better for your raid as a whole.

**Comment by mariusandersen** [comment]
I don't object the option is default to notify about an update. 

If an end user makes an effort to go into their addon options to disable this warning, he clearly don't want to be notified about these updates. 

Are you saying you have experience with a majority of the addon end users manually disabling the update notification in options, then you see a severe decrease of updates in the addon, with this target audience also raiding and missing out on updated information that would have made them perform better in the dungeon/raid?

I truly don't see how my 61 Druid wanting to level in Hellfire Peninsula has any benefit in your latest Magtheridon strategy update of the week, asking him to update the addon.

When did you have an option to disable the update notifications? And if you had this, and it was so popular, that it made people manually disable the update notification, that you decided to remove it, don't you think it's something the public wanted?

**Comment by MysticalOS** [comment]
What the public doesn't want is some asshole in their raid wiping them because they felt like updating addons was an inconvinience, so that one person is making 20+ others suffer. I've seen it, too many times.

I don't just consider the needs of one person I have to consider needs and implications of how an out of date addon affects the entire group.

I agree that you don't need to rush an update at level 61 and could maybe tweak it to forgive if not max level, but there will be no disable.
