### ISSUE TITLE
Custom /range yards

### ISSUE THREAD

**Issue by KonstantinosKoubetsos** [DeadlyBossMods/DeadlyBossMods#598]
Enable so we can input custom range like it was before. For example Gruul needs 15yards range and we dont have that

**Comment by QartemisT** [comment]
Check the latest alpha version of DBM-TBC-Classic for this, we added a feature and change to make the default 18 yards.

On top of that, custom /range's CANNOT work inside of instances, because blizzard restricts it :)
Hope this solves your issue.
