### ISSUE TITLE
recent update instant errors 

### ISSUE THREAD

**Issue by Gambeck** [DeadlyBossMods/DeadlyBossMods#600]
Message: Interface\AddOns\DBM-Core\DBM-Core.lua:5291: main function has more than 200 local variables
Time: Mon Jun 28 16:56:01 2021
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:5291: main function has more than 200 local variables

Locals: 

============================

Message: Interface\AddOns\DBM-Core\DBM-Arrow.lua:6: attempt to index global 'DBM' (a nil value)
Time: Mon Jun 28 16:56:01 2021
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-Arrow.lua:6: attempt to index global 'DBM' (a nil value)
[string "@Interface\AddOns\DBM-Core\DBM-Arrow.lua"]:6: in main chunk

Locals: (*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'DBM' (a nil value)"

==========================================================

Message: Interface\AddOns\DBM-Core\DBM-Flash.lua:4: attempt to index global 'DBM' (a nil value)
Time: Mon Jun 28 17:07:18 2021
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-Flash.lua:4: attempt to index global 'DBM' (a nil value)
[string "@Interface\AddOns\DBM-Core\DBM-Flash.lua"]:4: in main chunk

Locals: (*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'DBM' (a nil value)"

=============================================================

Message: Interface\AddOns\DBM-Core\DBM-RangeCheck.lua:4: attempt to index global 'DBM' (a nil value)
Time: Mon Jun 28 17:07:18 2021
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-RangeCheck.lua:4: attempt to index global 'DBM' (a nil value)
[string "@Interface\AddOns\DBM-Core\DBM-RangeCheck.lua"]:4: in main chunk

Locals: (*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'DBM' (a nil value)"

=============================================================

Message: Interface\AddOns\DBM-Core\DBM-InfoFrame.lua:4: attempt to index global 'DBM' (a nil value)
Time: Mon Jun 28 17:07:18 2021
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-InfoFrame.lua:4: attempt to index global 'DBM' (a nil value)
[string "@Interface\AddOns\DBM-Core\DBM-InfoFrame.lua"]:4: in main chunk

Locals: (*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'DBM' (a nil value)"

===============================================================

Message: Interface\AddOns\DBM-Core\DBM-HudMap.lua:8: attempt to index global 'DBM' (a nil value)
Time: Mon Jun 28 17:07:18 2021
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-HudMap.lua:8: attempt to index global 'DBM' (a nil value)
[string "@Interface\AddOns\DBM-Core\DBM-HudMap.lua"]:8: in main chunk

Locals: ADDON_NAME = "DBM-Core"
(*temporary) = nil
(*temporary) = <table> {
 Version = 2
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'DBM' (a nil value)"

===================================================================

Message: Interface\AddOns\DBM-Core\DBM-Nameplate.lua:4: attempt to index global 'DBM' (a nil value)
Time: Mon Jun 28 17:07:18 2021
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-Nameplate.lua:4: attempt to index global 'DBM' (a nil value)
[string "@Interface\AddOns\DBM-Core\DBM-Nameplate.lua"]:4: in main chunk

Locals: (*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'DBM' (a nil value)"

===================================================================

Message: Interface\AddOns\DBM-Archaeology\Archaeology.lua:31: attempt to index global 'DBM' (a nil value)
Time: Mon Jun 28 17:07:18 2021
Count: 1
Stack: Interface\AddOns\DBM-Archaeology\Archaeology.lua:31: attempt to index global 'DBM' (a nil value)
[string "@Interface\AddOns\DBM-Archaeology\Archaeology.lua"]:31: in main chunk

Locals: settings = <table> {
 enabled = true
}
L = <table> {
 TabCategory_Archaeology = "Archaeology"
 Enable = "Enable Archaeology"
 DBM_LOOT_MSG = "([^%s]+).*Hitem:(%d+)"
 AreaGeneral = "Archaeology Settings"
}
soundFiles = <table> {
 1 = 14376
 2 = 14377
 3 = 14378
 4 = 14379
 5 = 14380
 6 = 14381
 7 = 14382
 8 = 14383
 9 = 14372
 10 = 14373
 11 = 14374
 12 = 14375
 13 = 8580
 14 = 8581
 15 = 8582
 16 = 8583
 17 = 8584
 18 = 8585
 19 = 8586
 20 = 8587
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 14378
(*temporary) = 14379
(*temporary) = 14380
(*temporary) = 14381
(*temporary) = 14382
(*temporary) = 14383
(*temporary) = 14372
(*temporary) = 14373
(*temporary) = 14374
(*temporary) = 14375
(*temporary) = 8580
(*temporary) = 8581
(*temporary) = 8582
(*temporary) = 8583
(*temporary) = 8584
(*temporary) = 8585
(*temporary) = 8586
(*temporary) = 8587
(*temporary) = "attempt to index global 'DBM' (a nil value)"

===============================================================

Message: Interface\AddOns\DBM-Interrupts\Interrupt.lua:1: attempt to index global 'DBM' (a nil value)
Time: Mon Jun 28 17:07:18 2021
Count: 1
Stack: Interface\AddOns\DBM-Interrupts\Interrupt.lua:1: attempt to index global 'DBM' (a nil value)
[string "@Interface\AddOns\DBM-Interrupts\Interrupt.lua"]:1: in main chunk

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'DBM' (a nil value)"

===================================================================

Message: Interface\AddOns\DBM-SpellTimers\SpellTimers.lua:29: attempt to index global 'DBM' (a nil value)
Time: Mon Jun 28 17:07:18 2021
Count: 1
Stack: Interface\AddOns\DBM-SpellTimers\SpellTimers.lua:29: attempt to index global 'DBM' (a nil value)
[string "@Interface\AddOns\DBM-SpellTimers\SpellTimers.lua"]:29: in main chunk

Locals: isClassic = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'DBM' (a nil value)"

==========================================================

Message: Interface\AddOns\DBM-Core\DBM-Core.lua:5291: main function has more than 200 local variables
Time: Mon Jun 28 17:07:21 2021
Count: 3

=======================================================================

Message: (null)
Time: Mon Jun 28 17:07:21 2021
Count: 27

**Comment by QartemisT** [comment]
Duplicate issue of #599
