### ISSUE TITLE
Script errors entering layer 9 of Torghast Skoldus Hall and Layer 9 of Upper Reaches Torghast

### ISSUE THREAD

**Issue by emmetotter** [DeadlyBossMods/DeadlyBossMods#602]
**Describe the bug**
Immediately entering Torghast Layer 9 Skoldus Hall or Layer 9 of Upper Reaches I received 5 script errors from DBM.  Entering layer 8 does not result in any errors.

**Do you have an error log of what happened?**
**Error 1 of 5**
Message: Interface\AddOns\DBM-Core\DBM-Core.lua:7538: bad argument #2 to 'split' (string expected, got table)
Time: Wed Jun 30 16:22:44 2021
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:7538: bad argument #2 to 'split' (string expected, got table)
[string "=[C]"]: in function `split'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:7538: in function `NewMod'
[string "@Interface\AddOns\DBM-Challenges\Shadowlands\Torghast.lua"]:1: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4360: in function `LoadMod'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4307: in function `LoadModsOnDemand'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4247: in function `func'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:1877: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:1868>

Locals: (*temporary) = ","
(*temporary) = <table> {
 iconID = 3747982
 name = "Torghast, Tower of the Damned"
}
(*temporary) = "string expected, got table"

**Error 2 of 5**
Message: Interface\AddOns\DBM-Core\DBM-Core.lua:7538: bad argument #2 to 'split' (string expected, got table)
Time: Wed Jun 30 16:22:44 2021
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:7538: bad argument #2 to 'split' (string expected, got table)
[string "=[C]"]: in function `split'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:7538: in function `NewMod'
[string "@Interface\AddOns\DBM-Challenges\BfA\NzothVisionStormwind.lua"]:1: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4360: in function `LoadMod'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4307: in function `LoadModsOnDemand'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4247: in function `func'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:1877: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:1868>

Locals: (*temporary) = ","
(*temporary) = <table> {
 name = "Horrific Vision of Stormwind"
}
(*temporary) = "string expected, got table"

**Error 3 of 5**
Message: Interface\AddOns\DBM-Core\DBM-Core.lua:7538: bad argument #2 to 'split' (string expected, got table)
Time: Wed Jun 30 16:22:44 2021
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:7538: bad argument #2 to 'split' (string expected, got table)
[string "=[C]"]: in function `split'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:7538: in function `NewMod'
[string "@Interface\AddOns\DBM-Challenges\BfA\NzothVisionOrgrimmar.lua"]:1: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4360: in function `LoadMod'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4307: in function `LoadModsOnDemand'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4247: in function `func'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:1877: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:1868>

Locals: (*temporary) = ","
(*temporary) = <table> {
 name = "Horrific Vision of Orgrimmar"
}
(*temporary) = "string expected, got table"

**Error 4 of 5**
Message: Interface\AddOns\DBM-Challenges\MoP\PGWhiteTiger.lua:5: bad argument #1 to 'match' (string expected, got table)
Time: Wed Jun 30 16:22:44 2021
Count: 1
Stack: Interface\AddOns\DBM-Challenges\MoP\PGWhiteTiger.lua:5: bad argument #1 to 'match' (string expected, got table)
[string "=[C]"]: in function `match'
[string "@Interface\AddOns\DBM-Challenges\MoP\PGWhiteTiger.lua"]:5: in function `nameModifier'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:7536: in function `NewMod'
[string "@Interface\AddOns\DBM-Challenges\MoP\PGWhiteTiger.lua"]:1: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4360: in function `LoadMod'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4307: in function `LoadModsOnDemand'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:4247: in function `func'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:1877: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:1868>

Locals: (*temporary) = <table> {
 iconID = 136349
 name = "Proving Grounds: White Tiger Temple"
}
(*temporary) = "(%S+.%S+): (%S+.%S+)"
(*temporary) = "string expected, got table"

**Error 5 of 5**
Message: (null)
Time: Wed Jun 30 16:22:44 2021
Count: 12

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes I only had DBM addons and no other addons enabled.

**Which version of DeadlyBossMods are you using?** DBM-Core-9.1.0.zip

**Was it working in a previous version? If yes, which was the last good one?**  No idea of previous version

**Additional context**

**Comment by QartemisT** [comment]
Update to the latest alpha version of DeadlyBossMods for this fix :)
