### ISSUE TITLE
UI error after upgrade on shadow Priest. 

### ISSUE THREAD

**Issue by thicks595** [DeadlyBossMods/DeadlyBossMods#604]
Keep getting this error 

Message: Interface\AddOns\DBM-Interrupts\Interrupt-Interrupt.lua:35: attempt to index field 'Bars' (a nil value)
Time: Thu Jul  1 10:04:28 2021
Count: 9
Stack: Interface\AddOns\DBM-Interrupts\Interrupt-Interrupt.lua:35: attempt to index field 'Bars' (a nil value)

Locals:

**Comment by QartemisT** [comment]
DBM-Interrupts is not supported by us :) Please go contact the author of this addon and ask them to update to the latest supported codebase of DBM
