### ISSUE TITLE
new bug

### ISSUE THREAD

**Issue by Gambeck** [DeadlyBossMods/DeadlyBossMods#607]
Message: Interface\AddOns\DBM-Interrupts\Interrupt.lua:1: attempt to index global 'DBM' (a nil value)
Time: Thu Jul  8 05:59:45 2021
Count: 1
Stack: Interface\AddOns\DBM-Interrupts\Interrupt.lua:1: attempt to index global 'DBM' (a nil value)
[string "@Interface\AddOns\DBM-Interrupts\Interrupt.lua"]:1: in main chunk

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'DBM' (a nil value)"

**Comment by MysticalOS** [comment]
DBM-Interrupts is not one of ours. it's a 3rd party mod that's no longer maintained. Remove that module to avoid seeing errors.

**Comment by Gambeck** [comment]
oh ok, thank you for letting me know.
