### ISSUE TITLE
attempt to index field 'Bars' (a nil value)

### ISSUE THREAD

**Issue by MorTD** [DeadlyBossMods/DeadlyBossMods#612]
Hi,

This error is happening ever since 9.1 dropped and it happens in any content involving DBM. I couldn't find a place to report specific dbm-interrupts issues, so I hope this repo is fine as well. 
In any case, this is happening all the time and I can't seem to find a solution online to remedy this (even temporarily). 

4901x DBM-Interrupts\Interrupt-Interrupt.lua:35: attempt to index field 'Bars' (a nil value)
[string "@DBM-Interrupts\Interrupt-Interrupt.lua"]:35: in function `handler'
[string "@DBM-Core\DBM-Core-9.1.1.lua"]:894: in function <DBM-Core\DBM-Core.lua:881>
[string "=(tail call)"]: ?
[string "@DBM-Core\DBM-Core-9.1.1.lua"]:894: in function <DBM-Core\DBM-Core.lua:881>

Locals:
self = <table> {
 revision = 20210701004539
 categorySort = <table> {
 }
 DefaultOptions = <table> {
 }
 iconRestore = <table> {
 }
 specwarns = <table> {
 }
 SyncThreshold = 8
 timers = <table> {
 }
 Options = <table> {
 }
 id = "Displays the CDs of interrupts to you (and your raid in some configurations)."
 SPELL_CAST_SUCCESS = <function> defined @DBM-Interrupts\Interrupt.lua:6
 modId = "DBM-Interrupts"
 localization = <table> {
 }
 announces = <table> {
 }
 vb = <table> {
 }
 optionCategories = <table> {
 }
}
args = <table> {
 sourceName = "Antor"
 destFlags = 2632
 event = "SPELL_CAST_SUCCESS"
 destRaidFlags = 0
 sourceRaidFlags = 0
 spellId = 96231
 spellName = "Rebuke"
 destName = "Mindseize Controller"
 destGUID = "Creature-0-4242-2222-19574-177646-0000E03361"
 timestamp = 1625306006.868000
 sourceFlags = 1304
 sourceGUID = "Player-3702-08A169A9"
}
key = nil
value = nil
Name = "Rebuke"
ID_no_taint = 96231
Duration = 15
_ = "Rebuke"
SpellIcon = 523893
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Strangulate = <table> {
 }
 SilencingShot = <table> {
 }
 OpticalBlast = <table> {
 }
 Disrupt = <table> {
 }
 Rebuke = <table> {
 }
 SpearHandStrike = <table> {
 }
 WindShear = <table> {
 }
 MindFreeze = <table> {
 }
 AvengersShield = <table> {
 }
 CounterShot = <table> {
 }
 SpellLock = <table> {
 }
 Pummel = <table> {
 }
 Silence = <table> {
 }
 SolarBeam = <table> {
 }
 CounterSpell = <table> {
 }
 SkullBash = <table> {
 }
}
(for control) = "Rebuke"
key = "Rebuke"
value = <table> {
 1 = "Rebuke"
 2 = 96231
 3 = 15
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 523893
(*temporary) = nil
(*temporary) = 523893
(*temporary) = 0
(*temporary) = "attempt to index field 'Bars' (a nil value)"

**Comment by QartemisT** [comment]
DBM-Interrupts is not an addon we support. We gave addon authors months to support our new codebase, and since DBM-Interrupts is no longer developed, its on them.

Apologies if this is an inconvenience for you.

**Comment by MorTD** [comment]
> DBM-Interrupts is not an addon we support. We gave addon authors months to support our new codebase, and since DBM-Interrupts is no longer developed, its on them.
> 
> Apologies if this is an inconvenience for you.

Thanks for letting me know. I thought this addon was part of the DBM pack because it was installed when I installed DBM from curseforge. I'll be disabling it, then. Cheers.
