### ISSUE TITLE
Sylvanas bugging out 

### ISSUE THREAD

**Issue by AngeliqueDawnbringer** [DeadlyBossMods/DeadlyBossMods#626]
**Describe the bug**

Message: ...ddOns\DBM-SanctumOfDomination\SylvanasWindrunner.lua:852: attempt to call method 'combinedShow' (a nil value)
Time: Tue Jul 20 22:28:30 2021
Count: 37
Stack: ...ddOns\DBM-SanctumOfDomination\SylvanasWindrunner.lua:852: attempt to call method 'combinedShow' (a nil value)
[string "@Interface\AddOns\DBM-SanctumOfDomination\SylvanasWindrunner.lua"]:852: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:894: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:881>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:894: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:881>

Locals: self = <table> {
 stats = <table> {
 }
 SPELL_AURA_REMOVED = <function> defined @Interface\AddOns\DBM-SanctumOfDomination\SylvanasWindrunner.lua:954
 SyncThreshold = 8
 numBoss = 1
 ignoreBestkill = false
 minSyncRevision = 20210712000000
 lastAntiSpam1 = 119349.684000
 revision = 20210713072200
 creatureId = 175732
 iconRestore = <table> {
 }
 OnCombatStart = <function> defined @Interface\AddOns\DBM-SanctumOfDomination\SylvanasWindrunner.lua:333
 inCombatOnlyEventsRegistered = 1
 encounterId = 2435
 name = "Banshee Wail"
 localization = <table> {
 }
 announces = <table> {
 }
 optionCategories = <table> {
 }
 SPELL_AURA_APPLIED_DOSE = <function> defined @Interface\AddOns\DBM-SanctumOfDomination\SylvanasWindrunner.lua:730
 SPELL_CAST_START = <function> defined @Interface\AddOns\DBM-SanctumOfDomination\SylvanasWindrunner.lua:408
 specwarns = <table> {
 }
 OnCombatEnd = <function> defined @Interface\AddOns\DBM-SanctumOfDomination\SylvanasWindrunner.lua:384
 lastAntiSpam3 = 119604.235000
 modelId = 95032
 id = "2441"
 lastWipeTime = 118597.783000
 inCombat = true
 CHAT_MSG_RAID_BOSS_EMOTE = <function> defined @Interface\AddOns\DBM-SanctumOfDomination\SylvanasWindrunner.lua:1017
 SPELL_AURA_REMOVED_DOSE = <function> defined @Interface\AddOns\DBM-SanctumOfDomination\SylvanasWindrunner.lua:1005
 SPELL_AURA_APPLIED = <function> defined @Interface\AddOns\DBM-SanctumOfDomination\SylvanasWindrunner.lua:730
 hotfixNoticeRev = 20210712000000
 lastAntiSpam2 = 119640.160000
 zones = <table> {
 }
 combatInfo = <table> {
 }
 Options = <table> {
 }
 timers = <table> {
 }
 addon = <table> {
 }
 categorySort = <table> {
 }
 OnTimerRecovery = <function> defined @Interface\AddOns\DBM-SanctumOfDomination\SylvanasWindrunner.lua:396
 instanceId = 1193
 findFastestComputer = <table> {
 }
 SPELL_CREATE = <function> defined @Interface\AddOns\DBM-SanctumOfDomination\SylvanasWindrunner.lua:670
 SPELL_CAST_SUCCESS = <function> defined @Interface\AddOns\DBM-SanctumOfDomination\SylvanasWindrunner.lua:594
 modId = "DBM-SanctumOfDomination"
 usedIcons = <table> {
 }
 DefaultOptions = <table> {
 }
 vb = <table> {
 }
 inCombatOnlyEvents = <table> {
 }
}
args = <table> {
 sourceName = "Mawforged Summoner"
 destFlags = 1300
 event = "SPELL_AURA_APPLIED"
 spellId = 351451
 sourceRaidFlags = 0
 spellName = "Curse of Lethargy"
 destRaidFlags = 0
 destName = "Ravnur-Kazzak"
 destGUID = "Player-1305-0C020E00"
 timestamp = 1626812910.540000
 sourceFlags = 2632
 sourceGUID = "Creature-0-4240-2450-28470-177891-00007731E3"
}
spellId = 351451
(*temporary) = nil
(*temporary) = <table> {
 type = "target"
 spellId = 351451
 option = "announceother351451target"
 color = <table> {
 }
 text = "Curse of Lethargy on >%s<"
 announceType = "target"
 combinedcount = 0
 mod = <table> {
 }
 combinedtext = <table> {
 }
 sound = 1
 icon = 3528305
 spellName = "Curse of Lethargy"
}
(*temporary) = 0.300000
(*temporary) = "Ravnur-Kazzak"
(*temporary) = "attempt to call method 'combinedShow' (a nil value)"
specWarnWindrunner = <table> {
 voiceOptionId = "Voice347504"
 hasVoice = 2
 spellId = 347504
 icon = 236560
 option = "SpecWarn347504count"
 text = "Windrunner! (%s)"
 flash = 2
 combinedcount = 0
 mod = <table> {
 }
 announceType = "count"
 type = "count"
 combinedtext = <table> {
 }
 sound = true
 spellName = "Windrunner"
}
allTimers = <table> {
 normal

Every single time towards the third platform

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
already fixed in alpha, i'll have a new release out soon™
