### ISSUE TITLE
Interrupts 

### ISSUE THREAD

**Issue by norris2930** [DeadlyBossMods/DeadlyBossMods#628]
**Describe the bug**
<I have seen the castbar pop up from a creature, if I interrupt the spell or not i get error>

**Do you have an error log of what happened?**
<Message: Interface\AddOns\DBM-Interrupts\Interrupt.lua:35: attempt to index field 'Bars' (a nil value)
Time: Thu Jul 22 08:37:53 2021
Count: 24
Stack: Interface\AddOns\DBM-Interrupts\Interrupt.lua:35: attempt to index field 'Bars' (a nil value)
[string "@Interface\AddOns\DBM-Interrupts\Interrupt.lua"]:35: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:894: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:881>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:894: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:881>

Locals: self = <table> {
 revision = 20210722040749
 categorySort = <table> {
 }
 DefaultOptions = <table> {
 }
 iconRestore = <table> {
 }
 specwarns = <table> {
 }
 SyncThreshold = 8
 timers = <table> {
 }
 Options = <table> {
 }
 id = "Displays the CDs of interrupts to you (and your raid in some configurations)."
 SPELL_CAST_SUCCESS = <function> defined @Interface\AddOns\DBM-Interrupts\Interrupt.lua:6
 modId = "DBM-Interrupts"
 localization = <table> {
 }
 announces = <table> {
 }
 vb = <table> {
 }
 optionCategories = <table> {
 }
}
args = <table> {
 sourceName = "Negative-LaughingSkull"
 destFlags = 2632
 event = "SPELL_CAST_SUCCESS"
 destRaidFlags = 0
 sourceRaidFlags = 0
 spellId = 106839
 spellName = "Skull Bash"
 destName = "Lieutenant Voxiferus"
 destGUID = "Creature-0-3137-2222-480-178294-000079665B"
 timestamp = 1626957472.200000
 sourceFlags = 1304
 sourceGUID = "Player-67-0DB9AC7A"
}
key = nil
value = nil
Name = "SkullBash"
ID_no_taint = 106839
Duration = 15
_ = "Skull Bash"
SpellIcon = 236946
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Strangulate = <table> {
 }
 SilencingShot = <table> {
 }
 OpticalBlast = <table> {
 }
 Disrupt = <table> {
 }
 Rebuke = <table> {
 }
 SpearHandStrike = <table> {
 }
 WindShear = <table> {
 }
 MindFreeze = <table> {
 }
 AvengersShield = <table> {
 }
 CounterShot = <table> {
 }
 SpellLock = <table> {
 }
 Pummel = <table> {
 }
 Silence = <table> {
 }
 SolarBeam = <table> {
 }
 CounterSpell = <table> {
 }
 SkullBash = <table> {
 }
}
(for control) = "SkullBash"
key = "SkullBash"
value = <table> {
 1 = "SkullBash"
 2 = 106839
 3 = 15
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 236946
(*temporary) = nil
(*temporary) = 236946
(*temporary) = 0
(*temporary) = "attempt to index field 'Bars' (a nil value)"
->

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
nope
**Which version of DeadlyBossMods are you using?**
newest
**Was it working in a previous version? If yes, which was the last good one?**
maybe a month ago
**Additional context**

**Comment by QartemisT** [comment]
DBM-Interrupts is not an addon we support. We gave addon authors months to support our new codebase, and since DBM-Interrupts is no longer developed, its on them.

Apologies if this is an inconvenience for you.
