### ISSUE TITLE
WoD Garrison Invasion - DBM has no function

### ISSUE THREAD

**Issue by Mike160770** [DeadlyBossMods/DeadlyBossMods#630]
DBM Core refuses to load the WoD-Module when you are in your garrison after updating the add-on.

**Comment by QartemisT** [comment]
Is there any form of stacktrace/error regarding this? You can typically see these if you have something like BugSack installed.

**Comment by QartemisT** [comment]
Aha never mind, I see the issue. This is awaiting a DBM core update which should be coming soon :tm:

**Comment by QartemisT** [comment]
This will now be resolved as of the latest DBM release :)
