### ISSUE TITLE
Fatescribe Roh-Kalo crash problem 

### ISSUE THREAD

**Issue by macadamya** [DeadlyBossMods/DeadlyBossMods#635]
2x DBM-SanctumOfDomination\FatescribeRohKalo.lua:419: attempt to index field '?' (a nil value)
[string "@DBM-SanctumOfDomination\FatescribeRohKalo.lua"]:419: in function `handler'
[string "@DBM-Core\DBM-Core-9.1.7-1-g1552102.lua"]:894: in function <DBM-Core\DBM-Core.lua:881>
[string "=(tail call)"]: ?
[string "@DBM-Core\DBM-Core-9.1.7-1-g1552102.lua"]:894: in function <DBM-Core\DBM-Core.lua:881>

Locals:
Skipped (In Encounter)

After viewing the frame drop, shutdown, or blue screen on the raids, bugsack has this error. Is there a solution?

**Comment by MysticalOS** [comment]
That's not likely cause of the frame rop and blue screen, But i'll still try to fix it regardless. What difficulty was this on?
