### ISSUE TITLE
Timer Debug is misidentifying timers and spitting out invalid reports

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DeadlyBossMods#639]
Inline icons somehow break timer Id identification in debug code, causing it to mis report timers invalid that are perfectly fine

Example:
"<605.25 19:35:45> [DBM_TimerStart] Timer326039next#Endless Torment#24.2#1394887#next#326039#2#2421#nil#nil#Endless Torment#nil", -- [3625]
"<629.31 19:36:09> [DBM_Debug] Timer |TInterface\\EncounterJournal\\UI-EJ-Icons.blp:22:22:0:0:255:66:133:153:7:27|tRite of Supremacy (Timer326039next) refreshed before expired. Remaining time is : 13.2. Please report
"<629.31 19:36:09> [DBM_TimerStart] Timer326039next#Endless Torment#11.3#1394887#next#326039#2#2421#nil#nil#Endless Torment#nil", -- [3755]

In this example, a valid 24 second timer is started for endless torment, but yet it reports refreshed before expired on Rite of supremacy even though it was starting a new endless torment timer. more baffling, it has correct timer Id in () but wrong timer name and icon in text.

**Comment by QartemisT** [comment]
Debug appears to be once again working as intended :)
