### ISSUE TITLE
Popup error on every boss encounter

### ISSUE THREAD

**Issue by SylverrJ** [DeadlyBossMods/DeadlyBossMods#65]
**Describe the bug**

I just wanted to kill the bosses but instead get constantly interrupted with a pop-up error.

**Do you have an error log of what happened?**

Message: Interface\AddOns\DBM-Core\DBM-Core.lua:6415: PlaySoundFile Error - Invalid fileDataID for sound.
Time: Sun Sep  8 20:03:05 2019
Count: 2
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:6415: PlaySoundFile Error - Invalid fileDataID for sound.
[C]: ?
[C]: ?
Interface\AddOns\DBM-Core\DBM-Core.lua:6415: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:6394>
Interface\AddOns\DBM-Core\DBM-Core.lua:6424: in function `PlaySoundFile'
Interface\AddOns\DBM-Core\DBM-Core.lua:9956: in function `PlaySpecialWarningSound'
Interface\AddOns\DBM-Core\DBM-Core.lua:9556: in function `Show'
Interface\AddOns\DBM-Azeroth-BfA\Ulmath.lua:49: in function `handler'
Interface\AddOns\DBM-Core\DBM-Core.lua:762: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:749>
(tail call): ?
Interface\AddOns\DBM-Core\DBM-Core.lua:762: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:749>

Locals: 

**To Reproduce**

Engage any boss.

**Screenshots**
![WoWScrnShot_090819_200256](https://user-images.githubusercontent.com/55069231/64497683-b3bc9d00-d275-11e9-92ca-6d07608477c7.jpg)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

*Which version of DeadlyBossMods are you using?**
8.2.16

**Was it working in a previous version? If yes, which was the last good one?**
Yes, but it has been a few weeks.

**Additional context**

**Comment by MysticalOS** [comment]
few weeks or few months? honestly, I'd need to see your sound config to get bottom of that. but I don't understand why sound config didn't migrate from old paths to IDs automatically, i'd need to know current sound settings to know problem, might even be better if you can upload dbm-core.lua from your saved variable folder

**Comment by SylverrJ** [comment]
Weeks. It has been working perfectly for a long time, then after weekly reset one day, this happened. I wish I had noted the date, my best guess is about three weeks ago.

I tried to attach my dbm-core.lua file from my saved variable folder, but apparently it doesn't like the file type. I'll just Copy/Paste the file:

DBM_UsedProfile = "Default"
DBM_UseDualProfile = true
DBM_CharSavedRevision = 20190904205122

I don't mind reinstalling DBM from scratch, I just need to know which files to manually delete, as just deleting and reinstalling the add-on (I use Twitch) doesn't fix the problem. :-(

Thanks!

**Comment by MysticalOS** [comment]
that'd probably fix it, but I want to isolate cause so better migration can be added. I'd need full contents of config, not just those lines
use pastebin or another site like it maybe

**Comment by SylverrJ** [comment]
![image](https://user-images.githubusercontent.com/55069231/64499093-2bda9100-d27d-11e9-9bcf-5c5706b7ce66.png)

Those four lines were all of the content of "dbm-core.lua", the file is tiny. (I tried to show that with the attached screenshot, my File Explorer is on the second monitor.) Do you mean you need the contents of other DBM files? Or am I just not understanding what you need? I apologize, while I know how to do a lot of things on my computer, working with add-on code is way out of my expertise, but I am happy to provide any information you require!

I need to sign off for the evening, but would be happy to provide any more information you need tomorrow.

Thanks!

**Comment by MysticalOS** [comment]
Account\savedvariables

not account\realm\savedvariables

and not

account\realm\character\savedvariables

either

**Comment by SylverrJ** [comment]
The ...\Account\SavedVariables folder is empty, BUT I think I found the one you are wanting.

My ...\Account\MSSYLV\SavedVariables\DBM-Core.lua:

DBM_AllSavedOptions = {
	["Default"] = {
		["DontShowFarWarnings"] = true,
		["ChosenVoicePack"] = "None",
		["DontShowHudMap2"] = false,
		["AlwaysPlayVoice"] = false,
		["ShowSWarningsInChat"] = true,
		["DontShowNameplateLines"] = false,
		["RangeFrameRadarY"] = 118.547981262207,
		["StatusEnabled"] = true,
		["DontRestoreIcons"] = false,
		["DontShowNameplateIcons"] = false,
		["CoreSavedRevision"] = 20190904205122,
		["RangeFrameX"] = 306.00048828125,
		["RangeFrameY"] = 153.463333129883,
		["FilterInterruptNoteName"] = false,
		["EnableModels"] = false,
		["SpecialWarningFlashAlph3"] = 0.4,
		["ArrowPoint"] = "TOP",
		["SWarnNameInNote"] = true,
		["FakeBWVersion"] = false,
		["InfoFramePoint"] = "BOTTOMRIGHT",
		["EventSoundMusicCombined"] = false,
		["SpecialWarningFlashCol2"] = {
			1, -- [1]
			0.5, -- [2]
			0, -- [3]
		},
		["WarningAlphabetical"] = true,
		["WarningFont"] = "Fonts\\FRIZQT__.TTF",
		["CheckGear"] = true,
		["SpecialWarningX"] = 0,
		["WorldBossAlert"] = false,
		["DontShowPT2"] = false,
		["DontShowSpecialWarnings"] = false,
		["EventSoundTurle"] = "None",
		["ShowQueuePop"] = true,
		["ShowAllVersions"] = true,
		["DebugMode"] = false,
		["DontShowTargetAnnouncements"] = true,
		["ShowWarningsInChat"] = true,
		["SpecialWarningFontCol"] = {
			1, -- [1]
			0.7, -- [2]
			0, -- [3]
		},
		["WarningFontStyle"] = "None",
		["EventSoundEngage2"] = "None",
		["InfoFrameY"] = 189.8856811523438,
		["ChatFrame"] = "DEFAULT_CHAT_FRAME",
		["WarningIconRight"] = true,
		["UseSoundChannel"] = "Master",
		["RangeFrameRadarX"] = 333.2442932128906,
		["ShowRespawn"] = true,
		["EventSoundWipe"] = "None",
		["AlwaysShowSpeedKillTimer2"] = false,
		["FilterDispel"] = true,
		["DebugLevel"] = 1,
		["LFDEnhance"] = true,
		["SpecialWarningFlashDura1"] = 0.4,
		["DontShowPTNoID"] = false,
		["HideGarrisonToasts"] = true,
		["RangeFramePoint"] = "BOTTOM",
		["SpecialWarningFontShadow"] = false,
		["EventMusicMythicFilter"] = true,
		["HideBossEmoteFrame2"] = true,
		["HideObjectivesFrame"] = true,
		["SpecialWarningFlashCol1"] = {
			1, -- [1]
			1, -- [2]
			0, -- [3]
		},
		["DontShowPTText"] = false,
		["SpecialWarningFontSize2"] = 35,
		["SpecialWarningFlashCol5"] = {
			0.2, -- [1]
			1, -- [2]
			1, -- [3]
		},
		["SpecialWarningFlashAlph4"] = 0.4,
		["PTCountThreshold2"] = 5,
		["EventSoundDungeonBGM"] = "None",
		["CountdownVoice2"] = "Kolt",
		["AutoAcceptGuildInvite"] = false,
		["ArrowPosX"] = 0,
		["AITimer"] = true,
		["SpecialWarningFlashDura3"] = 1,
		["SpecialWarningSound4"] = "Interface\\AddOns\\DBM-Core\\sounds\\ClassicSupport\\HoodWolfTransformPlayer01.ogg",
		["DisableSFX"] = false,
		["AutologBosses"] = false,
		["SpecialWarningFlashDura4"] = 0.7,
		["ShowFlashFrame"] = true,
		["SpecialWarningFlashCol3"] = {
			1, -- [1]
			0, -- [2]
			0, -- [3]
		},
		["WarningColors"] = {
			{
				["b"] = 0.9411764705882353,
				["g"] = 0.8,
				["r"] = 0.4117647058823529,
			}, -- [1]
			{
				["b"] = 0,
				["g"] = 0.9490196078431372,
				["r"] = 0.9490196078431372,
			}, -- [2]
			{
				["b"] = 0,
				["g"] = 0.5019607843137255,
				["r"] = 1,
			}, -- [3]
			{
				["b"] = 0.1019607843137255,
				["g"] = 0.1019607843137255,
				["r"] = 1,
			}, -- [4]
		},
		["MoviesSeen"] = {
			[1364] = true,
		},
		["SWarningAlphabetical"] = true,
		["ShowGuildMessagesPlus"] = false,
		["BlockNoteShare"] = false,
		["FilterInterrupt2"] = "TandFandBossCooldown",
		["DontShowPTCountdownText"] = false,
		["LatencyThreshold"] = 250,
		["ModelSoundValue"] = "Short",
		["FilterTrashWarnings2"] = true,
		["StripServerName"] = true,
		["ShowGuildMessages"] = true,
		["RangeFrameRadarPoint"] = "BOTTOM",
		["SpecialWarningY"] = 75,
		["AutoReplySound"] = true,
		["CountdownVoice3v2"] = "Pewsey",
		["RangeFrameUpdates"] = "Average",
		["MovieFilter2"] = "OnlyFight",
		["CustomSounds"] = 0,
		["RaidWarningSound"] = 6674,
		["DontRestoreRange"] = false,
		["RoleSpecAlert"] = true,
		["SpecialWarningFlashRepeat3"] = true,
		["ShortTimerText"] = true,
		["WhisperStats"] = false,
		["VoiceOverSpecW2"] = "DefaultOnly",
		["DontShowReminders"] = false,
		["DontPlayPTCountdown"] = false,
		["SpecialWarningFlashAlph5"] = 0.5,
		["SpecialWarningDuration2"] = 1.5,
		["HideQuestTooltips"] = true,
		["WarningIconLeft"] = true,
		["ShowEngageMessage"] = true,
		["RangeFrameSound1"] = "none",
		["RangeFrameLocked"] = false,
		["WarningFontSize"] = 20,
		["EventSoundVictory2"] = "None",
		["SpecialWarningFlashDura2"] = 0.4,
		["LastRevision"] = 0,
		["InfoFrameX"] = -92.91834259033203,
		["SettingsMessageShown"] = true,
		["HideTooltips"] = false,
		["RangeFrameSound2"] = "none",
		["DontShowSpecialWarningText"] = false,
		["DontShowUserTimers"] = false,
		["DontSetIcons"] = false,
		["BigBrotherAnnounceToRaid"] = false,
		["UseRetailShamanColor"] = false,
		["CountdownVoice"] = "Corsica",
		["BonusFilter"] = "Never",
		["SpecialWarningFlashRepeat2"] = false,
		["CountdownVoice3"] = "Smooth",
		["DisableStatusWhisper"] = false,
		["SpecialWarningFlashRepeat5"] = true,
		["AutoRespond"] = true,
		["EventDungMusicMythicFilter"] = true,
		["SWarnClassColor"] = true,
		["RangeFrameFrames"] = "radar",
		["DontPlayCountdowns"] = false,
		["ShowBigBrotherOnCombatStart"] = false,
		["SpecialWarningIcon"] = true,
		["WarningDuration2"] = 1.5,
		["SpecialWarningFlashAlph1"] = 0.3,
		["ShowDefeatMessage"] = true,
		["FilterTankSpec"] = true,
		["DontShowRangeFrame"] = false,
		["SpecialWarningFlashRepeat4"] = false,
		["InfoFrameShowSelf"] = false,
		["WarningFontShadow"] = true,
		["SpecialWarningFlashAlph2"] = 0.3,
		["SpecialWarningFlashDura5"] = 1,
		["DontShowBossTimers"] = false,
		["SpecialWarningFontStyle"] = "THICKOUTLINE",
		["WarningX"] = 0,
		["SpecialWarningFont"] = "Fonts\\FRIZQT__.TTF",
		["InfoFrameLines"] = 0,
		["WorldBossNearAlert"] = false,
		["DontShowBossAnnounces"] = false,
		["SpecialWarningFlashCol4"] = {
			1, -- [1]
			0, -- [2]
			1, -- [3]
		},
		["SpecialWarningFlashRepeatAmount"] = 2,
		["AutoAcceptFriendInvite"] = false,
		["WarningIconChat"] = true,
		["SpecialWarningPoint"] = "CENTER",
		["HideGuildChallengeUpdates"] = true,
		["SpecialWarningSound5"] = "Interface\\AddOns\\DBM-Core\\sounds\\ClassicSupport\\LOA_NAXX_AGGRO02.ogg",
		["DontSendYells"] = false,
		["ShowPizzaMessage"] = true,
		["AdvancedAutologBosses"] = false,
		["SpecialWarningFlashRepeat1"] = false,
		["ArrowPosY"] = -150,
		["SpecialWarningSound2"] = "Interface\\AddOns\\DBM-Core\\sounds\\ClassicSupport\\UR_Algalon_BHole01.ogg",
		["Enabled"] = true,
		["WarningY"] = 260,
		["EventSoundEngage"] = "",
		["FilterVoidFormSay"] = true,
		["WarningPoint"] = "CENTER",
		["AutoCorrectTimer"] = false,
		["DontShowInfoFrame"] = false,
		["LogOnlyRaidBosses"] = false,
		["EventSoundMusic"] = "None",
		["SpecialWarningSound3"] = "Interface\\AddOns\\DBM-Core\\sounds\\AirHorn.ogg",
		["SpecialWarningSound"] = 8174,
		["RLReadyCheckSound"] = true,
		["ForumsMessageShown"] = false,
		["AFKHealthWarning"] = false,
		["DisableGuildStatus"] = false,
		["HelpMessageVersion"] = 3,
	},
}
DBM_MinimapIcon = {
	["hide"] = true,
}

I think I see the issue, too, and it would have been caused by Twitch once updating my DBM to the "Classic" version one day when I hadn't realized it. I see a lot of my sound path names refer to "...\ClassicSupport\\filename" but I also do not know if that is normal, so I will leave this in your very capable hands!

Sylvia

**Comment by SylverrJ** [comment]
Ack my Notepad had wordwrap on. The file with it off:


DBM_AllSavedOptions = {
	["Default"] = {
		["DontShowFarWarnings"] = true,
		["ChosenVoicePack"] = "None",
		["DontShowHudMap2"] = false,
		["AlwaysPlayVoice"] = false,
		["ShowSWarningsInChat"] = true,
		["DontShowNameplateLines"] = false,
		["RangeFrameRadarY"] = 118.547981262207,
		["StatusEnabled"] = true,
		["DontRestoreIcons"] = false,
		["DontShowNameplateIcons"] = false,
		["CoreSavedRevision"] = 20190904205122,
		["RangeFrameX"] = 306.00048828125,
		["RangeFrameY"] = 153.463333129883,
		["FilterInterruptNoteName"] = false,
		["EnableModels"] = false,
		["SpecialWarningFlashAlph3"] = 0.4,
		["ArrowPoint"] = "TOP",
		["SWarnNameInNote"] = true,
		["FakeBWVersion"] = false,
		["InfoFramePoint"] = "BOTTOMRIGHT",
		["EventSoundMusicCombined"] = false,
		["SpecialWarningFlashCol2"] = {
			1, -- [1]
			0.5, -- [2]
			0, -- [3]
		},
		["WarningAlphabetical"] = true,
		["WarningFont"] = "Fonts\\FRIZQT__.TTF",
		["CheckGear"] = true,
		["SpecialWarningX"] = 0,
		["WorldBossAlert"] = false,
		["DontShowPT2"] = false,
		["DontShowSpecialWarnings"] = false,
		["EventSoundTurle"] = "None",
		["ShowQueuePop"] = true,
		["ShowAllVersions"] = true,
		["DebugMode"] = false,
		["DontShowTargetAnnouncements"] = true,
		["ShowWarningsInChat"] = true,
		["SpecialWarningFontCol"] = {
			1, -- [1]
			0.7, -- [2]
			0, -- [3]
		},
		["WarningFontStyle"] = "None",
		["EventSoundEngage2"] = "None",
		["InfoFrameY"] = 189.8856811523438,
		["ChatFrame"] = "DEFAULT_CHAT_FRAME",
		["WarningIconRight"] = true,
		["UseSoundChannel"] = "Master",
		["RangeFrameRadarX"] = 333.2442932128906,
		["ShowRespawn"] = true,
		["EventSoundWipe"] = "None",
		["AlwaysShowSpeedKillTimer2"] = false,
		["FilterDispel"] = true,
		["DebugLevel"] = 1,
		["LFDEnhance"] = true,
		["SpecialWarningFlashDura1"] = 0.4,
		["DontShowPTNoID"] = false,
		["HideGarrisonToasts"] = true,
		["RangeFramePoint"] = "BOTTOM",
		["SpecialWarningFontShadow"] = false,
		["EventMusicMythicFilter"] = true,
		["HideBossEmoteFrame2"] = true,
		["HideObjectivesFrame"] = true,
		["SpecialWarningFlashCol1"] = {
			1, -- [1]
			1, -- [2]
			0, -- [3]
		},
		["DontShowPTText"] = false,
		["SpecialWarningFontSize2"] = 35,
		["SpecialWarningFlashCol5"] = {
			0.2, -- [1]
			1, -- [2]
			1, -- [3]
		},
		["SpecialWarningFlashAlph4"] = 0.4,
		["PTCountThreshold2"] = 5,
		["EventSoundDungeonBGM"] = "None",
		["CountdownVoice2"] = "Kolt",
		["AutoAcceptGuildInvite"] = false,
		["ArrowPosX"] = 0,
		["AITimer"] = true,
		["SpecialWarningFlashDura3"] = 1,
		["SpecialWarningSound4"] = "Interface\\AddOns\\DBM-Core\\sounds\\ClassicSupport\\HoodWolfTransformPlayer01.ogg",
		["DisableSFX"] = false,
		["AutologBosses"] = false,
		["SpecialWarningFlashDura4"] = 0.7,
		["ShowFlashFrame"] = true,
		["SpecialWarningFlashCol3"] = {
			1, -- [1]
			0, -- [2]
			0, -- [3]
		},
		["WarningColors"] = {
			{
				["b"] = 0.9411764705882353,
				["g"] = 0.8,
				["r"] = 0.4117647058823529,
			}, -- [1]
			{
				["b"] = 0,
				["g"] = 0.9490196078431372,
				["r"] = 0.9490196078431372,
			}, -- [2]
			{
				["b"] = 0,
				["g"] = 0.5019607843137255,
				["r"] = 1,
			}, -- [3]
			{
				["b"] = 0.1019607843137255,
				["g"] = 0.1019607843137255,
				["r"] = 1,
			}, -- [4]
		},
		["MoviesSeen"] = {
			[1364] = true,
		},
		["SWarningAlphabetical"] = true,
		["ShowGuildMessagesPlus"] = false,
		["BlockNoteShare"] = false,
		["FilterInterrupt2"] = "TandFandBossCooldown",
		["DontShowPTCountdownText"] = false,
		["LatencyThreshold"] = 250,
		["ModelSoundValue"] = "Short",
		["FilterTrashWarnings2"] = true,
		["StripServerName"] = true,
		["ShowGuildMessages"] = true,
		["RangeFrameRadarPoint"] = "BOTTOM",
		["SpecialWarningY"] = 75,
		["AutoReplySound"] = true,
		["CountdownVoice3v2"] = "Pewsey",
		["RangeFrameUpdates"] = "Average",
		["MovieFilter2"] = "OnlyFight",
		["CustomSounds"] = 0,
		["RaidWarningSound"] = 6674,
		["DontRestoreRange"] = false,
		["RoleSpecAlert"] = true,
		["SpecialWarningFlashRepeat3"] = true,
		["ShortTimerText"] = true,
		["WhisperStats"] = false,
		["VoiceOverSpecW2"] = "DefaultOnly",
		["DontShowReminders"] = false,
		["DontPlayPTCountdown"] = false,
		["SpecialWarningFlashAlph5"] = 0.5,
		["SpecialWarningDuration2"] = 1.5,
		["HideQuestTooltips"] = true,
		["WarningIconLeft"] = true,
		["ShowEngageMessage"] = true,
		["RangeFrameSound1"] = "none",
		["RangeFrameLocked"] = false,
		["WarningFontSize"] = 20,
		["EventSoundVictory2"] = "None",
		["SpecialWarningFlashDura2"] = 0.4,
		["LastRevision"] = 0,
		["InfoFrameX"] = -92.91834259033203,
		["SettingsMessageShown"] = true,
		["HideTooltips"] = false,
		["RangeFrameSound2"] = "none",
		["DontShowSpecialWarningText"] = false,
		["DontShowUserTimers"] = false,
		["DontSetIcons"] = false,
		["BigBrotherAnnounceToRaid"] = false,
		["UseRetailShamanColor"] = false,
		["CountdownVoice"] = "Corsica",
		["BonusFilter"] = "Never",
		["SpecialWarningFlashRepeat2"] = false,
		["CountdownVoice3"] = "Smooth",
		["DisableStatusWhisper"] = false,
		["SpecialWarningFlashRepeat5"] = true,
		["AutoRespond"] = true,
		["EventDungMusicMythicFilter"] = true,
		["SWarnClassColor"] = true,
		["RangeFrameFrames"] = "radar",
		["DontPlayCountdowns"] = false,
		["ShowBigBrotherOnCombatStart"] = false,
		["SpecialWarningIcon"] = true,
		["WarningDuration2"] = 1.5,
		["SpecialWarningFlashAlph1"] = 0.3,
		["ShowDefeatMessage"] = true,
		["FilterTankSpec"] = true,
		["DontShowRangeFrame"] = false,
		["SpecialWarningFlashRepeat4"] = false,
		["InfoFrameShowSelf"] = false,
		["WarningFontShadow"] = true,
		["SpecialWarningFlashAlph2"] = 0.3,
		["SpecialWarningFlashDura5"] = 1,
		["DontShowBossTimers"] = false,
		["SpecialWarningFontStyle"] = "THICKOUTLINE",
		["WarningX"] = 0,
		["SpecialWarningFont"] = "Fonts\\FRIZQT__.TTF",
		["InfoFrameLines"] = 0,
		["WorldBossNearAlert"] = false,
		["DontShowBossAnnounces"] = false,
		["SpecialWarningFlashCol4"] = {
			1, -- [1]
			0, -- [2]
			1, -- [3]
		},
		["SpecialWarningFlashRepeatAmount"] = 2,
		["AutoAcceptFriendInvite"] = false,
		["WarningIconChat"] = true,
		["SpecialWarningPoint"] = "CENTER",
		["HideGuildChallengeUpdates"] = true,
		["SpecialWarningSound5"] = "Interface\\AddOns\\DBM-Core\\sounds\\ClassicSupport\\LOA_NAXX_AGGRO02.ogg",
		["DontSendYells"] = false,
		["ShowPizzaMessage"] = true,
		["AdvancedAutologBosses"] = false,
		["SpecialWarningFlashRepeat1"] = false,
		["ArrowPosY"] = -150,
		["SpecialWarningSound2"] = "Interface\\AddOns\\DBM-Core\\sounds\\ClassicSupport\\UR_Algalon_BHole01.ogg",
		["Enabled"] = true,
		["WarningY"] = 260,
		["EventSoundEngage"] = "",
		["FilterVoidFormSay"] = true,
		["WarningPoint"] = "CENTER",
		["AutoCorrectTimer"] = false,
		["DontShowInfoFrame"] = false,
		["LogOnlyRaidBosses"] = false,
		["EventSoundMusic"] = "None",
		["SpecialWarningSound3"] = "Interface\\AddOns\\DBM-Core\\sounds\\AirHorn.ogg",
		["SpecialWarningSound"] = 8174,
		["RLReadyCheckSound"] = true,
		["ForumsMessageShown"] = false,
		["AFKHealthWarning"] = false,
		["DisableGuildStatus"] = false,
		["HelpMessageVersion"] = 3,
	},
}
DBM_MinimapIcon = {
	["hide"] = true,
}

**Comment by SylverrJ** [comment]
[DBM-Core.txt](https://github.com/DeadlyBossMods/DeadlyBossMods/files/3592837/DBM-Core.txt)

Even better I made a copy of the file, renamed it to .txt and have it attached.

**Comment by MysticalOS** [comment]
I see what caused this. at some point you ran DBM-Classic, on retail, and all sound paths were set to DBM-Classic values. i can probably code in an internal fix to correct that. but in meantime you can fix it yourself very quickly by just resetting special warning sounds yourself.

**Comment by SylverrJ** [comment]
Yes, Twitch once "updated" my DBM to the "Classic" version without me
realizing until I was in the game at which point I manually re-installed
the correct DBM, but the damage would have already been done because I ran
it once. I will start up WoW and look for an option to reset my sounds in
DBM.

Sylvia

**Comment by SylverrJ** [comment]
Found it and confirmed it fixed all of the entries in my DBM-Core.lua. Thank you SO much for all of your help here! Your service has truly been above and beyond!

Sylvia

**Comment by MysticalOS** [comment]
No, thank you for helping debug down actual cause. I could have told you how to fix it and be done with it but I wanted to root out the cause so it can be auto repaired for other users affected by same issue.

**Comment by SylverrJ** [comment]
I really appreciate it, and have joined your Patreon in thanks! I have been
a DBM user from my early WoW days and will certainly continue.

Thanks again,
Sylvia
