### ISSUE TITLE
DBM, no timers for The Arcatras "Zereketh The Unbound"

### ISSUE THREAD

**Issue by killrawr** [DeadlyBossMods/DeadlyBossMods#656]
There are no timers for Zereketh The Unbound, spell Shadow Nova there is only alert during the cast but no timers before the cast

**Comment by QartemisT** [comment]
The timers for a majority of the TBC dungeons don't really have a "calculatable" timer for when they're going to occur.
I've reviewed a bunch of logs, and its just not something thats theoretically doable, sorry :(

**Comment by killrawr** [comment]
Thanks, appreciate the quick reply.
