### ISSUE TITLE
Add option to use singular pronouns for auto-replies

### ISSUE THREAD

**Issue by Gaviin1242** [DeadlyBossMods/DeadlyBossMods#662]
When DBM sends certain auto-replies during or after encounters, it uses a plural pronoun to refer to the current player.  E.g., "<Player> has defeated X!  **They** have Y total victories."

I understand the reasoning behind this and don't intend to start an argument, but could there be an option added that either allows DBM to use the singular pronoun associated with the current character's sex and/or the singular pronoun of the player's choice whenever the addon is configured to refer to the character not directly by name?

Thanks for your consideration.

**Comment by MysticalOS** [comment]
any added option requires translation to over a dozen languages and DBM doesn't have loalizers for most of them. It'd just be a term that is incorrectly translated for most users. I tend to decline anything that requires localizing if it's not a needed feature. Thanks for suggestion though.
