### ISSUE TITLE
libfade is causing chat tabs to fade

### ISSUE THREAD

**Issue by telias82** [DeadlyBossMods/DeadlyBossMods#665]
libfade is causing chat tabs (the writing) to fade after x amount of seconds of inactivity. I deleted libfade and they are working correctly

**Comment by Meorawr** [comment]
I'd suggest refiling this to [LibFrameFade](https://github.com/Meorawr/LibFrameFade/issues).

I'm not personally seeing any difference in behaviour with regards to chat frame (or tab) fading between the default Blizzard UI with no addons loaded versus just having the library loaded, so this is likely going to be an addon conflict - in which case I'll need a list of installed addons to verify things.

**Comment by Azilroka** [comment]
I know we have an issue with it.. We just haven't upgraded the library yet.

**Comment by Meorawr** [comment]
Should be fixed as of Meorawr/LibFrameFade@a5b580a62ba35205fd6cbaa504fbb546c9bd0589.

**Comment by Azilroka** [comment]
Good deal. 👍 <3

**Comment by MysticalOS** [comment]
CLosing issue as the new release would have grabbed new lib
