### ISSUE TITLE
DBM issue

### ISSUE THREAD

**Issue by Milky063** [DeadlyBossMods/DeadlyBossMods#69]
1x DBM-GUI\DBM-GUI_DropDown.lua:224: attempt to index field 'dropdown' (a nil value)
DBM-GUI\DBM-GUI_DropDown.lua:224: in function `Refresh'
DBM-GUI\DBM-GUI_DropDown.lua:70: in function `OnMouseWheel'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
self = DBM_GUI_DropDown {
 0 = <userdata>
 OnMouseWheel = <function> defined @DBM-GUI\DBM-GUI_DropDown.lua:55
 buttons = <table> {
 }
 HideMenu = <function> defined @DBM-GUI\DBM-GUI_DropDown.lua:208
 text = DBM_GUI_DropDownText {
 }
 ShowMenu = <function> defined @DBM-GUI\DBM-GUI_DropDown.lua:118
 ShowFontMenu = <function> defined @DBM-GUI\DBM-GUI_DropDown.lua:165
 Refresh = <function> defined @DBM-GUI\DBM-GUI_DropDown.lua:223
 offset = 1
 fontbuttons = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'dropdown' (a nil value)"
MAX_BUTTONS = 10

**Comment by MysticalOS** [comment]
Closing issue, as i suspect this issue had already been fixed in .19 alpha/release by time this was posted
