### ISSUE TITLE
Issue with 8.2.18

### ISSUE THREAD

**Issue by Kalarah** [DeadlyBossMods/DeadlyBossMods#70]
## Version: 8.2.18

Installed the latest version and I get the following lua error:

Message: Error loading Interface\AddOns\DBM-Party-BfA\localization.it.lua
Time: Thu Sep 12 19:01:16 2019
Count: 3

**Comment by MysticalOS** [comment]
I could not reproduce this issue with any testing. I even forced my client to load .it locals and they loaded just fine.
