### ISSUE TITLE
Twitch keeps over-writting classic DBM

### ISSUE THREAD

**Issue by Trindle1604** [DeadlyBossMods/DeadlyBossMods#71]
Every time I have to manually install the DBM-classic version Twitch sees it as needing an update and auto updates to the retail version. It can't see the classic version because, I assume, its not listed as different addons. When I search classic addons it only shows the 8.2.18 version and thats what it keeps force installing.

**Comment by MysticalOS** [comment]
The newer versions of twitch client shouldn't do that. if you've kept it open last few weeks without ever restarting PC or twitch client, it never got the update that handles game versions correctly. If simply restarting doesn't fix it, you may need to just reinstall twitch client. this is not a DBM bug though so closing this issue.

**Comment by MysticalOS** [comment]
https://github.com/DeadlyBossMods/DeadlyBossMods/issues/74
