### ISSUE TITLE
DBM Classic Version is Being Installed As Latest Version When Using the Twitch Client

### ISSUE THREAD

**Issue by Calesta** [DeadlyBossMods/DeadlyBossMods#74]
**Describe the bug**
Typically, when we users 'Update' an addon using the Twitch client the latest version is downloaded and installed.  A few addons like DBM have now started including a classic version in the same project as the retail version and it's causing the classic version to be interpreted as the latest version.  We have to manually revert the update to the retail version.

Please separate your projects if the code base can't support both versions.  Thanks.

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
This is a twitch issue, not a DBM issue. If enough users complain about issue to twitch, they might actualy make their client less garbage

**Comment by Calesta** [comment]
Other addons don't seem to have this problem only those who put two different code versions in the same project.

Thanks for the tips.  I don't have automatic updates on and I don't leave the Twitch client open.  I'll just flag DBM as one I'll have to revert each time.

**Comment by MysticalOS** [comment]
the proper way to do it is to put two addons in same project, and what most authors supporting classic are doing.

Wow Interface is even changing to that system soon.

Two diff projects for same addon (but diff game versions) is less ideal.

So it's important that when the system doesn't work correctly, bug reports are sent to twitch staff so they can collect data and be aware the system is not working right.

I definitely want your issue looked at, it just needs to be looked at by the right people. I can't do anything on my end.

**Comment by MysticalOS** [comment]
This continues to be a twitch issue. Every duplicate will refer this issue but all this issue is going to do is reaffirm that this is an issue twitch/curse needs to fix with their client.
