### ISSUE TITLE
/gquit taint error

### ISSUE THREAD

**Issue by DDCorkum** [DeadlyBossMods/DeadlyBossMods#76]
**Describe the bug**
AddOn DBM-Core has tainted the chat window in such a way that errors occur when typing /gquit.

**Do you have an error log of what happened?**
Message: Error: AddOn DBM-Core attempted to call a forbidden function (GuildLeave()) from a tainted execution path.
Debug:
   [C]: GuildLeave()
   ..\FrameXML\ChatFrame.lua:1941: ?()
   ..\FrameXML\ChatFrame.lua:4609: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4270: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4306: ChatEdit_OnEnterPressed()

**To Reproduce**
Type /gquit.  It isn't even necessary to be in a guild.   If you type /gquit a second time then it is actually possible to leave the guild or get the message you arn't in one.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.  It can occur with only DBM-Core, DBM Default Skin, DBM Options GUI and DBM Status Bar Timers  (every other module turned off).

**Which version of DeadlyBossMods are you using?**
From CHANGELOG.md: ## [1.13.8](https://github.com/DeadlyBossMods/DBM-Classic/tree/1.13.8) (2019-09-14)

**Was it working in a previous version? If yes, which was the last good one?**
Unknown.

**Comment by MysticalOS** [comment]
That's actually a bug in classic that needs to be fixed. /gquit isn't in secure slash handler, so once any addon registers slash commands of it's own, (which dbm and MANY other addons do), the non secure slash handler becomes "tainted" and can't call protected functions. Blizzard needs to fix this, like all the other protected functions they've forgotten to move to secure slash list.

**Comment by DDCorkum** [comment]
I was doing some research and came to the same conclusion.
https://us.battle.net/forums/en/wow/topic/20764046364?page=1

Recommend closing this.
