### ISSUE TITLE
When attemping to /gquit, error is thrown by DBM

### ISSUE THREAD

**Issue by Zhenocnra** [DeadlyBossMods/DeadlyBossMods#79]
Date: 2019-10-13 07:57:50
ID: 1
Error occured in: AddOn: DBM-Core
Count: 1
Message: Error: AddOn DBM-Core attempted to call a forbidden function (GuildLeave()) from a tainted execution path.
Debug:
   [C]: GuildLeave()
   ..\FrameXML\ChatFrame.lua:1941: ?()
   ..\FrameXML\ChatFrame.lua:4609: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4270: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4306: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  AlreadyKnown, v1.21
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.3.0
  AtlasLootClassicData, vv1.3.0
  AtlasLootClassicDungeonsAndRaids, vv1.3.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  Bartender4, v4.8.8
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  ClassicQuestLog, v1.4.6-Classic
  Coordinates, v2.1.0
  DBMCore, v1.13.15
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  ExtVendorUIClassic, v1.0.4
  EZJunk, v1.0.1
  EZQuest, v1.0.0
  FasterLooting, v1.1.1
  FiveSecondRule, v1.14
  GigaAutoResourcesTracker, v0.0.1
  Gnosis, vr215
  HandyNotes, vv1.5.9
  HandyNotesDungeonLocationsClassic, v1.03
  HandyNotesFlightMastersClassic, v1.06
  HandyNotesNPCsClassic, v1.17
  Informant, v8.2.6374 (SwimmingSeadragon)
  LetMeCast, v1.3
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  OmniBar, vv10.3
  OmniCC, v8.2.5
  Questie, v4.2.1 0 0f28ee6
  RecipeRadarClassic, v1.0.0.22
  Recount, vv1.13.2d
  ShadowedUnitFrames, vv4.2-Classic-Beta7
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.1.1.11302
  TitanClassicBag, v1.1.1.11302
  TitanClassicClock, v1.1.1.11302
  TitanClassicGold, v1.1.1.11302
  TitanClassicLocation, v1.1.1.11302
  TitanClassicLootType, v1.1.1.11302
  TitanClassicMail, v1.0.0.1
  TitanClassicPerformance, v1.1.1.11302
  TitanClassicRegen, v1.1.0.11302
  TitanClassicRepair, v1.1.1.11302
  TitanClassicRestPlus, v1.0.0.1
  TitanClassicVolume, v1.1.1.11302
  TitanClassicXP, v1.1.1.11302
  TitanProfessionsMulti, v1.3
  TotemTimers, v1.06
  TrackResources, v0.9
  UsedInRecipe, v1.0.3
  VanasKoS, v1.13.2.2
  weizPVP, v1.0-beta5
  WhatsTraining, v1.8.6
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=880)

**Comment by MysticalOS** [comment]
This is a blizzard bug that they are fixingin next patch, meanwhile there is absolutely nothing DBM or any other addon that uses slash comands can avoid.
