### ISSUE TITLE
Minimalistic ingame explanation of raid warnings

### ISSUE THREAD

**Issue by HolyDLX** [DeadlyBossMods/DeadlyBossMods#8]
Hey there!

I just got a quick question/suggestion regarding the meaning of some (voice pack) warnings.

---

**The Problem**
I am in a raid of casuall-minded people and we stumbled over some voice pack warnings that were not clear until we put some effort into looking it up on google.

**Example Problem**
Let's take the "Bait Now" or "Jetzt Ködern" (german) in the Stormwall Blockade encounter as an example.
For us neither the german translation, nor the original english text explained what was going to happen or should be done. If you are into the scene you will know the meaning, as a guild that is new to the encounter you will have no idea and this could be quite confusing.

We thought of a better german translation but could not come up with anything. In our opinion one has to know what is meant by this warning, which either involves learning the hard way (wiping and figuring it out yourself) or checking the webs for an explanation.

**The Suggested Solution**
It would be nice to have a "minimal" description of raid warnings for specific encounters.
I do not know if it is possible to check which boss I am on and let "/dbm guide" give a minimalistic description what each voice pack warning means. Either with a minimalistic UI or just some text whould be helpful.
I do not mean an ingame guide for the whole fight, bus simply a mapping of warning and mechanic.

---

I fully understand that DBM is not a full on guide addon and that one should not entirely rely on it for new fights, but a minimalistic explanation of warnings that deal with specific mechanics would be nice imho.

Thanks for your great work - Love the addon

**Comment by MysticalOS** [comment]
Between the dungeon journal, and all the videos/guides available on various sites, plus my limitted time, I feel this is something I'll have to decline.
