### ISSUE TITLE
Victory Sounds

### ISSUE THREAD

**Issue by BloodyFess** [DeadlyBossMods/DeadlyBossMods#81]
Is it possible to include  "Victory_FinalFantasyClassic.ogg" in DBM Core for always? Every time when DBM updated, I need to manually edit dbm-core.lua for adding a row
{text = "Classic FF Fanfare",value = "Interface\\AddOns\\DBM-Core\\sounds\\Victory\\Victory_FinalFantasyClassic.ogg", length=4},

**Comment by MysticalOS** [comment]
There is an api for adding external media packs. That is the correct way to add media, not editing core.

Review the existing media event packs to see how. In fact, that sound is ALREADY included in one of them.

https://www.curseforge.com/wow/addons/search?search=dbm+event
