### ISSUE TITLE
Bug with some special warning sound selections

### ISSUE THREAD

**Issue by Invisybr** [DeadlyBossMods/DeadlyBossMods#87]
When trying to set specific sounds to raid mechanics I am unable to use some of the sounds as when I select them it plays the "DESTRUCTION" sound file instead (this happens for Headless Horseman: Laugh, Illidan: Not Prepared2, and I get no sound at all for Illidan: Not prepared). Also, I can't seem to find the War Drums option in the list anywhere.

Screenshots:
![image](https://user-images.githubusercontent.com/51806686/68907553-a2cd5380-071e-11ea-8474-6cd0bcbadc93.png)
![image](https://user-images.githubusercontent.com/51806686/68907624-e031e100-071e-11ea-8277-9c96d9b2cf8d.png)

**Which version of DeadlyBossMods are you using?**
8.2.28

**Was it working in a previous version? If yes, which was the last good one?**
Yes, not sure last working version, I've been on a break from the game until recently

**Comment by MysticalOS** [comment]
Good catch, actually curious how no one else noticed this sooner. I'm not even sure how it happened to be honest.
