### ISSUE TITLE
Underrot Cragmaw Tantrum

### ISSUE THREAD

**Issue by T3ll1nG** [DeadlyBossMods/DeadlyBossMods#9]
Hi,
if you check to see the tantrum bar for the Cragmaw fight in Underrot the bar will not display and you still will only get the screen warning just before the ability starts. Is this intended?

**Comment by MysticalOS** [comment]
What difficulty? I recall fixing this up recently for mythic and being told it's perfect

**Comment by T3ll1nG** [comment]
M+ didn't see it in my last run but will check it again. Perhaps I'm mistaken.

**Comment by T3ll1nG** [comment]
Just checked it again and the bar is not showing in the Cragmaw fight. The bars for charge and Indigestion work just fine.
