### ISSUE TITLE
Retail updating as Classic 

### ISSUE THREAD

**Issue by Vekki99** [DeadlyBossMods/DeadlyBossMods#91]
**Describe the bug**

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes
**Which version of DeadlyBossMods are you using?**
apparently 1.13.21 but had whatever core was for BFA as I never played classic wow 
**Was it working in a previous version? If yes, which was the last good one?**
yes it was working previous version
**Additional context**
I usually just have the Twitch/Curse app update all of my Add-ons and it updated to the classic version and there is no DBM for retail available on the twitch app for some reason. But its available on the website but even if I manually transfer the files it still shows up as Classic WoW version

**Comment by MysticalOS** [comment]
Not a problem to be reported here, report it to twitch. I've never been able to reproduce this issue though so it's still a mystery why this only happens to some users. Probably why twitch can't fix it either. It only affects some users and none of them report it to twitch they all report it to us. 🗡 
https://github.com/DeadlyBossMods/DeadlyBossMods/issues/74
