### ISSUE TITLE
Keybinds get blocked by DBM Core

### ISSUE THREAD

**Issue by keldrog** [DeadlyBossMods/DeadlyBossMods#912]
**Describe the bug**
My Keybind was blocked by DBM Core

**Do you have an error log of what happened?**
See Screenshot

**Screenshots**
![Bild_2023-07-09_135911426](https://github.com/DeadlyBossMods/DBM-Retail/assets/139051900/31b903d2-38a0-4a47-be4c-70b3ebeb9db3)
![Bild_2023-07-09_135922851](https://github.com/DeadlyBossMods/DBM-Retail/assets/139051900/19a43fa2-da82-497d-8357-be9d4a614ec2)

**Which version of DeadlyBossMods are you using?**
10.1.13

**Was it working in a previous version? If yes, which was the last good one?**
before DF 10.1.5

**Additional context**
Happens very often but i dont get the context in which it happens

**Comment by QartemisT** [comment]
Hi @keldrog

Just to narrow this down a bit further, does this still occur when DBM-Core is disabled?
My suspect is with WoW taints like this, it usually just blames the LAST addon to access something, rather than the actual addon which is causing the issue.

**Comment by keldrog** [comment]
Hi @QartemisT 

no just DBM-Core. I tried it with Bigwigs but it happens there too but with no ther addon.

**Comment by keldrog** [comment]
Can it be my macro? I guess the problem exists till i used it.

/lon [known: Starfall] ST
/lon [noknown: Starfall] M+

**Comment by QartemisT** [comment]
Could you go to `World of Warcraft\_retail_\Logs` and send the taint.log file :)

**Comment by QartemisT** [comment]
Though, I may suspect it's the same issue located here;
https://github.com/Stanzilla/WoWUIBugs/issues/447
and https://github.com/BigWigsMods/BigWigs/issues/1353

**Comment by keldrog** [comment]
I will try to send the log as i have it. I can't reproduce it so i have to wait till it happens.

**Comment by keldrog** [comment]
Those are the last records of the taint.log after the error came up again

7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomLeftButton1:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomLeftButton1:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomLeftButton1:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomLeftButton1:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomLeftButton2:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomLeftButton2:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomLeftButton2:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomLeftButton2:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomLeftButton3:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomLeftButton3:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomLeftButton3:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomLeftButton3:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomLeftButton4:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomLeftButton4:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomLeftButton4:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomLeftButton4:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomLeftButton5:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomLeftButton5:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomLeftButton5:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomLeftButton5:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomLeftButton6:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomLeftButton6:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomLeftButton6:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomLeftButton6:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomLeftButton7:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomLeftButton7:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomLeftButton7:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomLeftButton7:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomLeftButton8:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomLeftButton8:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomLeftButton8:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomLeftButton8:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomLeftButton9:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomLeftButton9:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomLeftButton9:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomLeftButton9:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomLeftButton10:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomLeftButton10:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomLeftButton10:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomLeftButton10:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomLeftButton11:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomLeftButton11:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomLeftButton11:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomLeftButton11:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomLeftButton12:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomLeftButton12:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomLeftButton12:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomLeftButton12:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomRightButton1:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomRightButton1:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomRightButton1:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomRightButton1:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomRightButton3:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomRightButton3:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomRightButton3:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomRightButton3:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomRightButton5:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomRightButton5:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomRightButton5:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomRightButton5:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomRightButton7:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomRightButton7:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomRightButton7:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomRightButton7:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomRightButton9:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomRightButton9:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomRightButton9:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomRightButton9:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarBottomRightButton11:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarBottomRightButton11:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarBottomRightButton11:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarBottomRightButton11:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarLeftButton2:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarLeftButton2:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarLeftButton2:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarLeftButton2:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarLeftButton4:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarLeftButton4:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarLeftButton4:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarLeftButton4:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarLeftButton6:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarLeftButton6:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarLeftButton6:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarLeftButton6:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarLeftButton8:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarLeftButton8:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarLeftButton8:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarLeftButton8:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarLeftButton10:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarLeftButton10:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarLeftButton10:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarLeftButton10:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarLeftButton12:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarLeftButton12:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarLeftButton12:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarLeftButton12:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarRightButton2:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarRightButton2:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarRightButton2:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarRightButton2:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarRightButton4:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarRightButton4:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarRightButton4:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarRightButton4:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarRightButton6:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarRightButton6:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarRightButton6:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarRightButton6:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarRightButton8:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarRightButton8:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarRightButton8:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarRightButton8:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarRightButton10:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarRightButton10:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarRightButton10:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarRightButton10:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.168  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:585 MultiBarRightButton12:UpdateSpellHighlightMark()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:493 MultiBarRightButton12:Update()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:465 MultiBarRightButton12:UpdateAction()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:938 MultiBarRightButton12:OnEvent()
7/13 00:12:11.168      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.175  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()
7/13 00:12:11.175      Interface/FrameXML/ActionButton.lua:585 ActionButton1:UpdateSpellHighlightMark()
7/13 00:12:11.175      Interface/FrameXML/ActionButton.lua:493 ActionButton1:Update()
7/13 00:12:11.175      Interface/FrameXML/ActionButton.lua:465 ActionButton1:UpdateAction()
7/13 00:12:11.175      Interface/FrameXML/ActionButton.lua:938 ActionButton1:OnEvent()
7/13 00:12:11.175      Interface/FrameXML/ActionButton.lua:207
7/13 00:12:11.175  Execution tainted by DBM-Core while reading ON_BAR_HIGHLIGHT_MARKS - Interface/FrameXML/ActionButton.lua:62 GetOnBarHighlightMark()

**Comment by MysticalOS** [comment]
last records are utterly useless. this doesn't show us where taint occurred, only that DBM touched something that was already tainted by something else and got blamed for it. include ENTIRE log

**Comment by keldrog** [comment]
damn didn't know that. i reloaded and now the taint log is overwritten. i'll upload the entire log when the error occurs again....

**Comment by keldrog** [comment]
https://drive.google.com/file/d/1y-zwMJJb30HhSAO3jkk9zgbosvJMIPmT/view?usp=sharing

**Comment by MysticalOS** [comment]
could have just attached file to ticket, that requires requesting access

**Comment by RavenMind** [comment]
I'm having the same issue. It's also often when I switch specs via keybind. 
1 - Switch specs via bind "/lon SpecName
2- Press any ability button
Sometimes it will happen with Accountant or Accountant Classic enabled. Also happens with BigWigs/LittleWigs. (which I tried when I thought DBM was the problem. It USED to happen with Altoholic (One of the DataStore modules IIRC.), and a couple others, but hasn't happened with them since latest updates. Leads me to not want to just shrug this off as a problem with WoW's loudout macro.
If there's any logs or other info I can provide, please LMK.
Thanks for all the work on a wonderful add-on!

**Comment by MysticalOS** [comment]
Unfortunately there is nothing we can do, it's a blizzard bug, and it'll happen with addon addon registering slash command from what I understand. it just happens to be DBM in your cases

**Comment by RavenMind** [comment]
Okay, thanks. I appreciate the reply.

**Comment by Necrochrist** [comment]
I was having the same issue...DBM-Core rendering my entire keyboard useless unless I reloaded, but I went through all my addons enabling one by one and it turned out it was Prat 3.0 that was actually causing the issues.
