### ISSUE TITLE
Lord Kazzak timer

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DeadlyBossMods#952]
**Describe the bug**
![image](https://github.com/DeadlyBossMods/DBM-Retail/assets/12860284/19c1106a-70d2-40db-9a09-7d008fd72f75)

I think it was his second cast.

**Do you have an error log of what happened?**
No.

**Which version of DeadlyBossMods are you using?**
0c74fb1248e6920911b76214352c109ef654e0db

**Was it working in a previous version? If yes, which was the last good one?**
Dunno

**Additional context**

**Comment by emmericp** [comment]
The timer has since been removed because it's rather random and unreliable :/
