### ISSUE TITLE
DBM saying it is classic version

### ISSUE THREAD

**Issue by wendyemdub** [DeadlyBossMods/DeadlyBossMods#96]
I have only ever had the retail version installed but now it is telling me that it is for classic. I have reinstalled the correct addon and it still says it is meant for classic.

**Comment by MysticalOS** [comment]
Duplicate of https://github.com/DeadlyBossMods/DeadlyBossMods/issues/74 , Twitch client installed wrong version on you, you'll have to remove and clean install correct DBM to fix this
