### ISSUE TITLE
DBM Classic-Magmadar

### ISSUE THREAD

**Issue by Greeko85** [DeadlyBossMods/DeadlyBossMods#97]
**Twitch client installed classic/retail version on retail/classic**
if you are here to report an issue with wrong version of DBM installed on your game version, that is an issue you need to report to twitch support, not here. DBM correctly releases correct versions for correct game versions. There exists a bug in twitch client where for whatever reason it gets the two backwards. This issue seems to come and go and for SOME REASON twitch can't seem to figure out why. They just keep saying it's "resolved" only to have issue come back hours/days later, again and again and again. Any tickets created for this will be immediately closed since there is NOTHING that can be done on DBMs end.

If your issue is something else related to DBM, continue on

**Describe the bug**
 Since the combat log range nerf the Frenzy warnings on Magmadar are very unreliable-even when standing at approximately 35-40yds away they seem to get skipped/not announced.

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?** Latest available version at the time

**Was it working in a previous version? If yes, which was the last good one?** Prior to combat log nerf

**Additional context**

**Comment by MysticalOS** [comment]
I'll add syncing to that spell. any others you can think of off hand? I did add syncing to a few spells already because of this dumb nerf. but i figured I'd get reports of some more that needed it.

**Comment by MysticalOS** [comment]
Closing issue as it's now been fixed, plus it's also in the wrong project.
