### ISSUE TITLE
lua error on login

### ISSUE THREAD

**Issue by Nihlo** [DeadlyBossMods/DeadlyBossMods#98]
**Twitch client installed classic/retail version on retail/classic**
on curse directly 

**Describe the bug**
lua erron on login

**Do you have an error log of what happened?**

Error occured in: Global
Count: 1
Message: ...e\AddOns\DBM-Core\Libs\AceEvent-3.0\AceEvent-3.0.lua line 33:
   Attempt to register unknown event "GUILD_RECIPE_KNOWN_BY_MEMBERS"
Debug:
   [C]: RegisterEvent()
   ...e\AddOns\DBM-Core\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: OnUsed()
   ...ory\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:142: RegisterEvent()
   Skillet\Skillet.lua:608:
      Skillet\Skillet.lua:593
   [C]: ?
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:353: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:424: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:693:
      ..\FrameXML\UIParent.lua:658
Locals:
None

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**
latest 

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
The error is caused by Skillet or Atlas, NOT dbm

DBM is just first instance of ace library that was found.
