### ISSUE TITLE
Eranog LFR timer

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DeadlyBossMods#981]
**Describe the bug**

![image](https://github.com/DeadlyBossMods/DBM-Retail/assets/12860284/3ae6dd20-79f3-43bf-8b79-d8b02548987e)

**Do you have an error log of what happened?**

[Transcriptor_Eranog.zip](https://github.com/DeadlyBossMods/DBM-Retail/files/13928370/Transcriptor_Eranog.zip)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Nah

**Which version of DeadlyBossMods are you using?**
0a7a5bab4728d8b8755c39c0ce97596641348ec6

**Was it working in a previous version? If yes, which was the last good one?**
Dunno

**Comment by MysticalOS** [comment]
This had already been fixed and just never closed. oops.
