### ISSUE TITLE
Interrupt for Demo Warlock

### ISSUE THREAD

**Issue by Coldsteelxii** [DeadlyBossMods/DeadlyBossMods#998]
**Describe the bug**

DBM used to warn me to interrupt spells on my demo warlock with my felguard ability axe toss.  About a month ago its stopped giving me audio warnings.  I am not sure what changed.  

I know that axe toss is a stun and an interrupt but I liked the audio warnings to remind me in Mythic plus.

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes and it still didn't work.
**Which version of DeadlyBossMods are you using?**
10.2.27
**Was it working in a previous version? If yes, which was the last good one?**
Not sure.
**Additional context**

**Comment by MysticalOS** [comment]
By default I don't think warlock has interrupts enabled by default, so you have to enable them manually for each ability. they've never actually been enabled by default for warlocks.

did you import a profile on warlock from another class maybe and then reset to defaults recently?

But yeah you just have to go into each trash mod for each dungeon, and enable interrupt warnings you want to see.

**Comment by MysticalOS** [comment]
![Screenshot 2024-02-28 at 12 06 22 AM](https://github.com/DeadlyBossMods/DBM-Retail/assets/1899149/ea7549ea-4eba-4293-ae91-768f4439a031)
